### ISSUE TITLE
issue when using with karma

### ISSUE THREAD

**Issue by iamstarkov** [postcss/postcss-loader#10]
Sorry, I’m not sure if this issue related to this loader itself, but at least it throwing the error:

	ERROR in ./~/css-loader?sourceMap&-minimize!./~/postcss-loader!./~/sass-loader?sourceMap&sourceMapContents=true!./src/components/upgrade-action/upgrade-action.scss
	Module build failed: TypeError: Cannot read property 'defaults' of undefined
	    at Object.module.exports (/Users/vladimir/projects/webstatic-transparency-widget/node_modules/postcss-loader/index.js:24:26)
	 @ ./src/components/upgrade-action/upgrade-action.scss 4:14-172

When I’m using webpack itself it’s going well. On the other side, when I’m trying to run test with karma it’s falling with this error. karma.conf.js is here in [gist](https://gist.github.com/iamstarkov/57326565e382de761b7f), probably interesting parts are `loaders` and `plugins`.

**Comment by ai** [comment]
I will add a check to ignore PostCSS if PostCSS's config is missing, like in your case.

You don't need a PostCSS in Karma, right?

**Comment by iamstarkov** [comment]
Thanks.
Yes, probably I don’t need it in karma, 'cause as far as I understand I need markup and js for tests, and probably don’t need css for this

**Comment by ai** [comment]
Fix released in 0.4.4

**Comment by iamstarkov** [comment]
awsm!

**Comment by iamstarkov** [comment]
problem solved 😊
