### ISSUE TITLE
Api Scheme is not working anymore on newer Webpack 2 Versions

### ISSUE THREAD

**Issue by MDSLKTR** [postcss/postcss-loader#105]
As of 2.1.0-beta.23 you can't use the postcss section anymore as the config will not be valid since it's checked against a scheme now.
![unbenannt](https://cloud.githubusercontent.com/assets/9129687/19203107/d441fc98-8cd5-11e6-9268-acf109613be2.png)

**Comment by ai** [comment]
Fix in master. Release will be in next 5 days.
