### ISSUE TITLE
Importing CSS files

### ISSUE THREAD

**Issue by pburtchaell** [postcss/postcss-loader#11]
As of right now, my setup is that I have one CSS file in `app/styles/app.css`, which imports a number of modules. For example:

```
@import 'utils/variables.css';
@import 'modules/typography/headings.css';
@import 'modules/buttons/base.css';
@import 'modules/forms/base.css';
@import 'modules/layout/grid.css';
@import 'modules/layout/reset.css';
```

This CSS file is required in `app/app.js`.

```
import './styles/app';`
```

When I make a change to one of the module files, WebPack does not run. It will only run if I change `app/styles/app.css`—which makes sense, but is a bit inconvenient. I'm using the [postcss-loader plugin](https://github.com/postcss/postcss-import) to handle my `@import` declarations, so WebPack wouldn't know to "watch" the CSS files that are imported.

Is there a way to work around this issue though? Maybe by specifying a glob of files to watch in the PostCSS config?

**Comment by ai** [comment]
Double for https://github.com/postcss/postcss-loader/issues/8

**Comment by ai** [comment]
Current answer: use a webpack dependency :)

**Comment by pburtchaell** [comment]
Ah, didn't realize that was the same issue at a first glance. I'll jump in on the conversation there.
