### ISSUE TITLE
cssmoudles and postcss-mixins does not take effect. 

### ISSUE THREAD

**Issue by motorguo** [postcss/postcss-loader#112]
[cssmoudles and postcss-mixins does not take effect. ](https://github.com/postcss/postcss-mixins/issues/63)

```
webpack: v1.13.2
node: v6.2.0
```
source code:
```
@define-mixin fonts $fs, $col {
    font-size: $(fs)px;
    p { color: $col; }
}
.search {
	@mixin fonts 80, blue;
}
```
I want to be like this:
```
.search {
	font-size: 80px;
}
.search p {
    color: blue;
}
```

```
// webpack.config.js
import path from 'path';
import webpack from 'webpack';
import values from 'postcss-modules-values';
import autoprefixer from 'autoprefixer';
module.exports = {
    module: {
        loaders: [
            {test: /\.css$/, loaders: ['style!css?modules&importLoaders=1&localIdentName=[local]
             -[hash:base64:6]&importLoaders=!postcss']},
        ],
    },
    postcss: [
        values,
        autoprefixer({ browsers: ['last 2 versions'] }),
        require('postcss-nested'),
        require('postcss-mixins'),
    ],

}
```

**Comment by ai** [comment]
Could you test Autoprefixer by `user-select: none`?

**Comment by motorguo** [comment]
`Autoprefixer` no problem.

**Comment by ai** [comment]
Autoprefixer works? Hm, maybe I was wrong that it is postcss-loader issue.

You told that other syntax work. Could you repeat?

**Comment by motorguo** [comment]
Configuration should be no problem.
But this can be used:
```
@define-mixin fonts $elem, $fs {
    .$(elem) { font-size: $(fs)px; }
    .test { font-size: calc($(fs)px*10); }
}
@mixin fonts search, 40;
/* @mixin fonts search:hover, 89; */
```

**Comment by ai** [comment]
Try to put `postcss-nested` before `postcss-mixin`.

Also I recommend to use [PreCSS](https://github.com/jonathantneal/precss). It has all Sass-like plugins in right order.

**Comment by michael-ciniawsky** [comment]
@motorguo As @ai mentioned put `postcss-nested`before 'postcss-mixin` and maybe autoprefixer at the bottom, bc your nested and mixed CSS will not be prefixed otherwise :). Besides that is the mixin definition in the same file bzw. `require(file.css)' or are these different files/requires? Can you please give me information about your overall organisation of CSS ?

**Comment by motorguo** [comment]
@ai Thank you very much. 正解！

**Comment by motorguo** [comment]
@michael-ciniawsky Already solved. thank you for your reply.

**Comment by michael-ciniawsky** [comment]
👍
