### ISSUE TITLE
Webpack2 config question

### ISSUE THREAD

**Issue by Matmo10** [postcss/postcss-loader#113]
I'm having trouble getting this to work with webpack 2. I have an angular2 setup where I write .scss files, which get converted to .css by node-sass, which are ultimately require()'ed from my javascript (typescript) files (in angular2 components).  

I copied the configuration from the README verbatim, but the output (.css files) of my .scss files aren't autoprefixed. I tried a `display: flex` in my .scss, but i didn't see any vendor prefixes in the .css output,

I'm trying to incorporate autoprefixer (and potentially other postcss plugins) into this webpack config: https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L132.   But nothing seems to work. 

I'm pretty much lost here, am I totally missing some steps? Any suggestions?

**Comment by ai** [comment]
What version exactly you have?

What webpack/postcss config you have?

**Comment by Matmo10** [comment]
`"webpack": "2.1.0-beta.25"`

I don't have a postcss config file, is that the problem? I thought the section with 
```
require('precss'),
require('autoprefixer')
```

was a substitute for the config file, to specify which plugins to run? 


My webpack config for css is literally straight from the README at this point.

**Comment by ai** [comment]
Could you show full config? :)

**Comment by Matmo10** [comment]
Sure, here it is: https://gist.github.com/Matmo10/04da27830124b9ededfed03a214a5f93#file-webpack-config-ts-L86

**Comment by michael-ciniawsky** [comment]
In https://github.com/qdouble/angular-webpack2-starter/blob/master/webpack.config.ts#L132

```diff
- { test: /\.css$/, loader: 'raw-loader' }
+ { 
+   test: /\.scss$/,
+   use: [
+     'style-loader',
+     {loader: 'css-loader', options: { importLoaders: 1 }}, 
+     {loader: 'postcss-loader', options: { plugins: () => [ require('autoprefixer') ] }}
+     'sass-loader'
+   ]
+ }
```

**Comment by ai** [comment]
You have `.scss` files, but rule in webpack config has `test: /\.css$/,`, so it works only for `.css` files ;)

**Comment by Matmo10** [comment]
I write my styles with .scss, but my app uses the .css files, because Angular2 AOT compilation requires .css files at this point. 

So my angular2 components look like this: 

```
@Component({
   selector: 'my-loader',
   templateUrl: 'loader.component.html',
   styleUrls: ['loader.component.css']
})
```

In this case, I would actually be developing in `loader.component.scss`. Correct me if I'm wrong, but wouldn't webpack "test" here and use the .css block/rule/loader(s) ? 

Before I actually "compile" the angular2 project, I run `node-sass` to generate all my css files. While I develop, I also use `node-sass -w` to watch and continuously re-generate the css files.

**Comment by ai** [comment]
Could you show your exactly config if you changed that config? ;)

**Comment by Matmo10** [comment]
The gist I provided is my config, I've only made a few tweaks from the started project I linked above

**Comment by ai** [comment]
Could you show your final config, please? Not base config with a diff ;).

**Comment by Matmo10** [comment]
This is the full config: https://gist.github.com/Matmo10/62643df359d4697aac337165007ee013

**Comment by ai** [comment]
Could you try to use `postcss-loader` without Angular magic? I think problems is in `.scss` → `.css` Angular AOT things.

**Comment by Matmo10** [comment]
In my case, angular and webpack have no idea about the .scss files. I use `node-sass` totally outside the context of webpack to create the .css files, and that happens before I even start webpack. 

When the webpack starts compiling/serving the angular app, it should only know and care about the .css files. 


`{test: /\.css$/, loader: 'raw-loader'}` works fine to load the css (without any postcss stuff), but when I try the config from the README I get the following error: `Uncaught Error: Expected 'styles' to be an array of strings.(…)` from angular, because it seems to be loading an array of a single empty object instead of a string like the `raw-loader` does. 


I also see all these errors when I use `postcss-loader`, not sure if its related:

```
 66% building modules 794/850 modules 56 active ...orms/src/directives/error_examples.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 819/865 modules 46 active ...es/@angular/common/src/facade/intl.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 820/865 modules 45 active ...es/@angular/common/src/facade/intl.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 848/905 modules 57 active .../compiler/src/i18n/serializers/xtb.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 849/905 modules 56 active .../compiler/src/i18n/serializers/xtb.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 863/919 modules 56 active ...g-monitor/src/dock-monitor/reducer.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 864/919 modules 55 active ...g-monitor/src/dock-monitor/reducer.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 865/919 modules 54 active ...g-monitor/src/dock-monitor/reducer.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 66% building modules 866/919 modules 53 active ...g-monitor/src/dock-monitor/reducer.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
 67% building modules 883/919 modules 36 active ...g-monitor/src/dock-monitor/reducer.jsTypeError: Cannot read property 'config' of null
    at /Users/myUserNameHere/myProjectHere/ng2app/node_modules/postcss-load-config/index.js:50:22
```

Maybe I just need to read up on the differences between styles-loader, css-loader, and raw-loader. I feel like I just need the right combination or configuration to make it work, but all the documentation related to webpack is so lacking :|

**Comment by ai** [comment]
@michael-ciniawsky ^ seems like we still have warnings

Why you use `node-sass` outside of webpack and don’t do it by `sass-loader`? Sorry, your config seems like too complicated to me, I have no idea, how to fix it ;).

Try to make it more simple.

**Comment by Matmo10** [comment]
Because angular2 AOT compilation requires css at the moment. I'm using [this specialized angular loader](https://github.com/TheLarkInn/angular2-template-loader), but I see other angular2 projects which are also using this angular2-template-loader using the following loader setups for css:

https://github.com/angular/angular2-seed/blob/master/webpack.config.js :
```
      { test: /\.css$/, loaders: ['to-string-loader', 'css-loader'] }
```

https://github.com/aspnet/JavaScriptServices/blob/dev/templates/Angular2Spa/webpack.config.js :
```
            { test: /\.css$/, loader: 'to-string!css' },
```

https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.common.js :
```
        {
          test: /\.css$/,
          loaders: ['to-string-loader', 'css-loader']
        }
```

so I think I need just need to swap out raw-loader and use [to-string-loader](https://www.npmjs.com/package/css-to-string-loader#angular-2-component-styling) instead. I just need to get the order right now.

My understanding from the README is that postcss-loader should run first, then css-loader should run second.

So I think I need to do this:  `loaders: ['to-string-loader', 'css-loader', 'postcss-loader']` (or `loader: to-string!css!postcss`). I just need to figure out how to do this correctly in the webpack config now.

**Comment by ai** [comment]
Sorry, have no idea. You should ask somebody who know all that Angular magic or make build process more simple 😊.
