### ISSUE TITLE
Webpack(config) not passed to postcss function in postcss-loader 1.0.0

### ISSUE THREAD

**Issue by oyvinmar** [postcss/postcss-loader#116]
The following example does not work with webpack 1.13.x and postcss-loader 1.0.0 (and prevents auto reloading of imported css files). It works with postcss-loader 0.13.0.

```javascript
module: {
  loaders: [
    //postcss loader...
  ]
},
postcss: (webpack) => {
    console.log(webpack.addDependency); //logs undefined
    return [
      postcssImport({
        glob: true,
        addDependencyTo: webpack,
      }),
      cssnext()
    ];
  },
```
This may not be the correct way to handle things in Webpack 2 (or there exists other solutions to the problem). But it is probably a breaking change for many Webpack 1.x users.

**Comment by ai** [comment]
It doesn’t work even if you change function to object in `postcss` key?

Very strange, because we have a tests for this case.

Could you try object and show a full config.

**Comment by oyvinmar** [comment]
Here is a full example of my config: https://github.com/NDLANO/ndla-frontend/blob/master/webpack.config.base.js

I may be able to create a simpler example later.

I not quite sure I understand how a object would help. I don't know what type of object i should pass to `postcssImport({addDependencyTo: ??})` in that case.

**Comment by ai** [comment]
Object is just:

```
postcss: [
      postcssImport({
        glob: true
      }),
      cssnext()
  ]
```

`postcss-loader` don’t need a `addDependencyTo` hack anymore. But auto-`addDependencyTo` works right now only in `postcss-smart-import`. If you want this support in `postcss-import`, please support this issue: https://github.com/postcss/postcss-import/issues/233

**Comment by ai** [comment]
postcss-loader 1.1 is now released

**Comment by DavidWells** [comment]
Holy snap. This just tripped me up for a bit.

Disabling the webpackInstance made postCSS hot-module reloading not work. =(

Reverting back to a version before 1.0 fixed my problem

For those curious on hot-reloading postcss variables that are defined in the webpack config see https://github.com/serverless/site/blob/master/webpack.config.js#L32-L43
