### ISSUE TITLE
Вопрос по postcss-loader + string-replace-loader

### ISSUE THREAD

**Issue by soulhunter1987** [postcss/postcss-loader#119]
Добрый день.

У меня есть css файл, написанный с использованием css custom properties, css apply.
В нем переменные указаны так:
```css
:root {
    --some-var: ${varValue};
}
```

${varValue} я хочу передать из process.env вебпака. Я только начал им пользоваться и пока нашел единственное решение для статики - это [string-replace-loader](https://github.com/Va1/string-replace-loader). Вызываю его так через webpack.config.js

```javascript
{test: /\.css$/, loaders: ['style', 'css', 'string-replace?' + staticReplace, 'postcss']}
```
где staticReplace - настройки замены для указанных выше переменных на их значения из process.env. Настройка postcss:
```javascript
postcss: function () {
    return [postcssCustomProperties, postcssApply, autoprefixer];
}
```

На выходе я получаю код, где var(--some-var) заменен на ${varValue}, а не на ее значение, как буд-то string-replace не отрабатывает. Но на самом деле он отрабатывает, если я убираю postcss из списка лоадеров - получаю такой css в бандле:
```css
:root {
    --some-var: white;
}
``` 
то есть значения заменяются, но postcss-loader почему-то "сбрасывает" результаты его работы.

В чем может быть дело? Если есть более правильный способ внедрить переменные среды в css - буду благодарен за подсказку.

Спасибо.

**Comment by soulhunter1987** [comment]
Так, я похоже разобрался, дело было в порядке лоадеров. Они выполняются справа налево, что довольно странно, ну да ладно.

**Comment by ai** [comment]
@soulhunter1987 `string-replace` — слишком сложная способ. Возьми `postcss-simple-vars`, он принимает опцию `variables` с переменными по-умолчанию — поставь какие хочешь.

```css
:root {
    --some-var: $systemColor;
}
```

```js
postcss: function () {
  return [
    postcssSimpleVars({
      variables: {
        systemColor: process.env.COLOR
      }
    })
    postcssCustomProperties,
    postcssApply,
    autoprefixer
  ];
}
```

**Comment by soulhunter1987** [comment]
Спасибо, это действительно проще и правильнее. Правда все равно придется использовать string-replace, так как мне нужно еще внедрять переменные в html и svg, но для css попробую postcssSimpleVars.
