### ISSUE TITLE
section of docs is very difficult to understand / needs better writing

### ISSUE THREAD

**Issue by donpinkus** [postcss/postcss-loader#120]
This section of your documentation is extremely difficult to understand. I would recommend rewriting it, or having someone take a look and help rewrite it.  I would, except I don't know what you're trying to say.

```
Autoprefixer

Original:
We don’t recommend to put Autoprefixer’s browsers to  plugin options. Webpack css-loader contains cssnano. It uses Autoprefixer too.

As result you will have different browsers in Autoprefixer and CSS minification. At result, css-loader could clean some prefixes in production.

We recommend to put browsers in browserslist config in project root:

last 2 versions
ie 11

As result other tools (for example, Stylelint) will use same browsers settings.

Also, please vote for disable second Autoprefixer in css-loader.
```

**Comment by ai** [comment]
Sure. I am not native speaker, so it is hard to me to write docs.

Could you help here? What questions do you have? How I can improve it?

**Comment by michael-ciniawsky** [comment]
Where can I find information about `browserlist` config ? I can change this section in terms of language and try to better explain the issue with redundancy, different options, because of the crappy hack solution currently implemented in css-loader.

**Comment by ai** [comment]
@michael-ciniawsky it will be very helpful.

Here is a `browserslist` config docs https://github.com/ai/browserslist#config-file

**Comment by michael-ciniawsky** [comment]
@ai 👍 ok I rewrite it and make a new branch when ready, but the css-loader/postcss-loader overleaps is a big topic on it's own, either postcss-loader exports the string on it's own and css-loader keeps it's options or it removes them and folks use postcss-loader, which would in my opinion be the saner solution. `loader-utils' could provide a export method for loader authors in general  or otherwise  maybe port the logic form css-loader (stringify result.css) to postcss-loader

**Comment by donpinkus** [comment]
Basically it sounds like you're saying "Don't put something in plugin options in the webpack config. Instead do ______." 

If you want, just give a "bad" example of a config and a "good" example of a config.  People will copy paste the good one, se be sure it works or that you've given instructions on all the steps needed to get it to work :)

**Comment by ai** [comment]
I removed this section b6c38c1 because AP issue was fixed in css-loader
