### ISSUE TITLE
Webpack HMR no longer works with postcss-loader 1.0.0

### ISSUE THREAD

**Issue by troutowicz** [postcss/postcss-loader#122]
Title sums it up, reverting to postcss-loader 0.13.0 is my fix for now.

**Comment by ai** [comment]
What you mean exactly? What part of CSS didn't reloading? Variables in JS files? Entire CSS? Config changes?

**Comment by troutowicz** [comment]
I have an `index.scss` file which imports other scss files. Changes made to those imported files are not caught by Webpack's HMR. This works correctly in 0.13.0.

**Comment by ai** [comment]
Fast solution: use postcss-smart-import, instead of postcss-import

I will update docs later, about this problem with postcss-import

**Comment by troutowicz** [comment]
Thanks @ai that seems to things!

**Comment by ai** [comment]
@troutowicz here is a issue in `postcss-import`, could you ping it, so `postcss-import` will fix a problem? https://github.com/postcss/postcss-import/issues/233

**Comment by ai** [comment]
Done b6c38c1
