### ISSUE TITLE
Plugin packages documentation removed

### ISSUE THREAD

**Issue by mattsbennett** [postcss/postcss-loader#123]
Curious why this section was removed from the documentation https://github.com/postcss/postcss-loader/commit/2b3e8a4c59a41b0f3497f26931bb41f1e7fae186#diff-04c6e90faac2675aa89e2176d2eec7d8L107

Is the `?pack=name` parameter no longer supported?

**Comment by ai** [comment]
It is still supported un webpack 1.0 config. But in PostCSS common config and in webpack 2.0 you just don't need packs hack.

**Comment by ai** [comment]
So we remove this hack from docs. Webpack 2.x users should use different loaders. Webpack 1.x users should use different dir with different PostCSS config inside.

**Comment by mattsbennett** [comment]
Ah - thanks @ai ! Turns out I don't actually _need_ packs - using the [postcss-scss](https://github.com/postcss/postcss-scss) parser means I can run all my plugins at the same time. I'm pretty new to postcss so just had to do some more learning.
