### ISSUE TITLE
Webpack2/postcss-loader1.1.0 [object Object] must be a function

### ISSUE THREAD

**Issue by mscienski** [postcss/postcss-loader#127]
I'm trying to upgrade my project to Webpack2, and I receive the error in the subject for each import in my project for my production config.
`[TypeError: [object Object] must be a function, did you require() it ?]`

My imports look like
`import styles from 'App/SearchSuggestions/SuggestedTerms/SuggestedTerms.css';`

My webpack config is:

```
{
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: [{
                        loader: 'css',
                        options: {
                            modules: true,
                            importLoaders: 1,
                            sourceMap: true
                        }
                    }, {
                        loader: 'postcss-loader',
                        options: {
                            plugins: function () {
                                return [
                                    require('postcss-smart-import')(),
                                    require('postcss-url')(),
                                    require('postcss-cssnext')(),
                                    require('postcss-inline-comment')(),
                                    require('postcss-mixins')()
                                ]
                            },
                            sourceMap: 'inline'
                        }
                    }]
                })
            }
```

I have a postcss.config.js, because without I received errors that postcss config was not found. 
`PostCSS Config could not be loaded. Please check your PostCSS Config.`
It looks like

```
module.exports = {
    plugins: [
        require('postcss-smart-import')(),
        require('postcss-url')(),
        require('postcss-cssnext')(),
        require('postcss-inline-comment')(),
        require('postcss-mixins')()
    ],
    sourceMap: 'inline'
};
```

I have tried adding es-css-modules and postcss-modules in various combinations, but received the error `[TypeError: require(...) is not a function]` with all combinations.

I know I'm missing something to allow my css modules to work, I'm just not sure what.
I appreciate any guidance you can provide.

**Comment by michael-ciniawsky** [comment]
There is  bug that triggers `postcss-load-config` atm which shouldn't be the case, i'm on it you can ignore this warning, when setting options in your `webpack.config.js` instead of using `postcss.config.js`, For the TypeError this is actually a check inside of `postcss-load-config` when using an Array in `config.plugins`. You also need to use a function when using an Array i8n `postcss.config.js`. Is `sourceMap` webpack8 related or should i8t set the PostCSS sourcemaps options? In the example below it sets the postcss sourcemap options :)

```js
modules.exports = (ctx) => {
  return {
    map: ctx.env === 'development' ? 'inline' : false, 
   // ctx.env === process.env.NODE_ENV === 'development' (default)
    plugins: [
        require('postcss-smart-import')(),
        require('postcss-url')(),
        require('postcss-mixins')()
        require('postcss-cssnext')(),
        require('postcss-inline-comment')()
    ]
  } 
}
```
Off topic: `postcss-mixins` before `postcss-cssnext` is better imo

**Comment by mscienski** [comment]
Thanks for the tip about the plugin order, I've updated that.

So my main problem is still `[TypeError: [object Object] must be a function, did you require() it ?]`
when I use es6 style imports for my styles: `import styles from 'App/SearchSuggestions/SuggestedTerms/SuggestedTerms.css';`

As I mentioned, I've tried both es-css-modules and postcss-modules plugins, but neither worked for me.

**Comment by michael-ciniawsky** [comment]
The TypeError is not related to your imports :). You use `webpack.config.js` or `postcss.config.js` atm? Can you please show your current config, could be related to the current bug, when autoload is triggered althou8gh it shouldn't

**Comment by mscienski** [comment]
Here is my current production config: 
https://gist.github.com/mscienski/5815c97a3bb4018e7646030361d9e1b0

**Comment by michael-ciniawsky** [comment]
```diff
loader: 'postcss-loader',
options: {
- plugins: function () {
-   return [
+ plugins: [
     require('postcss-smart-import')(),
     require('postcss-url')(),
     require('postcss-mixins')(),
     require('postcss-cssnext')(),
     require('postcss-inline-comment')()
   ]
},
```

Try using an Array instead of a function for now, normally it's correct that way, but as mentioned before there seems to be a bug here `postcss-load-config` is triggered incorrectly when options are specified. Otherwise try/use this `postcss.config.js` meanwhile.

**postcss.config.js**

```js 
module.exports = (ctx) => {
  return {
    plugins: [
      require('postcss-smart-import')(),
      require('postcss-url')(),
      require('postcss-mixins')(),
      require('postcss-cssnext')(),
      require('postcss-inline-comment')()
   ] 
   // or
   // plugins: {
   //  'postcss-smart-import': {...options},
   //  'postcss-url': {},
   //  'postcss-mixins': {},
   //  'postcss-cssnext': {},
   //  'postcss-inline-comment`: {}
   // },
  }
}

**Comment by mscienski** [comment]
Unfortunately that doesn't seem to have worked, using either config in my webpack file, nor using postcss.config.js.

I appreciate your help to this point. I'm going to pause for now, and try again after the bug is fixed (in fact, I can help try to track it down and submit a PR).

**Comment by michael-ciniawsky** [comment]
What 'result' do you get atm? Untransformed CSS or an Error ? If neither config works there must be an additional problem somewhere...

**Comment by mscienski** [comment]
Hmm, based on the output, it appears that my CSS is not being transformed. With the cssnext plugin defined, I'd expect

```
:root {
    --os-base-url: "";

    /* IMAGE URL - this should be used for 99.9% of images that you reference */
    --os-image-url: "var(--os-base-url)/img/mxc";
```

to not be in my bundle, and instead for the custom properties to be applied inline.

**Comment by michael-ciniawsky** [comment]
Could you remove cssnext please, there is another issue with resolving it (package). [PR](https://github.com/michael-ciniawsky/postcss-load-plugins/pull/17) pending I'm waiting for response there, best with just a simple CSS File and 1, 2 postcss plugins, if that works, we at least know the reason(s) for sure, I'm on fix both of them atm, I will notify you asap when done and stop wasting your time here any longer for now :).

**Comment by mscienski** [comment]
I'm going to go ahead and close this issue, since it looks like I'm dependant on a few updates in my toolchain. I'll see what I can do to help solve the aforementioned bugs.

Thanks again.

**Comment by spectralsun** [comment]
This appears to be closed but FWIW, I got this message to go away by adding a postcss property to my webpack object that requires the postcss config file:

webpack.config.js:
```
module.exports = {
    ...
    postcss: require('./postcss.config.js'),
    ...
}
```

**Comment by Skilgarriff** [comment]
I'm having this exact same issue while copy/pasting the code from the Readme :/

**Comment by spectralsun** [comment]
@Skilgarriff Did you try adding the line to your `webpack.config.js` as I demonstrated above your comment?

**Comment by Skilgarriff** [comment]
@spectralsun I did - I've done a lot more testing and it turns out that postcss-next and precss both break and postcss configuration. 

Currently I have my setup working when I only load two plugins - postcss-simple-import, and postcss-simple-vars. If I add either precss or postcss-cssnext then all the other plugins stop working as well.

**Comment by andykenward** [comment]
Been having the same issue and found that using an object worked instead of a function with `require` for the plugins in it. It was `postcss-cssnext` that was breaking when I tried to pass browser config to it for me.

**This WORKS**
```
module.exports = {
  plugins: {
    'postcss-smart-import': {
      path: path.join(process.cwd(), constants.APP),
    },
    'postcss-simple-vars': {
      variables: () => require('../app/styles-vars'),
      unknown: (node, name, result) => node.warn(result, 'Unknown CSS variable ', name),
    },
    'postcss-focus': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', 'IE > 11'],
    },
    'postcss-reporter': {
      clearMessages: true,
    },
  },
};
```


**This did NOT work.** 
`TypeError: [object Object] must be a function, did you require() it ?`
```
module.exports = () => {
  return {
    plugins: [
    require('postcss-smart-import')({
      path: path.join(process.cwd(), constants.APP),
    }),
    require('postcss-simple-vars')({
      variables: () => require('../app/styles-vars'),
      unknown: (node, name, result) => node.warn(result, 'Unknown CSS variable ', name),
    }),
    require('postcss-cssnext')({
      browsers: ['last 2 versions', 'IE > 11'],
    }),
    require('postcss-reporter')()
  ]}
};
```

It did work when I didn't pass anything to `postcss-cssnext`.
```
module.exports = () => {
  return {
    plugins: [
    require('postcss-smart-import')({
      path: path.join(process.cwd(), constants.APP),
    }),
    require('postcss-simple-vars')({
      variables: () => require('../app/styles-vars'), // eslint-disable-line global-require
      unknown: (node, name, result) => node.warn(result, 'Unknown CSS variable ', name),
    }),
    require('postcss-cssnext')(),
    require('postcss-reporter')()
  ]}
};
```
I tried passing a function to `postcss-cssnext` that returned an object. But that didnt work for me.



**FYI** This is my webpack loader config for css files

```
'style-loader',
    {
      loader: 'css-loader',
      options: {
        modules: true,
        localIdentName: '[name]__[local]__[hash:base64:5]',
        sourceMaps: true,
        importLoaders: 1,
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        config: path.join(process.cwd(), 'internals/postcss.config.js'),
      },
    },
```

**Comment by folmert** [comment]
> found that using an object worked instead of a function with require for the plugins in it. 

Which Webpack version are you using - 1 or 2? And where have you put this config? For me similar syntax in postcsss.config.js doesn't work:

```
module.exports = {
    plugins: {
        'postcss-precss':  {},
        'postcss-cssnext': {}
    }
};
```

it returns:
```
Error: Cannot find module 'postcss-precss'
(...)
TypeError: Cannot read property 'default' of undefined
```

**Comment by andykenward** [comment]
@folmert using webpack `2.1.0-beta.25`

Have you installed postcss-precss?
`npm i -D -E postcss-precss`

**Comment by folmert** [comment]
I have Webpack 2.1.0-beta.27 and postcss-precss 1.4.0.
But the error is gone once I've installed [postcss-load-plugins](https://www.npmjs.com/package/postcss-load-plugins) (using the Array syntax with `require()`).
