### ISSUE TITLE
CSS modules not works with PostCSS (Webpack 2)

### ISSUE THREAD

**Issue by azat-io** [postcss/postcss-loader#129]
It's strange and looks like a bug :bug: 

I'm using **Webpack** v.2.1.0-beta.25

If I add CSS modules to `css-loader` after `postcss-loader` the same class names which imports from different `.jsx` files will have the same hash.

```js
use: [
    'style-loader',
    {
        loader: 'css-loader',
        options: {
            importLoaders: 1,
            modules: true,
            localIdentName: '[local]--[hash:base64:5]',
        },
    },
    'postcss-loader',
],
```

If I remove `postcss-loader` and settings for PostCSS all will works good.

This is not plugin problem.

**Look here please:** https://github.com/azat-io/webpack2-css-modules-demo

At this repo you can see three different components which contains `.title` class name. If you try to build app you can see that all of this classes will have the same hash.

After then just comment `postcss-loader` and settings for `new webpack.LoaderOptionsPlugin` and all will works good.

[Previous issue](https://github.com/webpack/css-loader/issues/364)

**Comment by ai** [comment]
@azat-io Could you try PostCSS common config?

**Comment by azat-io** [comment]
@ai Yes. All works good if I put list of plugins to `.postcssrc` file :smiley:

**Comment by ai** [comment]
Seems like we have a mystery issue in webpack 2.

I have no idea how to fix it and just will force a common config.

**Comment by azat-io** [comment]
So, I cannot put PostCSS into `webpack.config.js`?

**Comment by ai** [comment]
If you worry about too many config files, just put PostCSS plugins in `package.json`.

Or help me with debugging 😆

**Comment by ai** [comment]
Also you could try `postcss-modules`'

**Comment by amir20** [comment]
I might be late to the party but I found that `importLoaders` worked when I did it with `query` using `ExtractTextPlugin`. 

```js
loader: ExtractTextPlugin.extract({
                fallbackLoader: 'style-loader',
                loader: [
                     {
                         loader: 'css-loader',
                         query: { importLoaders: 1},
                     },
                     {
                         loader: 'postcss-loader',
                     }
                 ]
            })
```

When I changed `query` to `options` it does not work.

**Comment by wZi** [comment]
[this](https://github.com/webpack-contrib/css-loader/issues/396) work for me. hope it is helpful

**Comment by pirelenito** [comment]
This worked for me https://github.com/webpack-contrib/css-loader/issues/413#issuecomment-283944881
