### ISSUE TITLE
Plugins Function TypeError

### ISSUE THREAD

**Issue by quicksilver7** [postcss/postcss-loader#13]
I am attempting to use postcss-loader with postcss-import. These work fine until I make the webpack-config postcss attribute a function as described [here](https://github.com/postcss/postcss-loader#plugins-function).

I get the following message:
ERROR in ./~/css-loader!./~/postcss-loader!./src/styles/main.css
Module build failed: TypeError: undefined is not a function

This is the output anytime I set postcss to a function. If it is an array of plugins, it works fine.

Can anyone verify this functionality is still working with webpack?
Thanks

**Comment by ai** [comment]
Sorry, this feature is unreleased yet :)

We just need small fix: https://github.com/postcss/postcss-loader/pull/12

**Comment by quicksilver7** [comment]
Great, excited for the release.

@ai I saw a [comment](https://github.com/postcss/postcss-loader/issues/8) you made where you mentioned you aren't a webpack user anymore. Just curious, do you use an alternative and why? Are you supporting postcss-loader actively or just merging PRs?

**Comment by ai** [comment]
@quicksilver7 I use Gulp and Browserify, because webpack has ugly parameters for loaders and works very bad with CSS.

**Comment by ai** [comment]
Released in 0.5
