### ISSUE TITLE
Common config doesn't allow addDependency

### ISSUE THREAD

**Issue by matthewlehner** [postcss/postcss-loader#131]
Using the `postcss-import`, we're unable to add imported files as a dependency to Webpack.

In previous versions of this loader and webpack, we were able to add dependencies [like this](https://github.com/postcss/postcss-import#adddependencyto):

```javascript
postcss: function(webpack) {
  return [
    require('postcss-import')({
      addDependencyTo: webpack
    })
  ]
}
```

However, this configuration no longer works (which, I believe is a result of webpack, and the LoaderOptionsPlugin, based on this issue: https://github.com/webpack/webpack/issues/2684)

All I want is for webpack to be aware when I've edited a file that is hat been `@import`ed, but for the life of me, I can't figure out where/how to do this. Compilation works the first time, but subsequent saves to files that have been included with `@import` do not recompile as expected.

**Comment by ai** [comment]
Please `+1` this issue in `postcss-import`: https://github.com/postcss/postcss-import/issues/233

Or just use `postcss-smart-import` https://github.com/sebastian-software/postcss-smart-import

**Comment by wonderbeyond** [comment]
+1 also for postcss-smart-import

**Comment by ai** [comment]
`postcss-import` now supports automatically `addDependencyTo`.

@wonderbeyond `postcss-smart-import` supports it too

**Comment by wonderbeyond** [comment]
Many thanks!
