### ISSUE TITLE
Autoprefix webkit not present with webpack -p mode

### ISSUE THREAD

**Issue by JiDai** [postcss/postcss-loader#134]
Hi,

I have a simple SCSS file for testing : 
```
body{
  display:flex;
  flex:1;
}
```

I have this config in webpack : 
```
{
  test: /\.scss$/,
  loaders: ['style', 'css?importLoaders=1','postcss', 'resolve-url', 'sass?sourceMap']
},
```
Output this with running `webpack`

```
body {\n  display: -webkit-flex;\n  display: -ms-flexbox;\n  display: flex;\n  -webkit-flex: 1;\n      -ms-flex: 1;\n          flex: 1;\n}\n\n/
```

But output this with `webpack -p`

```
body{display:-ms-flexbox;display:flex;-ms-flex:1;flex:1}
```
And here is my postcss.config.js file

```
module.exports = (ctx) => {
    return {
        map: ctx.env === 'development' ? 'inline' : false,
        plugins: {
            'autoprefixer': {
                'browsers': ['last 2 versions', 'ie > 9', 'iOS 8']
            }
        }
    }
}
```

Why webkit prefixes is not present  with `-p` flag ?

webpack: 1.13.3
postcss: 5.2.5
postcss-loader: 1.1.0

**Comment by ai** [comment]
https://github.com/postcss/autoprefixer/blob/master/README.md#no-prefixes-in-production

**Comment by ai** [comment]
Please support this issue to fix this problem https://github.com/webpack/css-loader/issues/281

**Comment by JiDai** [comment]
Thanks
