### ISSUE TITLE
Loader always generate source map even if not asked to

### ISSUE THREAD

**Issue by albv** [postcss/postcss-loader#136]
I have the following loaders chain in my setup `'css!postcss!sass'` and sass-loader `sourceMap` option is set to false. So I checked, postcss-loader is called with `source='some css code', map=null` but it's emit source map anyway (almost empty).

**Comment by ai** [comment]
Hm. Should we add `sourceMap=false` or check prev maps?

I don’t like to check prev maps, because `postcss-loader` could be used wuthout `css-loader`.

**Comment by barraponto** [comment]
@ai do you know any example of a webpack-config with `postcss-loader` but no `css-loader`?

**Comment by michael-ciniawsky** [comment]
@barraponto `raw-loader` or `source-loader`

**Comment by michael-ciniawsky** [comment]
What's the status here ? Is this still relevant ? :) What/How should we fixed it ?

**Comment by michael-ciniawsky** [comment]
🙃 ?

**Comment by michael-ciniawsky** [comment]
```js
map: params.sourceMap // true => extrenal (result.map)
        ? params.sourceMap === 'inline' // => '/*# sourceMappingURL='
          ? { inline: true, annotation: false }
          : { inline: false, annotation: false }
        : false
```

Will be fixed in v2, no sourcemap is generated by default, and external `sourceMap: true` && Inline `sourceMap: 'inline'` must be set explicitly
