### ISSUE TITLE
Dynamic config doesn't apply browserslist

### ISSUE THREAD

**Issue by princed** [postcss/postcss-loader#137]
Neither file `browserslist`, nor env variable `BROWSERSLIST`.

`browsers` option in config works fine:

```
module.exports = ctx => {
  return [require('autoprefixer')({ browsers: ['last 50 versions'] })];
};
```

**Comment by princed** [comment]
Looks like it happens when dynamic returns Array as described in README.

When object is returned, everything works as expected:
```
module.exports = ctx => ({
  plugins: [
    require('autoprefixer')
  ]
});
```

**Comment by michael-ciniawsky** [comment]
@prince In your first example, there is no plugins prop :) , {plugins: {} || [] } 👍☺

**Comment by princed** [comment]
Yep, I've taken it from [README](https://github.com/postcss/postcss-loader#dynamic-config).
So it is a README issue probably.

**Comment by michael-ciniawsky** [comment]
yep, was on mobile when replying, didn't check the repo tbh :), I will fix it

**Comment by ai** [comment]
@princed thanks for report. I fixed a example: a3ea3ec

@michael-ciniawsky should we add more warnings in `postcss-load-config` about mistakes in config?

**Comment by princed** [comment]
Great, thanks!

**Comment by michael-ciniawsky** [comment]
@ai Thx for update READEM.md hadn't found the time yet 👍 

> should we add more warnings in postcss-load-config about mistakes in config?

Yes, I have something in mind already and will ook at the latest issues whats needed else, a few days please 😛
