### ISSUE TITLE
webpack 2 beta: problem configuring postcss-loader

### ISSUE THREAD

**Issue by jfmercer** [postcss/postcss-loader#141]
This issue is similar to #106: I can't compile my postcss in the current webpack 2 beta. Here are the relevant files:

* [`broken.webpack.config.js`](https://gist.github.com/jfmercer/0fb0a2b8239c22a38e5879d707995547)
* [`relevant.devDependiences.package.json`](https://gist.github.com/jfmercer/66b9268da9de7c80fe14833b8b2364f9)
* [`STDERR` output](https://gist.github.com/jfmercer/98dc3d895b7ba118a8b3041ebbb41c03)
* an abbreviated [`application.css`](https://gist.github.com/jfmercer/d46aee4206ab3322db501758fbf6860e)

At the time I'm writing, my npm packages are up-to-date. 

As you can see from `stderr`, I do not have a `postcss.config.js` currently. I created one specifically for webpack 2; however, I couldn't get it to work, and, furthermore, #106 gave me the impression that I could configure postcss from within `webpack.config.js`. I tried [two](https://gist.github.com/jfmercer/0fb0a2b8239c22a38e5879d707995547#file-broken-webpack-config-js-L40) [different](https://gist.github.com/jfmercer/0fb0a2b8239c22a38e5879d707995547#file-broken-webpack-config-js-L57) configurations of `postcss-loader`, but neither worked.

If you could help me to solve this problem, I'd be happy to write a PR with code changes or additional documentation if it would help the project. 

Thank you for your time.

**Comment by michael-ciniawsky** [comment]
@jfmercer 

**broken.webpack.config.js**
```js
{
          loader: 'postcss-loader',
          options: {
            // sourceMap: true,
            postcss: function() {
              return {
                plugins: [
                  require('postcss-import'),
                  require('css-mqpacker'),
                  require('lost'),
                  require('postcss-calc'),
                  require('postcss-clean'),
                  require('postcss-discard-comments'),
                  require('postcss-extend'),
                  require('postcss-mixins'),
                  require('postcss-modular-scale'),
                  require('postcss-nested'),
                  require('postcss-utilities')
                ]
              };
            }
          }
}
```

**webpack.config.js**

```js

{
          loader: 'postcss-loader',
          options: {
            // sourceMap: true,
            // postcss property is unnecessary here, it's for webpack =< v1 only :)
                plugins: (context) => [
                  require('postcss-import'),
                  require('css-mqpacker'),
                  require('lost'),
                  require('postcss-calc'),
                  require('postcss-clean'),
                  require('postcss-discard-comments'),
                  require('postcss-extend'),
                  require('postcss-mixins'),
                  require('postcss-modular-scale'),
                  require('postcss-nested'),
                  require('postcss-utilities')
                ]
            }
          }
}
```

**Comment by jfmercer** [comment]
@michael-ciniawsky 

Thanks for the swift reply. I changed the loader config exactly as suggested, but still get the exact same error output. I also replaced the fat arrow with a good ole' fashioned anonymous function (which should be identical to the fat arrow), but it still didn't work. 

```js
          options: {
            // sourceMap: true,
            plugins: function(ctx) {
              return [
                // requires
              ];
            }
```

Any ideas? I don't know why it still says `PostCSS Config could not be loaded. Please check your PostCSS Config.` when PostCSS is configured in the `options` object.

**Comment by michael-ciniawsky** [comment]
If is just for the warning this is buggy atm, normally if options/plugins are set in `webpack.config.js ` this warning shouldn't pop up, feel free to ignore it as long as you get transpiled CSS output with your config :). The warning is entirely related to `postcss.config.js` and has nothing to do with your inline config in  `webpack.config.js`. When you run `webpack-dev-server` does it load styles as expected ?

**Comment by jfmercer** [comment]
@michael-ciniawsky Both `webpack-dev-server` and `webpack` are building & working as expected. I still see a lot of this in the output, but the `postcss-loader` now works:

```sh
60% building modules 601/717 modules 116 active ...de_modules/object-keys/isArguments.jsPostCSS Config could not be loaded. Please check your PostCSS Config.
```

Many thanks for your help. Should I add some documentation to this project regarding the issue I encountered?

**Comment by michael-ciniawsky** [comment]
> Many thanks for your help

@jfmercer 👍  np, welcome

>  I still see a lot of this in the output, but the postcss-loader now works
> Many thanks for your help. Should I add some documentation to this project regarding the issue I encountered?

Nope thx, I'm aware of this weird bug `PostCSS Config could not be loaded. Please check your PostCSS Config.`, and try to fix it soon ( need to do a bug fix release @`postcss-load-config` first :) ) and then investigate where/why the check for `query (webpack.config.js) ? parseOptions(query) : loadConfig()` doesn't work as expected and shows the `postcss-load-config` warning unnecessarily.

**Comment by DanielYKPan** [comment]
@michael-ciniawsky
I followed you suggestion, but I got an Error like this:
**Error: options/query cannot be used with loader**

Any idea?
