### ISSUE TITLE
[Question] How to use this with ExtractTextPlugin in webpack beta 2    

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-loader#144]
Hi, I wanted to check with you guys that I am doing this correct:

https://github.com/QuantumInformation/femptoCSS/blob/master/config/webpack.common.js#L34

When doing this I am not getting the css nesting unnested, but that may not be related to this repo.

**Comment by ai** [comment]
Sorry. This questions is for `ExtractTextPlugin`. I didn’t use it. Especially because webpack 2 is in beta and have many small issues.

Open issue if they found some issue in postcss-loader.

**Comment by QuantumInformation** [comment]
roger
