### ISSUE TITLE
I'm not getting my styles loading when bundled in webpack beta 2

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-loader#146]
I've tried various things for https://quantuminformation.github.io/femptoCSS/demos/everything.html
This is how I'm using it: https://github.com/QuantumInformation/femptoCSS/blob/master/config/webpack.common.js#L31

The page loads with the bundle, incl the css, but no styles are rendered.

![image](https://cloud.githubusercontent.com/assets/216566/20859414/70e13ee0-b956-11e6-99a3-845fc9721ece.png)

**Comment by ai** [comment]
Sorry, you should ask webpack team. Webpack 2 is in beta has many issues and I even don't use it to give you good support 😕

**Comment by ai** [comment]
IMHO, your config is right

**Comment by QuantumInformation** [comment]
Ok roger!

**Comment by michael-ciniawsky** [comment]
@QuantumInformation Can you show the various '<style></style>' tags in the `index.html` please

For getting started try to comment out `ExtractTextPlugin` in plugins. There are know issues with this plugin and CSS/PostCSS atm. , but I need to look them up again first...

**Comment by QuantumInformation** [comment]
@michael-ciniawsky sorry forget it I made the royal error of forgetting to change the link to a script tag when moving from extracttextplugin
