### ISSUE TITLE
Pass dependencies from stuff like postcss-import to webpack

### ISSUE THREAD

**Issue by gnarf** [postcss/postcss-loader#148]
Using postcss-import and this loader, whenever something is @import'ed, making changes to the @import'ed file doesn't recompile the files depending on it.

**Comment by ai** [comment]
What `postcss-import` do you use? The latest version supports `dependency` message and `postcss-loader` use this message for behavior that you want:

https://github.com/postcss/postcss-loader/blob/master/index.js#L125

**Comment by gnarf** [comment]
:/ sorry I coulda sworn I had updated to latest of both of these things before filing...
