### ISSUE TITLE
Consider custom config file path in options

### ISSUE THREAD

**Issue by jrmlstfMt** [postcss/postcss-loader#149]
You added in 1.2.0 a way to define a custom config file path using the loader query.

But if you have two different loaders using postcss, i'll have to define config query param for each.

Can you consider defining a global config custom file path from loader.options.postcss ?

**Comment by ai** [comment]
Custom config path is a private API for rare cases.

You should put PostCSS config somewhere in style files path. Babel has no custom path at all.

Custom config path is bad practice because of:

1. Other tools (IDE, linters, etc) will not understand custom config path automatically.
2. Other developers could miss config too.

In this case, I am not big fan of improving this feature.

What your use case why you need custom config path?

**Comment by jrmlstfMt** [comment]
I agree with you, especially point 1.

But I have a lot of files : webpack (x4), eslint, postcss, styelint, karma, protractor, etc. So i'm using a config dir to organize it a bit.

ESLint is implementing this feature https://github.com/MoOx/eslint-loader#options

**Comment by ai** [comment]
@jrmlstfMt why not put config files to root? Do you have ration reason for separated dir? :)

**Comment by jrmlstfMt** [comment]
No more rational than putting files in a directory to keep them organized. Which is why directories exists I guess ;-)

**Comment by ai** [comment]
BTW, you could store your PostCSS config in `package.json` to reduce config files in root.

**Comment by jrmlstfMt** [comment]
Yep package.json is a solution. But less powerful than a js function.

Having a .config/* dir in project root is a good convention I agree.

Maybe this kind of convention should be supported by the guys behind
https://github.com/davidtheclark/cosmiconfig ?

**Comment by CrashyBang** [comment]
Hey @ai what does the `package.json` config look like?

**Comment by ai** [comment]
@jrmlstfMt unfortunately, Babel developers did not support `.config/` idea (I asked them in prev. week)

**Comment by ai** [comment]
@CrashyBang https://github.com/michael-ciniawsky/postcss-load-config#packagejson

**Comment by CrashyBang** [comment]
hey @ai chhers
