### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by jantimon** [postcss/postcss-loader#15]
Is it possible to consume a sourcemap like the [css-loader](https://github.com/webpack/css-loader/blob/master/lib/loader.js) does?

Without postcss-loader I have to following:
```
{ test: /\.less$/, loader: ExtractTextPlugin.extract('style-loader', 'css?sourceMap!less?sourceMap) },
```

Now when I add the postcss-loader it looks like:
```
{ test: /\.less$/, loader: ExtractTextPlugin.extract('style-loader', 'css?sourceMap!postcss?sourceMap!less?sourceMap) },
```

Now the source map is broken and doesn't follow `@import` rules anymore.

**Comment by ai** [comment]
There is no need to use `?sourceMap`, source mas should load automatically.

**Comment by jantimon** [comment]
Thanks I tried that however the bug is still there.

a.less
```
@import 'b.less';
```
b.less
```
body {background: red}
```

When inspecting the body element I get different results:

Result without `postcss-loader`: `b.less`  
Result with `postcss-loader`: `a.less` (which is obviously wrong)

**Comment by ai** [comment]
@sokra maybe we can move postcss-loader to webpack support? I didn’t use it and it is very difficult to fix complicated issues :(.

**Comment by ai** [comment]
@jantimon can you create some small playground with this issue?

**Comment by sokra** [comment]
Maybe @markdalgleish like to maintain it...

**Comment by jantimon** [comment]
@ai here you go: http://we.tl/niZkeyeQrl
```
npm i
npm run dev
```

**Comment by ai** [comment]
@markdalgleish =^_^=

**Comment by ai** [comment]
I test your case, PostCSS correctly receives previous map, so there is no need for `?sourceMap` parameter.

**Comment by ai** [comment]
Hm. Seems like as strange case of Less/webpack/PostCSS conflict. Right not it will not be a important issue :).

**Comment by jantimon** [comment]
So postcss won't work with less?

**Comment by jantimon** [comment]
Just compared the two source maps post css receives:

Less

```json
{
  "sources" : [
    "b.less"
  ],
  "mappings" : "AAAA;EACE,aAAA",
  "sourcesContent" : [
    "h2 {\n  color: orange;\n}"
  ],
  "names" : [

  ],
  "version" : 3
}
```

Scss

```json
{
  "sources" : [
    "example\/with-postcss\/a.scss",
    "example\/with-postcss\/b.scss"
  ],
  "sourcesContent" : [

  ],
  "mappings" : "ACAA,EAAE,CAAC;EACD,KAAK,EAAE,MAAO,GADZ",
  "names" : [

  ],
  "file" : "example\/with-postcss\/a.scss",
  "version" : 3
}
```

Seems like postcss needs more information - is this a post css or less bug?

**Comment by ai** [comment]
If Less send a source with only one file it is definitely Less bug.

**Comment by jantimon** [comment]
But the css-loader can handle it correctly

**Comment by jantimon** [comment]
Just took a look at what post-css does with the less map.

```
{
  "sources" : [
    "b.less"
  ],
  "mappings" : "AAAA;EACE,aAAA",
  "sourcesContent" : [
    "h2 {\n  color: orange;\n}"
  ],
  "names" : [],
  "version" : 3
}
```

becomes

```
 { version: 3,
  sources: [ 'a.less' ],
  names: [],
  mappings: 'AAAA;EACE,cAAc;CACf',
  file: 'a.less',
  sourcesContent: [ 'h2 {\n  color: orange;\n}\n' ] 
}
```

As you can see postcss changes the sources from 'b.less' to 'a.less'

**Comment by ai** [comment]
What file is main and what will be imported?

**Comment by ai** [comment]
BTW, very strange, that Less file doesn't have `file` field.

**Comment by jantimon** [comment]
`a.less` is the file which imports `b.less`.

**Comment by ai** [comment]
Can you add a file field to Less map and see will it fix a problem?

**Comment by jantimon** [comment]
Maybe I mixed it up with other debug tests but it seems like the following change would fix the issue:
```
if (typeof map === 'string') {
  map = JSON.parse(map);
}
```

**Comment by jantimon** [comment]
Hm actually that really seems to fix the issue - do you want me to file a merge request?

**Comment by ai** [comment]
@jantimon awesome! Let’s my find out why string maps doesn’t work in PostCSS core. Maybe PR to core is a better solution.

**Comment by jantimon** [comment]
Only a guess but it's probably a loader bug:

from https://github.com/postcss/postcss-loader/blob/master/index.js#L17
```
if ( map && map.mappings ) opts.map.prev = map;
````

Will be false if map is a string.

**Comment by ai** [comment]
Oh, exactly

**Comment by ai** [comment]
Fix released in 0.5.1.

Thanks for doing all job by this task :D.

**Comment by jantimon** [comment]
Cool thanks :)

**Comment by markdalgleish** [comment]
@ai Did we still want to move this project to the webpack org?

**Comment by ai** [comment]
@markdalgleish yeap :) I am bad maintainer for webpack projects =^_^=
