### ISSUE TITLE
Is there some example to show use postcss-loader without css-loader?

### ISSUE THREAD

**Issue by hh9527** [postcss/postcss-loader#150]
It seemed that we can use css-modules & other optimization plugin of postcss to process name mangle and optimization, and thus make it unnecessary to use css-loader (which is locked in css-nano@3) any more.

But there is no configuration example for now.

**Comment by michael-ciniawsky** [comment]
> It seemed that we can use css-modules & other optimization plugin of postcss to process name mangle and optimization

Can you explain that a bit further please ? 😛 

>  and thus make it unnecessary to use css-loader...

Nope, css-loader adds the module syntax, while postcss-loader 'just' transforms the CSS `{String}` and returns it. You can use/try something like `raw-loader || source-loader`, but only postcss-loader won't work.

**Comment by hh9527** [comment]
@michael-ciniawsky 

`css-loader` provide the following features:
- module syntax & ident name mapping
- optimization of css (by `css-nano@3`)

and the compile process follows this:

.(less|styl) files
  -> (less|styl)-loader
  -> postcss-loader (autoprefixer)
  -> css-loader
  -> style-loader

these features can be replaced by relative postcss plugins:
- module syntax & ident name mapping: `postcss-modules`
- optimization: css-nano@latest

the the process become:

.(less|styl) files
  -> (less|styl)-loader
  -> postcss-loader (autoprefixer + postcss-modules + css-nano)
  -> style-loader

**Comment by ai** [comment]
Yeap, you can replace it. You can even replace styl-loader by SugarSS syntax in `postcss-loader`.

But, because many developers uses different ways, I can’t show single example. For instance, some of React developers doesn’t like a separated JSON from `postcss-modules`.

**Comment by ai** [comment]
Anyway PR is welcome, maybe you can write example better

**Comment by barraponto** [comment]
@michael-ciniawsky css-loader also parses imports (postcss-import). I'm trying to document a no-css-loader solution, but I didn't manage to get it working yet. do you have a working example?
