### ISSUE TITLE
Document `pack` option

### ISSUE THREAD

**Issue by jorrit** [postcss/postcss-loader#152]
I am using the kriasoft/react-starter-kit React boilerplate which uses postcss-loader. It contains `postcss-loader?pack=default` in the webpack config. I was surprised that the README of postcss-loader doesn't contain an explanation of the `pack` option. I now understand that it is used to select a postcss configuration, but perhaps some documentation could be added to the README file? Thanks!

**Comment by ai** [comment]
In 1.0 we promote only PostCSS common config. You don't need a pack option for it. So this is a reason, why we don't mentioned it in docs. 

You could create a issue in boilerplate to move to latest postcss-loader API.

**Comment by jorrit** [comment]
Thanks for explaining!

**Comment by jorrit** [comment]
I still have a question about this: the boiler plate uses version `^1.1.1` and it seems the `pack` option is still present and used in the `postcss-loader` code and tests. Also, changing the option does have an effect. Also, I can't find any documentation about 'PostCSS common config'.

**Comment by ai** [comment]
Instead of force users to change API I prefer lazy API updates. I removed webpack config docs, so new users will start to use new API. But we still support old API.

Here is PostCSS common config docs: https://github.com/postcss/postcss-loader#usage
