### ISSUE TITLE
Who care npm version?

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-loader#153]
```
 "engines": {
    "node": ">=0.12",
    "npm": ">=3"
  },
```

**Comment by ai** [comment]
Good question. Could you find a author of this change by `git blame` and ask him why he add it. If he will not give a good reason, let’s remove this line.

**Comment by TrySound** [comment]
Hm.. I see https://github.com/postcss/postcss-loader/pull/140 But warnings are not affects build process. So this change doesn't make sense.

**Comment by ai** [comment]
Sure. But let's wait few days for origin author reasons. Maybe we missed something.

**Comment by michael-ciniawsky** [comment]
@TrySound setting npm version was my fault, it's unnecessary crap, the PR author wanted to get rid of warnings triggert because of npm version set in `postcss-load-config` package.json. Next postcssrc minor will fix that and I remove it in postcss-loader when bumping postcssrc version

**Comment by ai** [comment]
@TrySound send PR with removing it.

**Comment by michael-ciniawsky** [comment]
@TrySound fixed in #161
