### ISSUE TITLE
Why postcss stops working when used inside webpack's text extract plugin?

### ISSUE THREAD

**Issue by felixsanz** [postcss/postcss-loader#156]
Using webpack 2.

"extract-text-webpack-plugin": "2.0.0-beta.4",
"webpack": "2.2.0-rc.2",
"postcss-loader": "^1.1.1",

This loader works fine:

```javascript
{
  loader: 'postcss-loader',
  options: {
    plugins: () => [
      atImport({
        onImport() {
          console.log('--------------------------------------------------------')
        },
      }),
    ],
  },
},
```

And also having the plugins inside `postcss.config.js` works too.

But when you wrap `postcss-loader` inside `ExtractTextWebpackPlugin.extract()` it stops working.

I only get a bunch of:

```
Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../../styles/config.css";
```

And I never see that console.log again. I'm 99% sure that the postcss config is not even read anymore.

Anyone had this troubles before?

**Comment by ai** [comment]
@felixsanz please create a issue in extract-text-plugin and mention me there. Webpack 2 is still in development, seems like they have a issue.
