### ISSUE TITLE
DeprecationWarning from loaderUtils

### ISSUE THREAD

**Issue by kidney** [postcss/postcss-loader#176]
When I run build, I get the feedback information from console：

```shell
(node:1670) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

postcss-loader@1.2.2

**Comment by michael-ciniawsky** [comment]
@kidney Yep `loader-utils` >= v1.0.0 had a API breaking change API `getOptions` I'm on it :), feel free to ignore this warning meanwhile

**Comment by NekR** [comment]
It's still there, right?

**Comment by michael-ciniawsky** [comment]
@NekR Which version of `postcss-loader` ?

**Comment by NekR** [comment]
`"postcss-loader": "^2.0.6",`

I'm not 100% sure if it's `postcss-loader`, but I got it when I started updating postcss related things, including the loader.

**Comment by NekR** [comment]
Nevermind, I found the problematic one, it was `css-loader`. Thanks!

**Comment by mcohoon** [comment]
For those following this chain here is the [issue in css-loader](https://github.com/webpack-contrib/css-loader/issues/707).
