### ISSUE TITLE
Emit Error On Warning

### ISSUE THREAD

**Issue by kenisteward** [postcss/postcss-loader#181]
Are there any prospects to change this to upgrade warnings to errors and then emit them to webpack for a failure?  https://www.npmjs.com/package/stylelint-webpack-plugin  Does this but I was hoping it was going to come here soon

**Comment by michael-ciniawsky** [comment]
@kenisteward Just to clearify you mean warnings generated by `stylelint` in particular here ?

**Comment by kenisteward** [comment]
For my use case stylelint but for a more generic one any warnings or errors
generated through a postcss loader.  That way if someone is using any
assortment of postcss plugins the loader will have the option to upgrade
warning to error and emit them as it already does as errors .

**Comment by michael-ciniawsky** [comment]
@kenisteward Can you point to where in the source of stylint-webpack-plugin it throws the warnings as errors?

I basically agree that throwing an error might sometimes be the better solution, especially to 'enforce' a certain code style, but if stylelint pushes warnings/errors to `result.warnings` it will be difficult to handle, bc that's normally it's propose and other plugins expecting to display a warning via `result.warnings` will break.

cc @ai

**Comment by kenisteward** [comment]
@michael-ciniawsky  in it's options api for webpack you can pass these
`
emitErrors: Display Stylelint errors as actual errors, rather than just warnings. Default: true
failOnError: Have Webpack's build process die on error. Default: false
`
Together they allow you to specifically force a codestyle

in their actual code this file has the error handling.
https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js

As a change to this loader I think all that would need to be done is a refactoring of when to use error or not.  Just wanted to know if it were in the pipeline.

**Comment by kenisteward** [comment]
@michael-ciniawsky also someone has made 

https://github.com/JasonAMartin/style-warning-breaker/blob/master/index.js
which basically gobbles up the lint stuff from it.  

Like I said before this works for my use case but I was thinking more generically.  Just seems odd to postcss but then not be able to force rules with it.

**Comment by ai** [comment]
This loader works with many plugins. For example, Autoprefixer has warnings too. If loader will always throw a error on warning, it will break many systems.

All PostCSS plugins have access to `result.messages`. If you need to different behaviour for warnings, just add plugin. Like [`postcss-reporter`](https://github.com/postcss/postcss-reporter).
