### ISSUE TITLE
With precss({..}) option, css can't get loaded

### ISSUE THREAD

**Issue by highdali** [postcss/postcss-loader#184]
LoaderOptionsPlugin
```js
postcss: [
  require('precss')({...anything...}),
  ...
]
```

```
ERROR in ./~/css-loader?importLoaders=1!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/stylesheets/main.scss
Module build failed: Error: ENOENT: no such file or directory, open ...
```

I don't know why error occurs.
But, If i delete a `require('precss')` sentence, bootstrap can get loaded.

**Comment by ai** [comment]
Do you have `@import` in you input fixes? Maybe input files affect to `precss`?

**Comment by highdali** [comment]
yes, I import bootstrap or semantic ui. and handle woff2, png... etc.
I think this problem be caused  by url-loader and file-loader...

**Comment by ai** [comment]
Show full config. I think you need @michael-ciniawsky help (it is webpack UX overall problem, not postcss-loader only).

**Comment by highdali** [comment]
**works nicely config**

main.scss

```scss
@import "~semantic-ui-css/semantic.min.css'
```

webpack.config.js
```js
var webpack = require('webpack')

module.exports = {
  entry: ['babel-polyfill', `${__dirname}/src/index.jsx`, `${__dirname}/src/stylesheets/main.scss`],
  output: {
    path: `${__dirname}/public`,
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        use: ['flow-bin-loader', 'eslint-loader'],
        exclude: /node_modules/
      },
      {
        use: 'babel-loader',
        test: /\.jsx?$/,
        exclude: /node_modules/
      },
      {
        use: [
          'style-loader',
          'css-loader?importLoaders=1',
          'postcss-loader',
          'sass-loader'
        ],
        test: /\.scss$/
      },
      { test: /\.(woff2?|svg|jpe?g|png|gif|ico|eot|ttf)$/, loader: 'url-loader?limit=10000' },
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.LoaderOptionsPlugin({
      options: {
        postcss: [
          require('autoprefixer')
        ]
      }
    })
  ],
  devServer: {
    ...
  }
}
```

But, If i add `precss` like below,
```js
var webpack = require('webpack')

module.exports = {
  entry: ['babel-polyfill', `${__dirname}/src/index.jsx`, `${__dirname}/src/stylesheets/main.scss`],
  output: {
    path: `${__dirname}/public`,
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.jsx?$/,
        use: ['flow-bin-loader', 'eslint-loader'],
        exclude: /node_modules/
      },
      {
        use: 'babel-loader',
        test: /\.jsx?$/,
        exclude: /node_modules/
      },
      {
        use: [
          'style-loader',
          'css-loader?importLoaders=1',
          'postcss-loader',
          'sass-loader'
        ],
        test: /\.scss$/
      },
      { test: /\.(woff2?|svg|jpe?g|png|gif|ico|eot|ttf)$/, loader: 'url-loader?limit=10000' },
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.LoaderOptionsPlugin({
      options: {
        postcss: [
          require('precss')({...anything options...}) /* HERE. */
          require('autoprefixer')
        ]
      }
    })
  ],
  devServer: {
    ...
  }
}
```

error shows

```
ERROR in ./~/css-loader?importLoaders=1!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/stylesheets/main.scss
Module build failed: Error: ENOENT: no such file or directory, open '/Users/highdali/tmp/book-review-moa/src/stylesheets/~semantic-ui-css/semantic.min.css'
 @ ./src/stylesheets/main.scss 4:14-181 13:2-17:4 14:20-187
 @ multi (webpack)-dev-server/client?http://localhost:4000 webpack/hot/dev-server babel-polyfill ./src/index.jsx ./src/stylesheets/main.scss
```

**Comment by highdali** [comment]
Problem is my config? or postcss-loader? sass-loader ? precss ? i don't know why this error occurs sorry

**Comment by michael-ciniawsky** [comment]
@highdali :D Where should I start here... 😛  

```js
entry: [ ..., `${__dirname}/src/stylesheets/main.scss`]
```
You can't use a `.scss` file as an entry point :). Instead require it in your components e.g in 
`index.jsx`

```
|–components
|   |– MyComponent
|   |    | – index.scss
|   |    | – index.jsx
|
|– App.scss
|– App.jsx
|–webpack.config.js
```

**MyComponent/index.jsx**
```js
import React, { Component } from 'react'

import $ from './index.scss' // <=

class MyComponent extends Component {
   render () {...}
}

export default MyComponent
``` 

**App.jsx**
```js
import React, { Component } from 'react'
import ReactDOM from 'react-dom'

import $ from './App.scss'

import MyComponent from './components/MyComponent'

class App extends Component {
   render () {
      return (
         <MyComponent />
      )
   }
}


ReactDOM.render(<App />, document.getElementById('app'))
```

**webpack.config.js**
```js
entry: './App.jsx'
```

> Module build failed: Error: ENOENT: no such file or directory, open '/Users/highdali/tmp/book-review-moa/src/stylesheets/~semantic-ui-css/semantic.min.css'


Thats `sass-loader` because of the `~` and no `includePaths` option is set see below

**webpack.config.js**
```diff
{
   test: /\.scss$/
   use: [
     'style-loader',
+   { loader: 'css-loader, options: { importLoaders: 1 } },
+   { loader: 'postcss-loader', options: { plugins: [ require('autoprefixer')({...options}) ] },
+   { loader: 'sass-loader', options: { includePaths: 'path/to/@imports/' } }
  ],
}
```

You won't need PreCSS if you use SASS (`sass-loader`)

Please remove `LoaderOptionsPlugin` you don't need it anymore since postcss-loader fully supports webpack 2 options

**webpack.config.js**
```diff
 plugins: [
   new webpack.HotModuleReplacementPlugin(),
- new webpack.LoaderOptionsPlugin({
-    options: {
-      postcss: [
-          require('precss')({...anything options...}) /* HERE. */
-          require('autoprefixer')
-        ]
-      }
-    })
  ]
```

**Comment by highdali** [comment]
Sass-loader provides custom importer that import modules from `/node_modules/`.
documentation [here](https://github.com/webpack-contrib/sass-loader#imports)
So I don't need to specify `includePaths` option, right?

**Comment by michael-ciniawsky** [comment]
> So I don't need to specify includePaths option, right?

@highdali I'm not 💯  sure about that tbh 😛 , does it work now/work without `@import ~/semantic-ui-css/semantic.min,css` at least?

**Comment by highdali** [comment]
Sorry, I am beginner for web development.
I just put `stylesheets/main.scss` on bundle `entry`. so, stylesheets will be in `bundle.js` finally.
According to [postcss doc](https://github.com/webpack-contrib/sass-loader#imports), i can import the css/sass module. Here, `~` does not mean **home directory**. It tells webpack resolve engine should find the module from 'node_modules'.

I tried your solution, but i didn't know what should put in `includePaths: 'path/to/@imports/'`
thanks.

**Comment by michael-ciniawsky** [comment]
> does not mean home directory. It tells webpack resolve engine should find the module from 'node_modules'

Yep exactly, but in the Error above it didn't work and reied to search in your project for e.g `semantic-ui-css/semantic.min.css`and the error was simply that it doesn't exists there :)

> I tried your solution, but i didn't know what should put in includePaths: 'path/to/@imports/'
thanks.

```
| – src
|    | – components (@imports)
|    | – index.scss
|
|– webpack.config.js
|– package.json
```

**webpack.config.js**
```js
{
   test: /\.scss$/
   use: [
     'style-loader',
     { loader: 'css-loader', options: { importLoaders: 1 } }
     { loader: 'sass-loader', options: { inlcudePaths: path.resolve('src/components') }
  ]
}
```


If you're a beginner, its good to learn webpack inside out but also very hard :), If you want just to get something running maybe try [create-react-app](https://github.com/facebookincubator/create-react-app) whch handles all the webpack things for you and you can focus on your actual app. On the other hand if ypu want to play around [webpack Guides](https://webpack.js.org/guides) can help you a ton in getting up and running with webpack 😛.

**Comment by highdali** [comment]
thanks, you're genius.
