### ISSUE TITLE
Webpack 2 not working with precss plugin for postcss-loader

### ISSUE THREAD

**Issue by ximet** [postcss/postcss-loader#185]
I added precss option to postcss-loader, but him not working and not transpile correct nested-selector.
`const precss = require('precss');`

 `{
       test: /\.scss$/,
           use: [
               {
                        loader: 'style-loader',
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            autoprefixer: false,
                        },
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            postcss: [
                                precss(),
                                autoprefixer(browserslist),
                            ],
                        },
                    }
                ]
            }`

How resolve this problem?

**Comment by ai** [comment]
1. Show full config.
2. Show input, output and expected output.
