### ISSUE TITLE
Cannot not get options from webpack config

### ISSUE THREAD

**Issue by yangg** [postcss/postcss-loader#188]
webpack 2
For some reason, I canno't use postcss.config.js, so I put config in loader options
```js
{
  loader: 'postcss-loader',
  options: {
    plugins: [
      require('autoprefixer')({
        browsers: [ 'iOS >= 5.1' ]
      }),
      require('postcss-pxtorem')({
        rootValue: 46.875,
        propWhiteList: []
      })
    ]
  }
}
```
But the following error occus:
```
 ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader?{"plugins":[null,null]}!./~/sass-loader?{"sourceMap":true}!./app/components/Coupons/couponbag/_couponbag.scss
    Module build failed: TypeError: Cannot read property 'postcss' of null
```

**Comment by michael-ciniawsky** [comment]
webpack version please 😛 if you're webpack <= 2.2.1. That's a known bug with 'Complex Options' in loader options like using `{Function}/require()`. 2.2.1 fixed this and if you can't upgrade (highly recommended) then try this

**webpack.config.js**
```js
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss' // <= 
    plugins: [
      require('autoprefixer')({
        browsers: [ 'iOS >= 5.1' ]
      }),
      require('postcss-pxtorem')({
        rootValue: 46.875,
        propWhiteList: []
      })
    ]
  }
}
```

Also a fresh `rm -rf node_modules && npm i` can do wonders 😄

**Comment by michael-ciniawsky** [comment]
If you still have any regressions feel free to reopen 😛

**Comment by yangg** [comment]
Update webpack from 2.2.0  to 2.3 fixed this problem.
Thanks for your help.😄
