### ISSUE TITLE
postcss-loader ignores options if there is configuration in postcss.config.js or package.json

### ISSUE THREAD

**Issue by barraponto** [postcss/postcss-loader#189]
is this expected?
can i work around it (and merge the options)?

**Comment by ai** [comment]
Nope. Could you remove config? Maybe options doesn’t work on your webpack. Show your configs.

**Comment by barraponto** [comment]
Sorry, my bad. I had set `{map: true}` in the options, but I forgot to set the proper `devtool` in webpack.
Thanks for the attention :)
