### ISSUE TITLE
feat: options.plugins support returning a promise

### ISSUE THREAD

**Issue by jerexyz** [postcss/postcss-loader#190]
options:plugins now support function   but not support return promise.

**Comment by ai** [comment]
What is your use case for it?

**Comment by jerexyz** [comment]
I am developing a tool like  create react app，Used postcss 。
I can read the user's configuration if it does not exist I can give a default configuration。
if support return promise，I can doing is dynamic。

**Comment by ai** [comment]
OK, I will try to fix it after React London. If you want if sooner, feel free to send PR.

**Comment by michael-ciniawsky** [comment]
@jerexyz Example for that (in code) please 😛

**Comment by jerexyz** [comment]
@michael-ciniawsky    https://github.com/jerexyz/postcss-loader-demo
thanks

**Comment by michael-ciniawsky** [comment]
@jerexyz I see, so basically you want to change the config resolving order ? 😛 

**Current**
`webpack.config.js`> `postcss.config.js` > `Error`

**Proposed**
`postcss.config.js`> `webpack.config.js` > `Error`

The logic for config loading starts [here](https://github.com/postcss/postcss-loader/blob/master/index.js#L65), but I must try and think of possibilities to do so first, please be patient and if you have a **non** breaking solution please share :)

**Comment by jerexyz** [comment]
@michael-ciniawsky    yes,this is what i wanted.a non breaking solution  is   `options.plugins` function  support `Promise`, so can change  the config dynamic.

**Comment by michael-ciniawsky** [comment]
@jerexyz But not for all current users of `postcss-loader` :), especially existing *webpack.config.js/postcss.config.js* combos expecting `webpack.config.js > postcss.config.js` will break with this change 😛 . Maybe we can introduce this in `v2.0.0`, what happens will the loader logic look like if someone doesn't use a Promise in `options.plugins` ? How to determine config loading ?

**Comment by jerexyz** [comment]
`webpack.config.js > postcss.config.js` can be keeped. For now, options.plugins support `{Function}`   so  can write some logic. but can't do everything sync.

**Comment by michael-ciniawsky** [comment]
Send PR please 😛 it seems I'm not 💯 getting it

**Comment by michael-ciniawsky** [comment]
@jerexyz Did you find a solution for this ? I will try to help wherever I can, but I don't think switching the current config loading behaviour is applicable in the proposed way.
