### ISSUE TITLE
refactor: don't use `postcss` when `plugins` option is empty

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-loader#196]
If option `plugins` is empty postcss is still applied, but we can avoid run `postcss`.

**Comment by michael-ciniawsky** [comment]
We could add a check [here](https://github.com/postcss/postcss-loader/blob/master/index.js#L80) and early return the css with a warning to maybe  remove `postcss-loader` from `webpack.config.js`. Good catch 👍

**Comment by michael-ciniawsky** [comment]
We need to take care of options too, in case `postcss-loader` is used for e.g SugarSS

**Comment by ai** [comment]
Do we need some loader changes?

**Comment by michael-ciniawsky** [comment]
Maybe around [here](https://github.com/postcss/postcss-loader/blob/master/index.js#L80), but if `postcss-loader` should take care of user/usage error(s) is another question 😛

**Comment by ai** [comment]
I still don’t understand this issue and what we should change :)

**Comment by michael-ciniawsky** [comment]
if `const plugin = [], const options= {}` skip parsing + display warning and early return, but if that is the case `postcss-loader` shouldn't be setup from the beginning and it can only happen if `postcss.config.js` is empty, which also errors in `postcss-load-config`. hmm... so while thinking about it I would say nothing :D, already fine, maybe test again if all cases are covered

**Comment by ai** [comment]
Why user would have empty plugins and options?

**Comment by michael-ciniawsky** [comment]
¯\_(ツ)_/¯
 
That change would be more of 'save me from my own stupidness' kind of thing I guess and ensure it doesn't hit performance while doing so

**Comment by ai** [comment]
If someone will have good use case for it, we will reopen issue.

Right now I think, error message for wrong configuration is more important (it is easy to miss warning, instead of error).

**Comment by evilebottnawi** [comment]
@ai i use difference `plugins` for difference files, examples `foo.cssnext.css` for files contain cssnext and `foo.css` for simple css. why? some modules from npm contain only css and i speedup my build.

**Comment by ai** [comment]
@evilebottnawi can you show your config?

**Comment by evilebottnawi** [comment]
@ai 
```js
const filterPostcssPlugins = (plugins) => plugins.filter(
    (postcssPlugin) => !(postcssPlugin.postcssPlugin === 'cssnano' || postcssPlugin.postcssPlugin === 'css-mqpacker')
);
const cssPostcssPlugins = filterPostcssPlugins(config.get('compiler.loaders.postcss').css); // Also i have this for cssnext and scss, for some situation i have zero plugins, but this increases the compilation time, because postcss spends time on parsing :(
```

Loader рas approximately this configuration:
```js
 {
            loader: 'postcss',
            options: {
                plugins: () => cssPostcssPlugins // Or scssPostcssPlugins and etc
            }
        }
```

**Comment by ai** [comment]
Hm, maybe we should do not show warning when user pass `[]` and still show it when user didn’t pass anything (here is a problem, that we try to fix with this warning).

I will think for few days and then decide.

**Comment by evilebottnawi** [comment]
@ai thanks for helping :1st_place_medal:
