### ISSUE TITLE
[Question] sass-loader and sourcemap

### ISSUE THREAD

**Issue by Kikobeats** [postcss/postcss-loader#199]
Hello, I want to know if this configuration using `sass-loader` and `postcss-loader` is correct for generate a production sourcemap:

```js
{
  test: /\.(css|scss)$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [{
      loader: 'css-loader',
      options: {
        minimize: true,
        importLoaders: 2
      }
    }, {
      loader: 'postcss-loader',
      options: {
        parser: require('postcss-scss'),
        // sourcemap: 'inline'
      }
    }, {
      loader: 'sass-loader'
      options: {
        sourcemap: true
      }
    }]
  })
}
```

Note how I commented `sourcemap: 'inline'` because I undestand `sass-loader` is the last loader in the pipeline and is enough with generate the sourcemap in these step? or is necessary generate twice?

Another question related: `inline` is the unique value available for sourcemap? I didn't found docs.

After any useful reply here I can complete the main documentation for add this case 😄

**Comment by michael-ciniawsky** [comment]
@Kikobeats Try this config 

**webpack.config.js**
```js
{
  test: /\.(css|scss)$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [{
      loader: 'css-loader',
      options: {
        minimize: true,
        sourceMap: true
        importLoaders: 2
      }
    }, {
      loader: 'postcss-loader',
      options: {
        parser: require('postcss-scss'), // Why ?
        sourceMap: true
      }
    }, {
      loader: 'sass-loader'
      options: {
        sourceMap: true
      }
    }]
  })
}
```

> Note how I commented sourcemap: 'inline' because I undestand sass-loader is the last loader in the pipeline and is enough with generate the sourcemap in these step? or is necessary generate twice?

`sass-loader` is the **first** loader that receives your `.css/.scss` files. (`reduceRight`)


> Another question related: inline is the unique value available for sourcemap? I didn't found docs.

Yes, atm this is `postcss-loader` specific, @webpack-contrib we are currently discussing  about supporting that in general (`css-loader/style-loader`) if needed or otherwise removed it enterily to avoid confusion 😛 . It was added in `postcss-loader` via a PR from an angular folk a while ago, but doesn't really work with other loaders tbh. Below is the loader skeleton explaining the data flow applying to all loaders in the CSS Pipeline + a Sourcemap Blueprint compatible with webpack

**loader.js**
```js
module.exports = function (source = css, map) {
    transform(source)
      .then((result) => {
         source = result.css
         options.sourceMap ? map = result.map : map

         return this.callback(/* Error */, source, map)
      })
}
``` 

**map.json**
```
{
  filename: ''  // will be ignored
  sourceRoot: "",  // needs to be empty
  sourceContent: `${ source.scss }` 
  sources: [ path.resolve('path/to/css'), ...],  // absolute path, each loader needs to update this
  // only the content from the entry, intermediate loaders shouldn't touch this at all 
  sourceContent: `${ source.scss }`,
  sources: [ path.resolve('path/to/css'), ...],  // absolute path, each loader needs to update this
  mappings: '' // every loader needs to update these after tranformation
}
```

**Comment by Kikobeats** [comment]
Thanks for reply!

Very interesting know about `reduceRight`. Have a lot of sense, Can you say where can I read more about webpack internals? Always I had the doubt if the order of the plugin list is important.

You said inline the unique value available (and I saw that [here] (https://github.com/postcss/postcss-loader/blob/833df03f8f6bd0ab24f2bff9bf8d15138bd39cda/index.js#L85)) but your code suggested have a `true `Instead 😛.

But yes, ideally, align with value with the rest of loaders could be great.

**Comment by michael-ciniawsky** [comment]
Ooops... 😛 yep sry `postcss-loader` sourcemaps are always generated atm, but this will change in the upcoming **v2.0.0** release for perf reasons

[Developer Guides](https://webpack.js.org/development/)

[Loader Runner](https://github.com/webpack/loader-runner)
[Loader API](https://webpack.js.org/api/loaders/)

[Tapable (Plugin 'Runner')](https://github.com/webpack/tapable) 

> ⚠️ Most of webpack is a Tapable (Plugin) Instance, an Event Emitter with Flow Control and webpack API 😛 

[Plugin API](https://webpack.js.org/api/plugins/)
