### ISSUE TITLE
TypeError: Cannot read property '_autoprefixerDisabled' of undefined

### ISSUE THREAD

**Issue by gaearon** [postcss/postcss-loader#2]
Getting this error against autoprefixer-core 4.0.2.

**Comment by ai** [comment]
Problem is because Autoprefixer expects PostCSS 3.0 and some other PostCSS plugin uses PostCSS 4.0.

Downgrade other plugins until Autoprefixer will be updated to new PostCSS.

We try to find some better solution here: https://github.com/w0rm/gulp-postcss/issues/14

**Comment by gaearon** [comment]
I see! Thanks.
