### ISSUE TITLE
wierd error after setting alias on css-loader

### ISSUE THREAD

**Issue by kud** [postcss/postcss-loader#203]
Hey,

I'm glad you also work here @michael-ciniawsky because I don't know exactly where to put this _bug_ (postcss-loader or css-loader).

This is what I've got.

```javascript
{
  test: /\.local\.css$/,
  use: [{
    loader: 'style-loader'
  }, {
    loader: 'css-loader',
    options: {
      modules: true,
      importLoaders: 1,
      localIdentName: env === 'prod' ? '[name]--[local]___[hash:base64:5]' : '[path][name]--[local]___[hash:base64:5]',
      import: true,
      alias: {
        '~': `${SRC_DIR}`
      }
    }
  }, {
    loader: 'postcss-loader',
    options: {
      plugins: [
        // autoprefixer(), unneeded for the moment
        customMedia({
          extensions: {
            "--mobile": "(max-width: 480px)",
            "--mobile-only": "(max-width: 480px)",
            "--tablet": "(max-width: 1024px)",
            "--tablet-only": "(min-width: 481px) and (max-width: 1024px)",
            "--desktop": "(min-width: 1025px)",
            "--desktop-only": "(min-width: 1025px)",
          }
        })
      ]
    }
  }]
},
```

It worked well before I added this:

```js
      alias: {
        '~': `${SRC_DIR}`
      }
```

to use this: 

```css
    .actionsBack {
      composes: link from '~/styles/ui.local.css';
    }
```

I had this error:

```console
ERROR in ./~/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[path][name]--[local]___[hash:base64:5]","import":true,"alias":{"~":"/Users/kud/Projects/_contexte/lois-webapp/src"}}!./~/postcss-loader?{"plugins":[null]}!./src/styles/ui.local.css
Module build failed: TypeError: Cannot read property 'postcss' of null
    at Processor.normalize (/Users/kud/Projects/_contexte/lois-webapp/node_modules/postcss/lib/processor.es6:101:18)
    at new Processor (/Users/kud/Projects/_contexte/lois-webapp/node_modules/postcss/lib/processor.es6:35:29)
    at postcss (/Users/kud/Projects/_contexte/lois-webapp/node_modules/postcss/lib/postcss.es6:34:12)
    at /Users/kud/Projects/_contexte/lois-webapp/node_modules/postcss-loader/index.js:129:16
 @ ./~/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[path][name]--[local]___[hash:base64:5]","import":true,"alias":{"~":"/Users/kud/Projects/_contexte/lois-webapp/src"}}!./~/postcss-loader?{"plugins":[null]}!./src/components/AsideFull/index.local.css 3:10-343 13:79-412
 @ ./src/components/AsideFull/index.local.css
 @ ./src/components/AsideFull/index.js
 @ ./src/pages/Bill/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server react-hot-loader/patch ./src/index.js
```
I always read `postcss-loader?{"plugins":[null]}` before, even when defining the plugins this way but had no troubles so I didn't take care so much.

But since I've added `alias` it didn't work well.

So my solution was to export postcss-loader config like this:

`webpack.config.babel.js`:

```javascript
        {
          test: /\.local\.css$/,
          use: [
            {
              loader: 'style-loader'
            },
            {
              loader: 'css-loader',
              options: {
                modules: true,
                importLoaders: 1,
                localIdentName: env === 'prod' ? '[name]--[local]___[hash:base64:5]' : '[path][name]--[local]___[hash:base64:5]',
                import: true,
                alias: {
                  '~': `${SRC_DIR}`
                }
              }
            },
            {
              loader: 'postcss-loader'
            }
          ]
        },
```

`postcss.config.js`:

```javascript
module.exports = {
  plugins: [
    require('postcss-custom-media')({
      extensions: {
        "--mobile": "(max-width: 480px)",
        "--mobile-only": "(max-width: 480px)",
        "--tablet": "(max-width: 1024px)",
        "--tablet-only": "(min-width: 481px) and (max-width: 1024px)",
        "--desktop": "(min-width: 1025px)",
        "--desktop-only": "(min-width: 1025px)",
      }
    })
  ]
}
```

I could be glad like this because it works but multiple things:

1/ Why it doesn't work with my way to define directly the plugins in webpack config?
2/ I don't like having so many files to define my compilation
3/ I can't use es6 in postcss config

Thank you for your time. ;)

Regards,

**Comment by michael-ciniawsky** [comment]
@kud First, sry for the delay 😛 

> I always read postcss-loader?{"plugins":[null]} before, even when defining the plugins this way but had no troubles so I didn't take care so much.

The `alias` only works on e.g `.a { background: url() }`  the `TypeError: Cannot read property 'postcss' of null` comes from `css-loader`, which also uses PostCSS internally for CSS Modules atm and the hacky solution there, fails at some point and `postcss` can't process the content. 

> 1. Why it doesn't work with my way to define directly the plugins in webpack config?

That's a good question and something seems to flanky within `loader-runner` but no clue what atm, see #201, it also bugs somewhere in 'wepack' (ETWP) and the postcss options for `postcss-loader`  set in `webpack.config.js` don't get applied 

> 2. I don't like having so many files to define my compilation

Aggreed it's personal preference and both (`webpack.config.js`/`postcss.config.js`) should work

> 3. I can't use ES6 in `postcss.config.js`

If you are on Node v6+ I'm sure besides of ES2015 modules you can 😛, note that e.g babel would need to run everytime for every file which is unnecessary overhead for a simple config file.


I will test it with the upcoming v2.0.0 of `postcss-loader`, but it seem to be unrelated to the loader itself, since postcss options in `webpack.config.js` are so called `Complex Options` (`{Function}`) with require webpack to generate an  `ident` interally to stringify, I guess it fails/bugs there when something else fails and this could get complicated 

```
!./~/postcss-loader?{"plugins":[null]}!./src/styles/ui.local.css
```

```
!./~/postcss-loader?-->ref--0-0<--{"plugins":[null]}!./src/styles/ui.local.css
```

**Comment by kud** [comment]
Okay, thank you for your explanation @michael-ciniawsky !
