### ISSUE TITLE
No PostCSS Config found

### ISSUE THREAD

**Issue by jeffijoe** [postcss/postcss-loader#204]
I've been using `LoaderOptionsPlugin` until now where everything worked. I then tried to use the inline options but I got `Error: No PostCSS Config found in node_modules/...`, apparently because the plugin uses the PostCSS config resolver if not using webpack 1-style options.

Would it be possible to prevent this if inline options are provided?

**Comment by TrySound** [comment]
Add postcss config to postcss.config.js as specified in documentation

**Comment by jeffijoe** [comment]
The docs specify 2 ways of config: a file and inline as loader options. I want to use the latter, which according to docs is supported. I think this behavior is unintended.

**Comment by michael-ciniawsky** [comment]
@jeffijoe Please post your `webpack.config.js` here, both ways are supported 😛 I will help to fix it, looks like a setup error somewhere

**Comment by michael-ciniawsky** [comment]
@jeffijoe Still free free to post your `webpack.config.js` 😛

**Comment by jeffijoe** [comment]
```js
{
  loader: 'postcss-loader',
  options: {
    plugins: () => [require('autoprefixer')]
  }
}
```

**Comment by michael-ciniawsky** [comment]
webpack version and the error log aswell please :)

**Comment by jeffijoe** [comment]
Webpack 2.4.1

![image](https://cloud.githubusercontent.com/assets/2505474/25606511/0ea55586-2f12-11e7-85da-d99fd52b8f5d.png)

**Comment by michael-ciniawsky** [comment]
The `ERROR in ./.../... ... postcss-loader?->{}<-` is empty ? The config doesn't seem to be applied and that's why it tries to load `postcss.config.js`. Please post the *full* `webpack.config.js`

**Comment by jeffijoe** [comment]
Sure thing.

```js
const path = require('path')
const webpack = require('webpack')
const yenv = require('yenv')
const filter = require('lodash/fp/filter')
const identity = require('lodash/fp/identity')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const BabiliPlugin = require('babili-webpack-plugin')

// Used to filter out environment-specific
// entries in arrays.
const clean = filter(identity)

// Webpack 2 supports function configurations.
// In our package.json we set --env.prod when building for
// production.
module.exports = function ({ prod }) {
  // Since we use ExtractTextPlugin in production, we can't use
  // the new way of declaring loaders, so defining all the CSS loader
  // stuff here to avoid repeating it.
  const cssLoaders = [{
    loader: 'css-loader',
    options: {
      modules: true,
      importLoaders: 2,
      localIdentName: '[name]__[local]___[hash:base64:5]'
    }
  }, {
    loader: 'postcss-loader',
    options: {
      plugins: () => {
        return clean([
          require('rucksack-css')({
            autoprefixer: true
          }),
          prod && require('postcss-csso')
        ])
      }
    }
  }, {
    loader: 'sass-loader'
  }]
  const dev = !prod
  // Used to pass environment variables from env.yaml
  // to DefinePlugin.
  const env = Object.assign(
    yenv(),
    { NODE_ENV: prod ? 'production' : 'development' }
  )
  return {
    devtool: dev ? 'inline-source-map' : 'source-map',
    entry: {
      vendor: [
        'inferno',
        'moment',
        'classnames',
        'jwt-decode',
        'mobx',
        'mobx-task',
        'libx',
        'marked',
        'messageformat',
        'memoizee',
        'inferno-mobx',
        'standalone-react-css-transition-group',
        'react-textarea-autosize',
        'react-router',
        'react-helmet',
        'tinycolor2'
      ],
      app: clean([
        dev && 'react-hot-loader/patch',
        dev && 'webpack-hot-middleware/client',
        path.resolve(__dirname, './index.jsx')
      ])
    },
    plugins: clean([
      new webpack.LoaderOptionsPlugin({
        minimize: prod,
        debug: dev
      }),
      new webpack.optimize.CommonsChunkPlugin({ name: 'vendor' }),
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify(env.NODE_ENV),
          API_ROOT: JSON.stringify(env.API_ROOT)
        }
      }),
      new webpack.NamedModulesPlugin(),
      prod && new webpack.NoErrorsPlugin(),
      dev && new webpack.NoEmitOnErrorsPlugin(),
      dev && new webpack.HotModuleReplacementPlugin(),
      prod && new BabiliPlugin(),
      prod && new webpack.optimize.UglifyJsPlugin({
        output: { comments: false },
        compress: {
          sequences: true,
          dead_code: true,
          conditionals: true,
          booleans: true,
          unused: true,
          if_return: true,
          join_vars: true,
          drop_console: true
        }
      }),
      prod && new ExtractTextPlugin({ filename: 'bundle.css', allChunks: true })
    ]),
    output: {
      // This is only used for production
      path: path.join(__dirname, '../../dist/public'),
      filename: '[name].js',
      publicPath: '/',
      pathinfo: dev
    },
    module: {
      rules: [{
        test: /\.[jt]sx?$/i,
        use: clean([
          'babel-loader'
        ]),
        exclude: /node_modules/
      }, {
        test: /\.(css|sass)$/i,
        use: dev
          ? [{ loader: 'style-loader' }, ...cssLoaders]
          : ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: cssLoaders
          })
      }, {
        test: /\.(gif|png|jpe?g|svg)$/i,
        use: [
          {
            loader: 'image-webpack-loader',
            options: {
              progressive: true,
              pngquant: { quality: '65-90', speed: 4 }
            }
          },
          {
            loader: 'url-loader',
            options: { limit: 5000 }
          }
        ]
      }, {
        // Favicon
        test: /favicon\.ico/i,
        use: [{
          loader: 'file-loader',
          options: { name: 'favicon.ico' }
        }]
      }]
    },
    resolve: {
      extensions: ['.js', '.jsx'],
      modules: ['./', 'node_modules'],
      alias: Object.assign(
        {},
        prod && {
          react: 'inferno-compat',
          'react-dom': 'inferno-compat',
          'mobx-react': 'inferno-mobx',
          'react-addons-css-transition-group': 'standalone-react-css-transition-group'
        }
      )
    },
    performance: {
      hints: prod ? 'warning' : false
    }
  }
}
```

**Comment by michael-ciniawsky** [comment]
```diff
    options: {
      plugins: () => {
-       return clean([
+      return [
          require('rucksack-css')({
            autoprefixer: true
          }),
-          prod && require('postcss-csso')
        ])
      }
    }
```

This won't work because webpack **stringifies** the returned value internally, that's why we have **`postcss.config.js`** and recommend it 

**webpack.config.js**
```js
...
plugins: () => prod ? return [...plugins] : return [...plugins, ...devPlugins ] // maybe
```

or

**postcss.config.js**
```js
module.exports = (ctx) => ({
  plugins: [
    ...
    ctx.env === 'production' ? require('postcss-csso') : false
  ]
})
```

**Comment by jeffijoe** [comment]
The returned value is an array - `clean()` simply filters out falsy values. Unless you're saying Webpack stringifies the `options` hash? That can't be, because if that was the case it would choke on the fact `plugins` is a function.

**Comment by michael-ciniawsky** [comment]
It needs an `ident` stringifies the functions in `options: {}`+ references the the `require()` calls based on the `ident`. The `LoaderOptionsPlugin` works enterily different and it's purpose was to make loaders not supporting webpack 2 option syntax work with webpack 2 beta during the webpack 2 beta phase and is deprecated now. It should be used only for loaders **not** supporting webpack 2 syntax, otherwise removed.

Does it work now?

**Comment by jeffijoe** [comment]
I tried:

```
options: {
      plugins: () => {
        return [
          require('rucksack-css')({
            autoprefixer: true
          })
        ]
      }
    }
```

Still no luck. Removed the conditional.

**Comment by michael-ciniawsky** [comment]
hmm... last resort is trying with `postcss-csso` instead of `rucksack-css` (Plugin Package), otherwise it's a more nasty issue somewhere else, if still no luck please try a config file aswell for debugging proposes

**Comment by jeffijoe** [comment]
I put a `postcss.config.js` in the root of my `client` folder, although `node_modules` is 2 levels above that, causing issues when importing css from `node_modules`.

Putting the config file at the root of the project works, but now my project root is littered with client code and breaks my otherwise clean separation of server and client code. This is why I preferred the inline approach.

**Comment by michael-ciniawsky** [comment]
Can you `tree` your project and post it here please 👍 :)

**Comment by jeffijoe** [comment]
![image](https://cloud.githubusercontent.com/assets/2505474/25614839/1a262e18-2f34-11e7-9a88-ec77c4952589.png)

**Comment by michael-ciniawsky** [comment]
Out of the gut I guess neither `postcss-load-config` when placed in `./src` nor `webpack.config.js`  in `./src` can pick up the packages in `node_module`

**Comment by jeffijoe** [comment]
Yeah its probably using the same resolution strategy as `.babelrc`

So there's no way to work around this within the Webpack config?

**Comment by michael-ciniawsky** [comment]
Nope 😛 at least not to my knowledge

**Comment by jeffijoe** [comment]
Fair enough, didn't know about that Webpack stringify behaviour. 😄

**Comment by funkyLover** [comment]
so the conclusion is we can't replace `postcss.config.js` with `inline options in webpack`? same issue here.

**Comment by michael-ciniawsky** [comment]
@funkyLover No both are supported and `webpack.config.js` > `postcss.config.js` in terms of loading behaviour, we still recommend `postcss.config.js`

**Comment by yarnball** [comment]
Hi, I'm having the same issue. I am trying to use `react-toolbox` but keep getting this error (No PostCSS config found). It does so in 2 locations.

Any ideas on a fix?

Here is my config file:

```
const webpack = require('webpack');
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const config = {
  context: __dirname,
  entry: './src/index.js',
  output: {
    path: __dirname,
    filename: 'bundle.js',
  },
  module: {
    loaders: [{
      exclude: /node_modules/,
      test: /\.(js|jsx)$/,
      loader: 'babel',
    },
    {
    test: /\.(eot|svg|ttf|woff|woff2)$/,
    loader: 'file?name=public/fonts/[name].[ext]'
    },
    { test: /\.json$/, loader: "json-loader" },
      {
        test: /\.css$/,
        loaders: [
          'style-loader',
          'postcss-loader',
          'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss?sourceMap&sourceComments',
        ],
      },
    {
    test: /\.scss$/, loader: ExtractTextPlugin.extract('css!sass'),
    }],
  },
  devServer: {
    historyApiFallback: true,
    contentBase: './',
  },
  plugins: [
    new webpack.DefinePlugin({ 'process.env': { NODE_ENV: JSON.stringify('production') } }),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new ExtractTextPlugin('src/public/stylesheets/app.css', {
      allChunks: true,
    }),
  ],
};

module.exports = config;
```

**Comment by michael-ciniawsky** [comment]
@yarnball webpack `v1 || v2` ? `postcss-loader` v?

```diff
 {
        test: /\.css$/,
        loaders: [
          'style-loader',
-         'postcss-loader',
          'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss?sourceMap&sourceComments',
+         'postcss-loader',
        ],
}
```

Do you use have a `postcss.config.js` in place ?

**Comment by yarnball** [comment]
I'm on webpack v1. I don't have a post.css.config in place anywhere- as the react toobox did not say it was needed.

**Comment by michael-ciniawsky** [comment]
How do you intend to use `postcss-loader` ? :)  Your current `webpack.config.js` does nothing...

**Comment by yarnball** [comment]
I did intend to use it yes- where have i gone wrong with it?

**Comment by michael-ciniawsky** [comment]
You need to either us a `postcss.config.js` file or  add a `config.postcss` prop to your `webpack.config.js` 

**webpack.config.js**
```js
module: {
  loaders: [
    {
      test: /\.css$/,
      loaders: [
       'style-loader',
       'css-loader',
       'postcss-loader'
      ]
    }
  ]
},
postcss: () => [...plugins]
```

**Comment by Bnaya** [comment]
Hey, i'n having the same issue
My relevant webpack2 config is:
```js
      new webpack.LoaderOptionsPlugin({
        options: {
          context: sourcePath,
          postcss: [
            require('postcss-import')({ addDependencyTo: webpack }),
            // this was breaking url-loader / file-loader require('postcss-url')(),
            require('postcss-cssnext')({
              browsers: [
                "last 2 Chrome versions",
                "last 2 Edge versions",
                "last 2 Safari versions",
                "last 2 Firefox versions",
              ],
            }),
            require('postcss-reporter')(),
            require('postcss-browser-reporter')({ disabled: isProduction })
          ]
        }
      }),
```

It was working until the last update

Thanks!

**Comment by dwolfhub** [comment]
@Bnaya i had same issue. when updating to 2.x please check readme for new configuration.

here is mine:

```
    {
      loader: 'postcss-loader',
      options: {
        plugins: (loader) => [
          require('autoprefixer')({browsers: ['last 3 versions', 'iOS 9']}),
        ]
      }
    },
```

**Comment by remotezygote** [comment]
I am having this issue also after updating to the latest version. My webpack config is dynamically generated, but here is the relevant config section:

```
const postCSSConfig = {
  sourceMap: useSourceMaps,
  plugins() {
    return [
      autoprefixer({ browsers: ['last 2 versions'] }),
      classprefixer('scoped-', {
        ignore: [
          /^tether/,
        ],
      }),
    ];
  },
};
```

then when used:

```
{
  loader: 'postcss-loader',
  options: postCSSConfig,
},
```

It looks correct to me, but I still get this error for every single directory that has any css file loaded in it. Any ideas?

**Comment by remotezygote** [comment]
FYI, I walked this back all the way to 2.0.0, and it worked differently (resolved paths differently), but all had the same error as before. I do not believe config loading from webpack config is working properly. Possibly it is only breaking in certain cases? In my case, I load many SCSS files throughout my app. Was that case tested, or only a case of a single entry point? Grasping at straws a bit here. I would just go back to pre-2.0 versions, but then I get warnings about loader options deprecation. Kind of bad either way at this point...

**Comment by michael-ciniawsky** [comment]
@remotezygote 

```diff
const postCSSConfig = {
+ ident: 'postcss',  // <= this line
  plugins () {
    return [
      autoprefixer({ browsers: ['last 2 versions'] }),
      classprefixer('scoped-', {
        ignore: [
          /^tether/,
        ],
      }),
    ];
  },
  sourceMap: useSourceMaps,
};
```

Yes `{Function}` && `require()` are both buggy in webpack config atm, it should have been solved in `webpack >= 2.2.0` by autogenerating the `ident`, but since `webpack >= 2.4.0` it doesn't seem to work anymore 😞 . I will try one last attempt @webpack/webpack if this can be solved otherwise it is likely that `postcss.config.js`  will be mandatory in the near future

**Comment by brandonaaskov** [comment]
This same error popped up for me, but the issue wasn't due to the `postcss-loader`, it was because I was using the `importLoaders` option for `css-loader`.

*Before*
`{ loader: 'css-loader', options: { sourceMap: true, importLoaders: 1 } }`

*After*
`{ loader: 'css-loader', options: { sourceMap: true } }`

I'm not going to imply that will fix the issue for others, but I hope that it does :)

**Comment by lucasmotta** [comment]
@michael-ciniawsky adding the `ident: 'postcss'` to the options config works fine.

I understand that webpack has its issues, but do you think this option can be documented on the README? I don't mind having to add the `ident` line to my config.

**Comment by littlenewbee** [comment]
I use the webpack 2.x,and I have the same error when I use the importLoaders option .which one get the reason?

**Comment by nickperkinslondon** [comment]
All of this webpack confusion is unfortunate.
I use React and Webpack, but I don't use CSS myself ( and I don't know or care what "postcss" is )
I just wanted to try React Toolbox, but I have been unable to make it work!
I am going back to Material-UI

**Comment by dudewad** [comment]
I have to back this up, I'm experiencing issues using the most basic of configurations for 2.x versions of webpack. The documentation is in severe need of updating; I've been stuck on this for several hours now and its killing me.

**Comment by japboy** [comment]
This might be irrelevant though, `postcss.config.js` seems to be named as it is as always.

```js
      {
        loader: 'postcss-loader',
        options: {
          config: {
            ctx: {
              alias: base.baseConf.resolve.alias,
            },
            path: path.resolve(__dirname, 'postcss.config.js'),
          },
        },
      },
```

This works unless I change the config name to something different like `postcss.amp.conf.js` or something.

**Comment by mattmewton** [comment]
Bump. I'm having similar issues with the PostCSS config not being found. I am using the `path.resolve` function to find my config, but it seems that Webpack is still searching for the config in folders relative to where `postcss` is being called. So for example, if I have a `.vue` file that uses `postcss` at a path of `src/javascript/`, PostCSS will say there is no config in the `src/javascript` folder, when I am explicitly pointing to a config located somewhere else.

Here is a snippet of my config with the issue in question:
```
{
    test: /\.vue$/,
    loader: 'vue-loader',
    options: {
        loaders: {
            css: ExtractTextPlugin.extract({
                use: [
                    'css-loader?importLoaders=1',
                    {
                        loader: 'postcss-loader',
                        options: {
                            config: {
                                path: path.resolve(__dirname('build/webpack/postcss.config.js')),
                            },
                            sourceMap: true,
                        },
                    },
                ],
                fallback: 'vue-style-loader',
            }),
        },
    }
},
```

**Comment by ParallelUniv3rse** [comment]
@mattmewton I think you're just using the __dirname variable wrong. 
I managed to finally get everything working and I'm set up as follows: 

directory structure for reference:
```
config/
├── webpack.config.js/
└── postcss.config.js/
```

in webpack.config.js:
```
{
  loader: 'postcss-loader',
  options: {
    config: {
       path: path.resolve(__dirname, './postcss.config.js'),
    },
  },
},
```

postcss.config.js:
```
module.exports = {
  sourceMap: true,
  plugins: [
    require('autoprefixer')({ browsers: ['last 3 versions', '> 1%'] }),
  ],
};
```

**Comment by MrVichr** [comment]
Just a note to anyone with this problem, I spent quite a few hours checking all configs back and forth until I figured out that I had to add an empty plugins() function for PostCSS to recognize the options.
```diff
 {
    loader: 'postcss-loader',
    options: {
      sourceMap: true,
+     plugins: function() { return []; } //had to add this line to avoid Error: No PostCSS Config found in ...
    }
 }
```

**Comment by kleinfreund** [comment]
The following will do when you want to use inline configuration for postcss:

```js
{
  loader: 'postcss-loader',
  options: {
    plugins: []
  }
}
```

This needs to be documented. Without the plugin property, the build throws the no config error.

**Comment by charleslaw** [comment]
I stumbled on this thread after hitting the same issue.  I eventually found this reference very helpful: https://github.com/react-toolbox/react-toolbox-example/

**Comment by angusmunro** [comment]
Empty plugins did it for me. Thanks

**Comment by Chucheen** [comment]
Empty plugins did for me too :)

**Comment by fabricecolas** [comment]
Also, make sure that the `postcss.config.js` is located in the root folder of your app, otherwise when processing sub-modules (under `node_modules`), webpack won't find the `postcss` config file in the sub-module's hierarchy.

**Comment by TheDutchCoder** [comment]
Adding empty plugins breaks resolving node_module imports :(

**Comment by zhaojjiang** [comment]
Another scene for me: node_modules is worked with symlink, then I set `resolve.symlinks: false` and solved it.
