### ISSUE TITLE
[2.0.1] cssnano's discardComments not effect for css

### ISSUE THREAD

**Issue by someok** [postcss/postcss-loader#213]
I have 3 webpack module to parse css and sass, every module have a `postcss-loader`, so I use a `postcss.config.js` to parse all css data.

But I found my css file still has comments, so I debug the postcss's process and found cssnano's discardComments plugin not effect at all, `removeAll: true` is null.

I think `postcss-loader` not load `postcss.config.js` success.

<img width="730" alt="2017-05-09 7 11 12" src="https://cloud.githubusercontent.com/assets/1523082/25829395/5a386670-3488-11e7-8877-c4fc979b825c.png">

postcss.config.js:
```
module.exports = ({env}) => {
    console.log('postcss: ', env);
    const isDev = env === 'development';

    return {
        sourceMap: true,
        plugins: {
            autoprefixer: {},
            cssnano: {
                discardEmpty: true,
                discardDuplicates: true,
                colormin: true,
                discardComments: {removeAll: true},
            }
        }
    }
};
```

webpack:
```
{
                test: /\.css$/,
                use: extractCommonCSS.extract({
                    fallback: 'style-loader',
                    use: [
                        'css-loader',
                        'postcss-loader'
                    ]
                })
            }, {
                test: /\.scss$/,
                include: [
                    /container/,
                    /component/
                ],
                use: extractModuleCSS.extract({
                    fallback: 'style-loader',
                    use: [
                        {
                            loader: 'css-loader',
                            options: {
                                modules: true,
                                importLoaders: 2,
                                localIdentName
                            }
                        },
                        'postcss-loader',
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: isDev
                            }
                        }
                    ]
                })
            }, {
                test: /\.scss$/,
                include: [
                    /node_modules/,
                    /style/
                ],
                use: extractCommonCSS.extract({
                    fallback: 'style-loader',
                    use: [
                        'css-loader',
                        'postcss-loader',
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: isDev
                            }
                        }
                    ]
                })
            }
```

**Comment by michael-ciniawsky** [comment]
Please try the fix branch and provide feedback 😛 npm i -D postcss/postcss-loader#fix

We have a config applying bug in `2.0.1` atm 😟 Hopefully the `fix`branch resolved this

**Comment by michael-ciniawsky** [comment]
**postcss.comfig.js**
```
return {
  sourceMap: true,
  ...
```

That's not supported, you need to set this in `webpack.config.js`, but only if you installed the `fix` branch, otherwise by removing this is should work atm from `postcss-loader` perspective

**Comment by someok** [comment]
I install the fix version, but discardComments problem still there

**Comment by michael-ciniawsky** [comment]
`discardComments` only ? (it gets minified at all 😛 ?)

**Comment by michael-ciniawsky** [comment]
[Hopefully 😛] fixed by https://github.com/postcss/postcss-loader/commit/e764761
Released in [`v2.0.2`](https://github.com/postcss/postcss-loader/releases/tag/v2.0.2)

Awaiting futher reply :D

**Comment by someok** [comment]
If postcss-loader is 2 loader after sass, the process is right.

The problem is that it as 1 loader.

Michael Ciniawsky <notifications@github.com>于2017年5月9日周二 10:04写道：

**Comment by michael-ciniawsky** [comment]
How do your comments look like `//` (SASS) or  `/* */` (CSS) ?

**Comment by michael-ciniawsky** [comment]
With `v2.0.2` you can now use `{ sourceMap: true }` in `postcss-loader`, `postcss.config.js` still works, the source map from `sass-loader` will be discarded by `postcss-loader` otherwise :) 

```js
// css-loader...
{
   loader: 'postcss-loader',
   options: { sourceMap: true }
}
// sass-loader...
```

**Comment by someok** [comment]
Two comment style `/**/` and `//` are all used.

**Comment by michael-ciniawsky** [comment]
They are still not getting dicarded with latest `postcss-loader`(`v2.0.3`) ?  `//` is SASS Comment Style but the should get transpiled to `/* */` by `sass-loader` && it doesn't work for both `{test: /\.css$/}` (CSS Files) && `{ test: /\.scss$/ }` (SASS Files) ?

**Comment by evilebottnawi** [comment]
@someok @michael-ciniawsky  Thanks for issue, but seems not related to `postcss-loader`, original issue https://github.com/ben-eb/cssnano/issues/90.

**Comment by michael-ciniawsky** [comment]
Yep, I was guessing that too @someok quoted from the issue 

> This is caused by https://github.com/postcss/postcss-filter-plugins - will be removed for v4. To resolve, pass {filterPlugins: false}.

Sry but won't fix in `postcss-loader`
