### ISSUE TITLE
Error: Unsupported previous source map format

### ISSUE THREAD

**Issue by msecret** [postcss/postcss-loader#22]
When running with the option `devtool: 'inline-source-map'`, I got the error: `Error: Unsupported previous source map format`. I traced this to a change in API in postcss version 4.0: https://github.com/postcss/postcss/issues/98. I was also able to fix this by making the following change to index.js

```js
map: {
            inline: true,
            annotation: false
        }
```

```js
map: true
```

I'm happy to submit a PR but wanted to check if anybody else that knew more about this could confirm that this makes sense.

**Comment by ai** [comment]
If you add `map: true`, it will enable always inlined source maps.

But according loader API, loader should return map object.
