### ISSUE TITLE
[2.0.5] CSS Modules hash mismatch (React SSR)

### ISSUE THREAD

**Issue by chrisblossom** [postcss/postcss-loader#222]
I have a React SSR that uses Webpack on the client and server. After updating to ``postcss-loader v2.0.3``, my generated CSS Module hash's are different on the client and the server.

I am unsure if the issue is related to ``postcss-loader`` directly or if it is a new/updated dependency brought in by ``v2.0.3``.

I can bring up a skeleton repository if that would help to demonstrate the issue I am having.

**Comment by michael-ciniawsky** [comment]
@chrisblossom Yep please provide a small repo, are you using sourcemaps in `postcss-loader` ?
Note that we are in the transition phase to move CSS Modules from `css-loader` into `postcss-loader` via a compatible PostCSS Plugin in the future

**Comment by chrisblossom** [comment]
During the process of gutting my app to give an example repository, I found the following in my server webpack config:

```js
        new webpack.LoaderOptionsPlugin({
            options: {
                context: __dirname,
            },
        }),
```

After removing that, everything works as expected. Thanks for the quick reply!

**Comment by theasia-Ashish** [comment]
@chrisblossom  your comment save my life, after struggling this checksum warning nearly a month.
