### ISSUE TITLE
[2.0.3] `postcss.config.js` not resolved correctly unless `options.config` is set

### ISSUE THREAD

**Issue by Kovensky** [postcss/postcss-loader#226]
In https://github.com/postcss/postcss-loader/blob/39638602/lib/index.js#L63, `rc.path` is only set if `options.config` is given by the user, instead of defaulting to `path.dirname(file)` as it seems was the original intent.

This means `postcss-loader` by default can only find a `postcss.config.js` relative to `process.cwd()` instead of one relative to the currently processed file; unless (at least) an empty `config` object is given in the `options`.

This is a regression relative to pre-2.0 behavior.

**Comment by michael-ciniawsky** [comment]
Sloppy.. 😛 I fix asap

**Comment by michael-ciniawsky** [comment]
Released in https://github.com/postcss/postcss-loader/releases/tag/v2.0.4
