### ISSUE TITLE
cssnext examples don't work

### ISSUE THREAD

**Issue by taion** [postcss/postcss-loader#23]
I was trying to use this loader to use cssnext and autoprefixer. The examples seem not to work with the latest versions - I found that I had to use `cssnext()` instead of just `cssnext` to get cssnext to run.

**Comment by ai** [comment]
What version of loader and cssnext you used before and update before this issue?

**Comment by taion** [comment]
`postcss-loader@0.6.0` and `cssnext@1.8.3`. I was setting this up from scratch - didn't have this working at any point. I could just be doing something wrong though.

**Comment by ai** [comment]
@taion can you help me (I am on the way and can do research myself). Do you update `cssnext` too? Can you reduce `cssnext` back and update only `postcss-loader`?

**Comment by taion** [comment]
Oh, I see that this example just got added. I think there's just a slight typo there. Instead of:

```js
    postcss: function () {
        return [autoprefixer, cssnext];
    }
```

it should be

```js
    postcss: function () {
        return [autoprefixer, cssnext()];
    }
```

BTW, I'm unclear as to when it's better to use `postcss-loader` with the `cssnext` plugin v just using `cssnext-loader`. Could it be worth explaining that?

**Comment by ai** [comment]
@taion technically, `cssnext` should works wihout `()`. Do I right @MoOx ?

**Comment by ai** [comment]
@taion the most easy way is a `cssnext-loader`. But PostCSS has many awesome plugin, so I didn’t see a reason why you should use only Autoprefixer and cssnext :D. For example, [font-magician](https://github.com/jonathantneal/postcss-font-magician).

**Comment by taion** [comment]
This is far beyond anything I know, but it looks like `cssnext` exports a function that returns a plugin, rather than directly exporting a plugin: https://github.com/cssnext/cssnext/blob/1.8.3/src/index.js#L20

**Comment by ai** [comment]
Seems like. OK, so it is not a problem of PostCSS 5.0 (we made so many changes there :D ).

**Comment by taion** [comment]
Although this example is a little weird if you think about it, since `cssnext` already includes `autoprefixer` if I'm not mistaken.

**Comment by ai** [comment]
@taion yeap, I will change example

**Comment by ai** [comment]
Done 246c90f

**Comment by MoOx** [comment]
cssnext also have a "plugins" option to pipe more plugins.

**Comment by taion** [comment]
@ai @MoOx Oof. That only makes it more confusing as to whether I should use `postcss-loader` or `cssnext-loader`.

**Comment by MoOx** [comment]
This will be more clear in cssnext 2.x when cssnext will deprecate all cssnext runners in favors of postcss ones.
