### ISSUE TITLE
What's the correct way to configure plugins within Webpack 2?

### ISSUE THREAD

**Issue by rfgamaral** [postcss/postcss-loader#235]
I've always had this loader configuration in my Webpack 2 configuration:

```
loader: 'postcss-loader',
options: {
    sourceMap: 'inline',
    plugins: () => {
        return [
            require('postcss-import'),
            require('postcss-cssnext')
        ];
    }
}
```

But I look at the README and I see this:

```
loader: 'postcss-loader',
options: {
    plugins: (loader) => [
        require('postcss-import')({ root: loader.resourcePath }),
        require('cssnext')(),
        require('autoprefixer')(),
        require('cssnano')()
    ]
}
```

And I'm confused about the correct way to require plugins. I've tested both these approaches:

1. `require('postcss-cssnext')`
2. ` require('postcss-cssnext')()`

Both work, but what is the correct way and what are the differences?

Also, I never defined the `root` property for `postcss-import` and it is working. In what circumstances would I need to define it?

**Comment by evilebottnawi** [comment]
@rfgamaral both valid, if your want to pass options to plugin use `require('postcss-cssnext')({...options})` (see in docs `pluginFunction`), if not - use just `require('postcss-cssnext')` (see i docs `Plugin`). It is related to `postcss` (http://api.postcss.org/Processor.html#use)

**Comment by evilebottnawi** [comment]
More simple with examples:

Using `postcss.plugin("postcss-plugin", (options) => {});` your got `Plugin` (http://api.postcss.org/postcss.html#.plugin)

Using `postcss.plugin("postcss-plugin", (options) => {})();` your got `pluginFunction` (http://api.postcss.org/global.html#pluginFunction)

**Comment by evilebottnawi** [comment]
@rfgamaral ping me if need more help

**Comment by rfgamaral** [comment]
No need. I get it now. Thanks very much.
