### ISSUE TITLE
CSS nesting parse error after upgrade from v1.3.3 to v2.0.5

### ISSUE THREAD

**Issue by fengyuanchen** [postcss/postcss-loader#236]
Input:
```css
  .foo {
    &__bar {
      & > baz {}
    }
  }
```

Expected output: 
```css
.foo {}
.foo__bar {}
.foo__bar > baz{}
```

Actual output: 
```css
.foo {}
.foo__bar { 
  & > baz{} 
}
```

**Comment by michael-ciniawsky** [comment]
`postcss-nested` (if update to  `v2.0.0`) / `cssnext` @seehttps://github.com/MoOx/postcss-cssnext/issues/374 `postcss-loader` uses PostCSS 6 and a few plugins haven't been updated yet.
