### ISSUE TITLE
SourceMaps: CSS sources inside build file

### ISSUE THREAD

**Issue by olegstepura** [postcss/postcss-loader#239]
Hi!

Test repo: [olegstepura/postcss-loader-test](https://github.com/olegstepura/postcss-loader-test)

I made this change: [changeset](https://github.com/olegstepura/postcss-loader-test/commit/69d2d4df17ef8c6b8a40f46879b52ef31fb2a5a3) (added `sourceMap: false` to `webpack.config.js`)
If I run `npm run build` final built file is 1.6Mb
If I remove this back to just string with the loader name, and run `npm run build` again final built file is 0.8Mb
It becomes even heavier with this change (which should remove sourcemaps). 

Sourcemaps stuff is complex, sorry to bother you. 

### Use case 1: I do not want source maps for CSS

- I  perform [this changes](https://github.com/olegstepura/postcss-loader-test/commit/01ad28e851aaefd55d27e42ee6668f44561d5563)
- `npm run build`
- bult file has sources! And it's size is 971kb.

#### Ok, maybe some PostCSS config should be added. 
- Add some config to `postcss.config.js`: [changeset](https://github.com/olegstepura/postcss-loader-test/commit/e2d7c558fc7f9614a4dece648c15973f4a69f02a)
-  `npm run build`
-  bult file has sources! And it's size is still 971kb.

### Use case 2: I want source maps to be stored in separate `build.js.map` file. This would be usefull to debug production build one day.
 - I perform
```diff
- sourceMap: false
+ sourceMap: true
``` 
[see this changeset](https://github.com/olegstepura/postcss-loader-test/commit/11432921ddd9073118ccd161f5e1284a9def3e6a)
 - `npm run build`
 -  bult file has sources! Sources are not in `.map` file (maybe there as well) And built file is 1.23 MB

I'm kind of lost... Am I doing something wrong? What is going on with sourceMaps? I tried to remove `postcss-each` and `postcss-cssnext` since you wrote these do not support PostCSS v6, but result is the same: if I disable sourcemaps, there are sources in built file (all those `--palette-grey-300:#e0e0e0;--palette-grey-400:#bdbdbd;--palette-grey-500:#9e9e9e;`) and it's size is 971kb.

Please help me figuring out on how to manage sourceMaps, I've read [this guide](https://github.com/postcss/postcss/blob/master/docs/source-maps.md) and your README section according source maps. Nothing helps. 

Thanks!

**Comment by michael-ciniawsky** [comment]
So it works,  if you don't use `{ loader: 'postcss-loader', options: { sourceMap: false } }` but just `'postcss-loader'` in `webpack.config.js` ? (Just omit the `{ sourceMap: false }`) (It's the default)


>  if I disable sourcemaps, there are sources in built file (all those --palette-grey-300:#e0e0e0;--palette-grey-400:#bdbdbd;--palette-grey-500:#9e9e9e;) and it's size is 971kb

These are CSS Variables (CSS Custom Properties) not related to source maps in any way. It's normal to have them  in the source :). Do you in general mean the CSS in your webpack bundle, when you refer to 'sources' ?

**Comment by michael-ciniawsky** [comment]
Did you solve it or still regressions ? :)

**Comment by michael-ciniawsky** [comment]
Feel free to reopen anytime, but closing for now

**Comment by olegstepura** [comment]
Hi!

1. What cannot be achieved: 
sources should be in `.map` file, not in build file itself (if I turn `sourceMap: true`, sources are inside of build file, but my opninion is that it should not be there). 

2. What I'm not sure about: 
there are sources with `var(---some-var)` syntax, which should be eleminated after running `postcss` with `cssnext`. Build file should contain only final css, which browsers understand. Here I'm not sure, maybe currently old version of `cssnext` (without support for `PostCSS v6`) is the issue. But this issue was for sure actual with previous versions of all stuff (including `postcss-loader v1.3.3` and `PostCSS v5`).

**Comment by michael-ciniawsky** [comment]
1. Is actually an issue with `webpack`/`webpack.config.js`. `postcss-loader`has no influence upon that, `output.sourceMapFilename` + `devtool: 'source-map'` should do the trick normally 

2. 

```js
variables: {
  'color-primary': 'var(--palette-indigo-500)',
  'color-primary-dark': 'var(--palette-indigo-700)',
  'color-primary-light': 'var(--palette-indigo-500)',
  'color-accent': 'var(--palette-pink-a200)',
  'color-accent-dark': 'var(--palette-pink-700)',
  'color-primary-contrast': 'var(--color-dark-contrast)',
  'color-accent-contrast': 'var(--color-dark-contrast)'
}
```

This is off, you need to actually provide a value :). Current is e.g 'var(--palette-indigo-500)' no wonder it is still 'there'

```js
/* picked up by cssnext */
:root {
  --color: red;
}

.class {
  background: var(--color);
}
```

or 

**postcss.config.js**
```js
...
variables: {
  'color': 'red',
  ...
}
...
```

```js
.class {
  background: var(--color);
}
```

[postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) (used by cssnext)

**Comment by olegstepura** [comment]
Hi!

@michael-ciniawsky Thanks for your time!

1. There is this: [`sourceMapFilename: '[name].js.map',`](https://github.com/olegstepura/postcss-loader-test/blob/master/webpack.config.js#L31) and this: [`devtool: 'source-map',`](https://github.com/olegstepura/postcss-loader-test/blob/master/webpack.config.js#L42) and  build file contains sources. Sorry, I'm not expert here, but this is an issue. Where should I report? Thanks!

2. Seems like you are right. [I created a separate branch](https://github.com/olegstepura/postcss-loader-test/tree/no-source-maps).  I [commented out](https://github.com/olegstepura/postcss-loader-test/commit/9ed4131c7376de2e81d03e4d9381775e74733720) those variables. If I remove variables section and turn off sourcemaps, there is no `vars` in final CSS. Thanks!

**Comment by michael-ciniawsky** [comment]
1. webpack/webpack 

2. All off the following will have no effect and can be safely removed, only `{ sourceMap: true || 'inline' }` in `webpack.config.js` will change the behaviour regarding source maps.

```diff
-      map: {
-        sourcesContent: false,
-        inline: false
-      },
```
