### ISSUE TITLE
[2.0.6] docs(README): inconsistent use of 'cssnext' or 'postcss-cssnext' plugin references

### ISSUE THREAD

**Issue by ecbrodie** [postcss/postcss-loader#246]
The README is confusing, as to whether I include the CSSNext plugin in my `postcss.config.js` file as `"cssnext"` or `"postcss-cssnext"`. There are examples of both styles in the README. Is this intentional? If not, then please let me know which plugin name is meant to be used and then I can submit a PR that clarifies the README. Thank you.

**Comment by michael-ciniawsky** [comment]
`postcss-cssnext` is the right name, `cssnext` is deprecated in favour of && superseded by `postcss-cssnext`. PR would be appreciated 😛

**Comment by ecbrodie** [comment]
@michael-ciniawsky thank you for the fast feedback. I will submit a PR later today.

While I have your attention and also on the subject of README and plugins, I want to get some clarification about specifying postcss plugins in `postcss.config.js` (or inlined within `webpack.config.js`). Some examples in the README have the`plugins` specified as an objects whose string keys represent the names of postcss plugins to apply. Other examples has the `plugins` represent a function that accepts a single `webpack` parameter and returns an array of `require`'d plugin references. Which one is valid, or are both valid? Also, in the latter case of the object, can the plugins array contain string references or must they be key-value pairs? For example, if I wanted to specify the `postcss-import` plugin without any custom options, can I specify just `'postcss-import'` in the plugins array or must it be `'postcss-import': {}`?

Thank you.

**Comment by michael-ciniawsky** [comment]
### `postcss.config.js`

`postcss.config.js` (`postcss-load-config`) support both `{Object}` && `{Array}` notation

```js
...
plugins: [
  require('postcss-plugin')({...options})
]
...
```

```
...
plugins: {
  'postcss-plugin': {} || false // empty {} === true
}
...
```

`Key/Value` is mandatory, when using `{Object}` notation

### `webpack.config.js`

Doesn't support `{Object}` Notation, since this is a convenience methof of `postcss-load-config`, PostCSS Plugins are an `{Array}`

```js
{ 
  loader: 'postcss-loader', 
  options: {
    plugins: [] // {Array}
  }
}
```

### Static vs. Dynamic 

Both `postcss.config.js` && `webpack.config.js` config can be either static `{Array|Object}` or dynamic `{Function}`

**postcss.config.js**
```js
 // {Function} && ctx === { file, options, env }
module.exports = (ctx) => ({
   parser: file.extname === '.sss' ? 'sugarss' : false
   plugins: []
})
```

**webpack.config.js**
```js
{ 
  loader: 'postcss-loader', 
  options: {
    // {Function} && loader === Loader API
    plugins: (loader) => [
      require('postcss-plugin')({ root: loader.resourcePath })
    ]
  }
}
```

**Comment by michael-ciniawsky** [comment]
Done in https://github.com/postcss/postcss-loader/commit/2ef4449d5715935a214a8ea588d3d09eb0c72241

**Comment by ecbrodie** [comment]
@michael-ciniawsky I realize that I never thanked you for your excellent response to my question about the different ways to specify plugins. It was quite clear and answered my question well. Thank you!
