### ISSUE TITLE
[postcss@0.6] `Module build failed: TypeError: Cannot read property 'before' of undefined`

### ISSUE THREAD

**Issue by iam4x** [postcss/postcss-loader#25]
postcss-loader@0.6 css-loader@0.16.0 cssnext@1.8.4

my `app.css`:

```
@import 'bootstrap/dist/css/bootstrap';

body {
  padding-top: 100px;
}

/* on dev make redux-devtool always shown */
.navbar-fixed-top {
  z-index: 998;
}

.user-list ul,
.user-list li {
  list-style-type: none;
  padding: 10px 0px;
}

.user-list li {
  padding: 10px 20px;
}

.user-list li img {
  margin-right: 10px;
}
```

Had to rollback to `0.5.1`

**Comment by ai** [comment]
This issue from old version of postcss-import, which still uses PostCSS 4.x with many hacks, so we can't handle compatibility fixes.

@MoOx was released new version. Maybe we need to wait for cssnext update.

Downgrade postcss-loader until cssnext update.

**Comment by MoOx** [comment]
We need to get all modules compatible. Please track this issue https://github.com/cssnext/cssnext/issues/202

**Comment by iam4x** [comment]
Okey thank's subscribed :)
