### ISSUE TITLE
package.json config definition [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [postcss/postcss-loader#252]
Sorry to bother again: does postcss-loader support configuration defined in package.json?

https://github.com/stylelint/stylelint/issues/2609#issuecomment-306765151

Instead of:
```
            autoprefixer({ browsers: config.browserslist }),
            styleLint({
                extends: ['stylelint-config-standard', 'plugin:scss/recommended'],
                plugins: ['stylelint-scss'],
            }),
            postcssReporter({ throwError: true }),
```
=>
```
            autoprefixer(),
            styleLint(),
            postcssReporter({ throwError: true }),
```

**Comment by michael-ciniawsky** [comment]
Yes via `postcss-load-config` && `postcss` prop in `package.json`, recommended way is to use
`postcss.config.js`. For stylelint there maybe an additional `stylelint` prop needed/possible or you use the Stylelint PostCSS Plugin, I'm not personally using Stylelint via webpack, so please consider their README for more info about that
