### ISSUE TITLE
postcss-js parser option doesn't work on imports with webpack loaders

### ISSUE THREAD

**Issue by sukazavr** [postcss/postcss-loader#255]
I've tried to make some CSS-in-JS webpack config, like was in README.md:

```JS
{
  test: /\.style.js$/,
  use: [
    'style-loader',
    { loader: 'css-loader', options: { importLoaders: 2 } },
    { loader: 'postcss-loader', options: { parser: 'postcss-js' } },
    'babel-loader'
  ]
}
```

It works, BUT then I try to import an image, for example, I have webpack: Failed to compile.
It looks like in those conditions postcss-loader can't do transfer import-flow into webpack instead, it uses some built-in babel-config.

**The peace of my experiment webpack config:**
```JS
[
  {
    test: /\.cssm\.js$/,
    include,
    exclude,
    use: [
      'raw-loader',
      {
        loader: 'postcss-loader',
        options: {
          parser: 'postcss-js',
          plugins: (loader) => [
            autoprefixer({ browsers: browserslist }),
          ]
        }
      },
      {
        loader: 'babel-loader',
        options: {
          babelrc: false,
          cacheDirectory: true,
          presets: [
            ['env', {
              targets: {
                node: true,
              },
              debug: true,
            }]
          ],
          plugins: [
            'add-module-exports',
            'transform-class-properties',
            'transform-object-rest-spread',
            ['transform-prejss', {
              namespace: 'prejss',
              config: {
                options: {
                  parser: sugarss,
                },
                plugins: [
                  'postcss-nested',
                ]
              }
            }]
          ]
        }
      },
    ]
  },
]
```

**styles\index.cssm.js**
```ES6
import { ddd } from './jj.js'
import file from './Transparent.gif'

const sss = prejss`
.color
	color: red
`

const $ = Object.assign({}, {
	'.menu': {
		color: 'red',
		fontSize: '11px',
		//content: file,
	}
})

export default $
```

**The cmd.exe:**
![image](https://user-images.githubusercontent.com/2406951/26961266-305528b8-4ce6-11e7-9f46-48295f6b1098.png)

**The fist error in browser after compile:**
![image](https://user-images.githubusercontent.com/2406951/26961219-d1b7ae48-4ce5-11e7-96aa-543a594cd000.png)

**The second error:**
![image](https://user-images.githubusercontent.com/2406951/26961234-ee964fe2-4ce5-11e7-8776-0a1741a30a4b.png)

**Expected behavior:**
Imported `file` should be processed by webpack with `file-loader` and finally contain a string.

**Comment by michael-ciniawsky** [comment]
Your first example looks sane, the second not _sooo_ tbh :), you're are using postcss twice there, one in `prejss` (`babel-loader`) and then again in `postcss-loader`. As you can see from the Error log,  it already fails in `babel-loader` (`babylon` is the babel parser :)). Where is the GIF actually used, what is the usecase/goal?

**Comment by sukazavr** [comment]
@michael-ciniawsky thank you for reactive answer :-)
The goal is to reach opportunity of use CSS in JS with sugar CSS syntax. I've chosen `prejss` to have ability write in SugarSS which will be transpiled in CSSinJS (object), then this object will be transpiled into pure CSS. So, in that way, I'll get transparent JS-modules and CSS Modules, code reuse, and that is all without the runtime overhead.

**Comment by sukazavr** [comment]
The problem is that `postcss-loader` can't work correctly, even if I have removed `transform-prejss` from babel config.

**Comment by TrySound** [comment]
@sukazavr postcss-loader works correctly. But `postcss-js` requires js object value, not string with `module.exports = {}`. Look at val-loader

**Comment by sukazavr** [comment]
I've found a point:
https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L106-L110
```
    // Loader Exec (Deprecated)
    // https://webpack.js.org/api/loaders/#deprecated-context-properties
    if (options.parser === 'postcss-js') {
      css = this.exec(css, this.resource)
    }
```
Anyone who is interesting in subject, look this: [Loader.exec method does not eval loaders
](https://github.com/webpack/webpack/issues/667)

**Comment by sukazavr** [comment]
I've found a temporary solution in use `value-loader` with `raw-loader`.
It's not elegant, but it works even with webpack 2 treeshaking :-)
Now my config looks like this:
```
[
  'raw-loader',
  {
    loader: 'postcss-loader',
    options: {
      parser: 'postcss-js',
      plugins: (loader) => [
        autoprefixer({ browsers: browserslist }),
      ]
    }
  },
  'raw-loader',
  {
    loader: 'value-loader',
    options: {
      name: 'default',
    }
  },
  {
    loader: 'babel-loader',
    options: {
      babelrc: false,
      cacheDirectory: true,
      presets: [
        ['env', {
          targets: {
            node: true,
          },
          debug: true,
          modules: false,
        }]
      ],
      plugins: [
        'transform-class-properties',
        'transform-object-rest-spread',
        ['transform-prejss', {
          namespace: 'prejss',
          config: {
            options: {
              parser: sugarss,
            },
            plugins: [
              'postcss-nested',
            ]
          }
        }]
      ]
    }
  },
]
```

**Comment by michael-ciniawsky** [comment]
You can eventually drop the (last) `raw-loader` after `postcss-loader` since `postcss-loader` exports a module by default in case it's the last loader in the chain :)
