### ISSUE TITLE
postcss-apply doesn't work with @2.0.0

### ISSUE THREAD

**Issue by ZeroCho** [postcss/postcss-loader#256]
After upgrading from 1.3.3 to 2.0.5
postcss-apply doesn't work.

I'm using postcss-apply@0.8.0 and postcss-cssnext@2.11.0
Is this intended? I heard that postcss-apply may be dropped.

**Comment by michael-ciniawsky** [comment]
I need your config please, `postcss-cssnext`still doesn't support PostCSS v6.0.0 which is used by  `postcss-loader >= 2.0.0`. `postcss-apply` should have gotten an update for PostCSS v6.0.0 recently, please check if you have the latest version

**Comment by ZeroCho** [comment]
```
const path = require('path');

module.exports = {
  plugins: {
    'postcss-import': {
      path: path.join(__dirname, '..', 'app', 'css'),
    },
    'postcss-cssnext': {
      browsers: ['> 1%', 'last 2 versions'],
    },
    'postcss-browser-reporter': {},
  },
};
```

I checked that everything is the latest version.
One thing is that `postcss-cssnext` has `postcss-apply@0.3.0` as a dependencies, which is a bit old, so I overrided it by installing `postcss-apply@0.8.0`

**Comment by michael-ciniawsky** [comment]
`postcss-nesting` in `postcss-cssnext`) for instance is also not compatible with PostCSS 6 `postcss-loader` yet. For `postcss-cssnext` usage you will have to wait for compatible release of the plugin sry :)
