### ISSUE TITLE
[3.0.0] (Discussion) make `postcss.config.js` mandatory 

### ISSUE THREAD

**Issue by michael-ciniawsky** [postcss/postcss-loader#258]

**Comment by evilebottnawi** [comment]
@TrySound friendly ping

**Comment by TrySound** [comment]
I don't think it's a good idea. Fragmenting config sometimes feels like abuse. Such behavior will confuse folks. Gulp postcss have both ways afaik.

**Comment by evilebottnawi** [comment]
@TrySound now we have problems to determinate when we should load config when not https://github.com/postcss/postcss-loader/pull/234. I can't found best way for this. Now i use fork this loader because it is really problems in many projects.

**Comment by TrySound** [comment]
Just add priority in options over config. Without merging. It's simplest and bulletproof way.

**Comment by evilebottnawi** [comment]
@TrySound i.e. if we have don't have `config` we load options, if we have `config` we load config?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky Also we have problems with `ident`, we should documentation this :disappointed:

**Comment by michael-ciniawsky** [comment]
The current way is `webpack.config.js` (explicit) > `postcss.config.js` (implicit) > Error, which should stay as is imho. Since `postcss.config.js` doesn't support any webpack specific props and never will be, we need to have a few ugly checks 😛 . The main problem is the buggy `ident` atm 
it worked fine in `webpack = v2.2.0`  and started to bug again around  `v2.4.0+`

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can we found issue or create about this, because it is very important problem. Let's finish today https://github.com/postcss/postcss-loader/pull/234 and do release :+1:

**Comment by TrySound** [comment]
What is `ident` thing? Didin't find even in source code.

**Comment by michael-ciniawsky** [comment]
**webpack.config.js**
```js
{
   loader: 'blabla'
   options: {
     ident: 'whatever',  // mandantory in webpack =< 2.2.0 when using
     function: (blub) => require(blub) // <= a 'Complex Option' (`{Function}` || `require()`) 
  }
}
```

To stringify the `request`

**Comment by andy-j-d** [comment]
Upgrading from Webpack 1 to 3, I was getting "Module build failed: TypeError: Cannot read property 'postcss' of null"

Adding an `ident` option fixed it.

Ended up with 
```
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss-ident',
    plugins: () => [
      require('postcss-nested'),
      require('postcss-import'),
      require('postcss-simple-vars'),
      require('postcss-calc')(),
      require('postcss-color-function')(),
      require('autoprefixer')({ browsers: ['last 2 versions'] }),
    ],
  },
},
```

**Comment by barraponto** [comment]
[Neutrino](https://neutrino.js.org) is a Webpack-wrapper which allows presets to be added and edited to make project setup easier. The [neutrino-postcss-preset](https://github.com/barraponto/neutrino-preset-postcss-cssnext) is designed to ship with a configuration in-code, without relying on any `postcss.config.js`.

**Comment by michael-ciniawsky** [comment]
I'm closigf this for now and instead, add the `ident` back to the docs, it would affect too many builds to be a sufficient fix, maybe I can fix it in webpack in the long run :)
