### ISSUE TITLE
docs(README): add loader description

### ISSUE THREAD

**Issue by gregjacobs** [postcss/postcss-loader#261]
Hey guys. It's great that you have all kinds of documentation on configurations and different things, but what does this loader do exactly? How about a quick description on the top of the readme file?

**Comment by michael-ciniawsky** [comment]
Yep we should add one, there is already a bad one imho https://raw.githubusercontent.com/postcss/postcss-loader/master/README.md (comment after the heading block) 😛. Any sugesstions ?
