### ISSUE TITLE
Add `webpack` as peerDeps and allow v2 and v3

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-loader#263]
@michael-ciniawsky

**Comment by TrySound** [comment]
@evilebottnawi Why restrict version? To anger user with noise messages on webpack 4 and 5 release?

**Comment by TrySound** [comment]
Peer warnings are really useless and noisy IMHO.

**Comment by evilebottnawi** [comment]
@TrySound hm, why other people use `peerDeps`, maybe if `webpack` v4 shipped and have incompatibility (with peerDeps it is break semver idea for safe deps)

**Comment by TrySound** [comment]
Maybe. But specifying all compatible version can be painful with betas at least which don't seem work with ranges.

**Comment by TrySound** [comment]
All problems was with webpack 2 prereleases.

**Comment by michael-ciniawsky** [comment]
It's the recommended way in `webpack-contrib` to handle it, but I don't _really_ 'like' the `peerDependency` pattern, as @TrySound already mentioned it can be really noisy and is basically useless if you go ahead anyways 😛 and in the worst case misleading if you follow and everything is still fine e.g `webpack v2.0.0 => v3.0.0` in most cases. `postcss-loader` also doesn't use `postcss` as a `peerDependency` for the same reason. Better maintain the loader as good && fast as possible, cut a branch and release a major, when breaking changes occur. The v1 branch is still in 'maintenance mode' here for e.g. If a `peerDependency` of `webpack >= 2.0.0` (specifing the minimum only) works with `webpack >= v3.0.0`, we could/should add it, nothing wrong about that. But `peerDependency` ranges like `^2.0.0 || ^2.0.0-rc.0 || ^3.0.0-beta.0  || ^3.0.0-rc.0  || ^3.0.0` are bad

**Comment by evilebottnawi** [comment]
@michael-ciniawsky we can avoid all `beta`, `rc` and etc. Because it is not stable and noise in this case is normal

**Comment by TrySound** [comment]
Don't know current behavior but previously such noises broke my deploy.

**Comment by evilebottnawi** [comment]
@TrySound @michael-ciniawsky we can use `webpack-default` strategy here or let it be as it is. What is our decision?

**Comment by michael-ciniawsky** [comment]
Let it be for now, but if `webpack-contrib` is in better shape and the workflow works, we could/should align with `webpack-contrib` imho.

**Comment by evilebottnawi** [comment]
I think we can close this issue, if necessary in the future we will reopen it. Let's leave it at that.

**Comment by jcrben** [comment]
Disappointed that no peerDependency is documented. It's really better to figure out what versions of webpack you support - you depend upon their API.
