### ISSUE TITLE
[2.0.6] previous loader's `sourceMap: false` option still causes warning

### ISSUE THREAD

**Issue by KagamiChan** [postcss/postcss-loader#264]
Hi I'm using vue and less in my project, and use less-loader@4.0.4 together with postcss-loader. Here's the warning I got from build process

```
WARNING in ./~/css-loader?{"minimize":true,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-3269c29c","scoped":false,"hasInlineConfig":false}!./~/less-loader/dist?{"sourceMap":false}!./~/postcss-loader/lib?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
(Emitted value instead of an instance of Error)
```

It seems to me that setting `sourceMap: false` does not help. How can I figure out if it's less-loader that ignores the option or postcss-loader that emits a false warning? Thank you!

**Comment by evilebottnawi** [comment]
@KagamiChan can your provide minimal reproducible test repo?

**Comment by KagamiChan** [comment]
@evilebottnawi Sorry I forgot that.
For now I can give a repo for reproduce this:
https://github.com/KagamiChan/postcss-loader-demo

Have to say it is not quite minimal because it was created upon vue-cli webpack template, but I try to limit my own changes: https://github.com/KagamiChan/postcss-loader-demo/commit/c19ef7a1df568fcece5aa97727c8f97eb37fe584

when running `npm run dev` there'll be 2 warnings, the latter one is what I want to resolve.

```
 WARNING  Compiled with 2 warnings                                                                                   17:52:20

 warning  in ./src/components/Hello.vue

(Emitted value instead of an instance of Error)

 ⚠️  PostCSS Loader

Previous source map found, but options.sourceMap isn't set.
In this case the loader will discard the source map entirely for performance reasons.
See https://github.com/postcss/postcss-loader#sourcemap for more information.



 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-25bba16e","scoped":true,"hasInlineConfig":false}!./~/postcss-loader/lib?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Hello.vue 4:14-395 13:3-17:5 14:22-403
 @ ./src/components/Hello.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 warning  in ./src/App.vue

(Emitted value instead of an instance of Error)

 ⚠️  PostCSS Loader

Previous source map found, but options.sourceMap isn't set.
In this case the loader will discard the source map entirely for performance reasons.
See https://github.com/postcss/postcss-loader#sourcemap for more information.



 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7cf643c8","scoped":false,"hasInlineConfig":false}!./~/less-loader/dist?{"sourceMap":false}!./~/postcss-loader/lib?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-446 13:3-17:5 14:22-454
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

I you want a simpler repro, I'll try something from scratch.

**Comment by evilebottnawi** [comment]
@KagamiChan try to rename `.postcssrc.js` to `postcss.config.js`, maybe a problem in loading the configuration file

**Comment by evilebottnawi** [comment]
@KagamiChan sorry, misunderstood, your got this warning because some loader before `postcss-loader` generate source map.

**Comment by KagamiChan** [comment]
@evilebottnawi Thank you for investigating this. So setting `sourceMap` to `false` for other loaders prior to `postcss-loader` does not mean that the source map will be dropped before flowing into `postcss-loader`? I'm not quite sure for that.

If it is the case, this issue can be closed.

**Comment by evilebottnawi** [comment]
@KagamiChan Info:
RemainingRequest - `/home/evilebottnawi/IdeaProjects/postcss-loader-demo/node_modules/vue-loader/lib/selector.js?type=styles&index=0!/home/evilebottnawi/IdeaProjects/postcss-loader-demo/src/App.vue`
Loaders:
```
[ { path: '/home/evilebottnawi/IdeaProjects/postcss-loader-demo/node_modules/css-loader/index.js',
    query: '?{"minimize":false,"sourceMap":false}',
    options: '{"minimize":false,"sourceMap":false}',
    ident: undefined,
    normal: [Function],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: false,
    request: [Getter/Setter] },
  { path: '/home/evilebottnawi/IdeaProjects/postcss-loader-demo/node_modules/vue-loader/lib/style-compiler/index.js',
    query: '?{"vue":true,"id":"data-v-7cf643c8","scoped":false,"hasInlineConfig":false}',
    options: '{"vue":true,"id":"data-v-7cf643c8","scoped":false,"hasInlineConfig":false}',
    ident: undefined,
    normal: [Function],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: false,
    request: [Getter/Setter] },
  { path: '/home/evilebottnawi/IdeaProjects/postcss-loader-demo/node_modules/less-loader/dist/index.js',
    query: '?{"sourceMap":false}',
    options: '{"sourceMap":false}',
    ident: undefined,
    normal: [Function: lessLoader],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: false,
    request: [Getter/Setter] },
  { path: '/home/evilebottnawi/IdeaProjects/postcss-loader-demo/node_modules/postcss-loader/lib/index.js',
    query: '?{"sourceMap":false}',
    options: '{"sourceMap":false}',
    ident: undefined,
    normal: [Function: loader],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: true,
    request: [Getter/Setter] },
  { path: '/home/evilebottnawi/IdeaProjects/postcss-loader-demo/node_modules/vue-loader/lib/selector.js',
    query: '?type=styles&index=0',
    options: 'type=styles&index=0',
    ident: undefined,
    normal: [Function],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: true,
    request: [Getter/Setter] } ]
```

Seems before `postcss-loader` we have `vue-loader`, which generate source maps. I am not familiar with `vue-loader`, seems your need set source Map false for this.

**Comment by evilebottnawi** [comment]
@KagamiChan  yep, your should set `sourceMap: false` for each loader

**Comment by KagamiChan** [comment]
I'm using postcss alone bacause vue-loader only handles `.vue` files and I have some other css files. 

The style-compiler in vue-loader [in fact uses postcss and also reads the postcss config file](https://github.com/vuejs/vue-loader/blob/master/lib/style-compiler/index.js), but setting sourceMap option in `.postcssrc.js` (also tried renaming to `postcss.config.js`) or in build config cannot remove the warning.

**Comment by KagamiChan** [comment]
Anyway I think postcss-loader is working fine, I'm looking into vue-loader, closing this.

**Comment by KagamiChan** [comment]
@evilebottnawi I manage to prevent vue-loader from producing source map by changing its code, but the warning persists. Seems I should look into less-loader instead

**Comment by yoyo837** [comment]
Maybe it's the same thing. I'm not sure ，#248

**Comment by adi518** [comment]
Such an annoying bug. I have the same issue as @KagamiChan.
