### ISSUE TITLE
"Module not found" when using glob

### ISSUE THREAD

**Issue by dan-gamble** [postcss/postcss-loader#266]
**Error**:
```
ERROR in ./~/css-loader?{"importLoaders":1}!./~/postcss-loader/lib!./cms_test/assets/css/app.css
Module not found: Error: Can't resolve './base/**/*.css' in '/Users/dangamble/Workspace/cms-test/cms_test/assets/css'
 @ ./~/css-loader?{"importLoaders":1}!./~/postcss-loader/lib!./cms_test/assets/css/app.css 6:10-152
 @ ./cms_test/assets/css/app.css
 @ ./cms_test/assets/main.js
 @ multi webpack-hot-middleware/client?&reload=true ./cms_test/assets/main.js
webpack: Failed to compile.
```

**postcss.config.js**:
```js
module.exports = [
  require('postcss-easy-import'),
]
```

**webpack.config.js**
```js
      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ]
      }
```

**app.css*
```css
@import '~sanitize.css';
@import 'helpers/index.css';
@import 'base/define.css';
@import './base/**/*.css';
```

Really out of ideas with this :(

**Comment by evilebottnawi** [comment]
@dan-gamble seems `postcss-easy-import` use `"postcss": "^5.0.15",`, loader use `postcss` v6, maybe incompatibility?

**Comment by evilebottnawi** [comment]
@dan-gamble also can your check `postcss.config.js` is loading, try to `console.log('LOAD'); process.exit()` in postcss config file?

**Comment by dan-gamble** [comment]
```

webpack: Compiling...
webpack building...
LOAD

~/Workspace/cms-test develop* 32m 40s
```

It's getting loaded.

I could try forking `postcss-easy-import` myself and updating it to postcss 6.0 or using `postcss-import` with a glob function to see if that helps?

**Comment by evilebottnawi** [comment]
@dan-gamble try to use, seems your config invalid https://github.com/michael-ciniawsky/postcss-load-config 
```js
module.exports = {
  plugins: {
    'postcss-easy-import': {}
  }
}
```
Without minimal test repo i can not help you anymore

**Comment by dan-gamble** [comment]
Hmm you are right, that's weird. `postcss-load-config` works though so i'll explore that avenue. Thanks @evilebottnawi :)

**Comment by evilebottnawi** [comment]
@dan-gamble My example solved the problem, if so, we can make the configuration validation for the future?
/cc @michael-ciniawsky

**Comment by dan-gamble** [comment]
Changing my `postcss-config.js` to:

```js
module.exports = {
  plugins: {
    'postcss-easy-import': {}
  }
}
```

Fixed it 👍
