### ISSUE TITLE
Warning "Previous source map found, but options.sourceMap isn't set"

### ISSUE THREAD

**Issue by Janaka-Steph** [postcss/postcss-loader#271]
Hello,

Despite all my efforts, I can't get rid of the warning "Previous source map found, but options.sourceMap isn't set"

Some packages I have:
- babel-plugin-react-css-modules: 3.0.0
- bootstrap: 4.0.0-alpha.6
- bootstrap-loader: 2.1.0
- node-sass: 4.5.3
- postcss-loader: 2.0.6
- postcss-scss: 1.0.1
- precss: 1.4.0
- sass-loader: 6.0.6
- webpack: 2.6.1
- webpack-dev-server: 2.5.0

My webpack.config.js : https://pastebin.com/QgLGNUbH
My webpack.bootsrap.config.js : https://pastebin.com/X9H0CTv6
My postcss.config.js : https://pastebin.com/a5grb2qx
My .bootstraprc : https://pastebin.com/NVq8Ne4J

The github repo : https://github.com/asseth/dao1901

I mention `disableSassSourceMap: true` in the .bootstraprc but it has no effect on the warnings.

Thank you for your help

**Comment by michael-ciniawsky** [comment]
```
postcss-scss: 1.0.1
precss: 1.4.0
```

You won't need them when using SASS (`sass-loader`) itself, the former is for stylelint (syntax) and the latter is mimicking SASS for folks who want to use PostCSS standalone, either remove `sass-loader` or remove those two 

```
 babel-plugin-react-css-modules: 3.0.0
```

I perosnally never used it myself but if you have 

```js
{
  loader: 'css-loader' 
  options: { modules: true }
}
```


you won't need ot either. It's another way to use CSS Modules, both in the same config won't make much sense and I recommend using `css-loader` 

As stated on gitter I also would simply use a a CDN link for vendor CSS libs instead of such madness loaders like `boostrap-loader`, webpack doesn't shine on this (Global CSS) in general

**style.css**
```css
.title {
  font-size: 3rem;
}
```

**component.js**
```js
import React from 'react'

import $ from './style.css'

export default (props) => (
   <div className='container'> // Bootstrap CSS (Global)
       <h1 className={$.title}>{props.title}</h1> // Custom CSS (Local)
   </div>
) 
```

I take a a deeper look at `bootstrap-loader` when time, please try by remove it and notify when your you get a working build  without it :)

**Comment by Janaka-Steph** [comment]
If I remove all things related to bootstrap, but not the rest, and import bootstrap from CDN, then I don't have the warnings anymore, but now it doesn't load my custom styles. :-(

**Comment by kishorevarma** [comment]
Hi, 

I have a similar issue, even though I set the soureMap true in config.
```
module.exports = {
  sourceMap: true,
  plugins: [require('autoprefixer')]
};
```

I have tried to debug issue. I think we are not checking sourceMap option from config file.

**Comment by michael-ciniawsky** [comment]
@kishorevarma `sourceMap` isn't supported by `postcss.config.js`, you need to add it to `webpack.config.js` instead. The separate config only supports PostCSS related Options && Plugins to work across the different PostCSS runners (CLI, gulp, ...) seemlessly. `sourceMap` is webpack specific and therefore => `webpack.config.js`

**postcss.config.js**
```diff
module.exports = {
- sourceMap: true,
  plugins: [require('autoprefixer')]
};
```

**webpack.config.js**
```diff
{
   loader: 'postcss-loader'
+  options: { sourceMap: true }
}
```

@Janaka-Steph I can only recommend to **skip** frameworks like `bootstrap` when using webpack, the component based archictecture isn't well suited for CSS frameworks in general
On attempt (i wasn'T too 'lucky' with either) is to `require()/import` bootstrap in  the app entry `App.js` 

**boostrap.scss**
```css
/* Individualize (S)CSS here */
@import bootstrap/../...scss;
...
...
```

**App.js**
``` js
import React from 'react'

// Only imported once in the entry 
import 'boostrap.scss'
import $ from 'style.scss'

// => Component [index.js, style.scss, ...assets]
import Component from './components/component' 
...

class App extends React.Component {
   render () {
     return (
        <div className="container">
           <Component />
        </div>
     )
   }
}
```

> ⚠️  You will need the `extract-text-webpack-plugin` in production then, since the whole `bootstrap` blob is in the JS otherwise :)

In any case, just the compare `<link href="path/to/boostrap.min.css">` to **hunderds of lines**  for requiring a CSS file like `boostrap-loader` does atm. Not to black-mouth the `bootstrap-loader` in particular here, there is simply no straightforward way to do it, but the approach is off in general imho :). I also couldn't find the section where `postcss-loader` is required by `boostrap-loader` tbh, so please open an issue there if you intend to use the loader nevertheless 😛

**Comment by Janaka-Steph** [comment]
I agree that requiring Bootstrap from the CDN is much simpler but then we loose the scss bootstrap variables..

**Comment by kishorevarma** [comment]
thanks @michael-ciniawsky
