### ISSUE TITLE
postcss not working in webpack

### ISSUE THREAD

**Issue by ir-fuel** [postcss/postcss-loader#276]
I am using webpack 3
This is my config

```
      {
        test: /\.css$/,
        exclude: /node_modules/,
        include: path.join(__dirname, 'client'),
        use: ['style-loader','css-loader',{
          loader:'postcss-loader',
          options: {
            config: {
                  path: path.join(__dirname, 'postcss.config.js')
                }
          }
        }]
      },
```

To make sure it actually picks up the config I put this in the `postcss.config.js` file
```
module.exports = {
  ]wepfowewepjwegpjo
  parser: 'sugarss',
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {},
    'autoprefixer': {},
    'postcss-focus': {},
    'postcss-nested': {},
    'postcss-url': {},
    'cssnano': {}
  }
}
```

This should never work as it isn't valid syntax.

The problem is it doesn't even throw an error when running webpack. The config file is located in the project root btw.

My css files are in `client/css` and when looking inside `bundle.js` I can see 
```
exports.push([module.i, ":root {\n  --brand: #EB7C5C;\n  --text: #424242 ....
```

Which is the contents of my `style.css` file, so it does get picked up.

The styles are added to my `index.jsx` file as follows:

```
import './css/flexboxgrid.css'
import './css/font-awesome.css'
import './css/style.css'
```

Any idea what I am missing?

**Comment by michael-ciniawsky** [comment]
[postcss-load-config #91](https://github.com/michael-ciniawsky/postcss-load-config/issues/91) Tracking Issue (`schema-validation`). It should warn about incorrect config via `postcss-load-config`.

**Comment by michael-ciniawsky** [comment]
It will fallback to `{ plugins: [], options: {} }` and simply not run any PostCSS transforms atm
