### ISSUE TITLE
postcss-loader-before-processing missing

### ISSUE THREAD

**Issue by naBausch** [postcss/postcss-loader#278]
Hi 

was `postcss-loader-before-processing` removed?
I am using a postcss plugin which requires access to the current webpack compiler and used `postcss-loader-before-processing` to connect both parts.

With the current version it doesn't work anymore.

Thanks :)

**Comment by michael-ciniawsky** [comment]
Yep, it was removed in `postcss-loader >= v2.0.0`, because it was widely used and the Loader API accessing the webpack `compilation` from inside a loader directly is officially deprecated. What is the usecase, could you provide more info? :)

**Comment by naBausch** [comment]
Oh too bad I am using https://github.com/jantimon/iconfont-webpack-plugin and without the `postcss-loader-before-processing` the `iconfont-webpack-plugin` doesn't work anymore :/

**Comment by jantimon** [comment]
@michael-ciniawsky the current implementation of the iconfont-webpack-plugin is using the compiler to resolve the filename of `url(demo.svg)`.

According to the official documentation there would be a new api for that which is not deprecated:
https://webpack.js.org/api/loaders/#this-resolve
```js
resolve(context: string, request: string, callback: function(err, result: string))
```

Can you think of a clean way to pass `this` from the your loader to a postcss plugin?

**Comment by jantimon** [comment]
@naBausch just released a new version which works with postcss-loader 2.x
I guess this issue can be closed

**Comment by michael-ciniawsky** [comment]
@jantimon Thx
