### ISSUE TITLE
docs(README): clearify custom parser usage in examples

### ISSUE THREAD

**Issue by Rufflewind** [postcss/postcss-loader#280]
I was kind of expecting a sensible default configuration that works on plain CSS – the whole reason I'm using postcss is for cssnext.  The one in the README file suggested sugarss as the default "parser", which I assumed was just a standard CSS parser implementation, or at the worst nothing more than an extension to standard CSS syntax like Less or Sass.

But no, I later learned that sugarss is a completely different language of its own and will reject even the simplest CSS code like `p { }`, so I wasted hours trying to understand why the webpack pipeline couldn't accept a normal CSS file even with the most minimal “default” configuration:

```
ERROR in ./test.css
Module build failed: Syntax Error 

(1:3) Unnecessary curly bracket

> 1 | p {
    |   ^
  2 |     color: red;
  3 | }
```

In the end, `test/fixtures/postcss.config.js` helped me understand what was going on, whereas the README file was very misleading.

I suggest either:

- remove sugarss from the default configuration, leaving a note that it could be used if desired, or
- warn the reader who may not be familiar with sugarss that it is an completely different syntax for CSS and should be left undefined if the user wants to use standard CSS.

**Comment by michael-ciniawsky** [comment]
The examples main purpose is to just show **if** you want to use a **custom** parser how this looks like/works. It uses a conditional to clearify `file.extname !== .css` ? 'custom' :  'default'` this

```
file.extname === '.sss' ? 'sugarss' : false,
```

**Comment by Rufflewind** [comment]
The conditional is not present in the very first example:

```
module.exports = {
  parser: 'sugarss',
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {},
    'autoprefixer': {},
    'cssnano': {}
  }
}
```

All it needs is a short explanation of what `parser: sugarss` is for, e.g. `// enables sugarss syntax instead of standard CSS`.

**Comment by michael-ciniawsky** [comment]
Yep agreed, I will add a note when I update the docs with the other docs related nits currently in the issue tracker
