### ISSUE TITLE
refactor: handle loader errors gracefully in watch mode

### ISSUE THREAD

**Issue by cihadturhan** [postcss/postcss-loader#285]
If you have an error (e.g. sytax error), webpack shows me the following call stack

```
    at runLoaders (...\node_modules\webpack\lib\NormalModule.js:194:19)
    at ...\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at ...\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (...\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (...\node_modules\postcss-loader\lib\index.js:176:44)
    at <anonymous>
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js??ref--5-3!src/app.css:
```
and says 
`webpack: Failed to compile.`

After that point, fixing your error doesn't trigger your watcher. You have to restart webpack dev server and this could be frustrating.

Is there any solution?
Thanks in advance

---
Edit: Plugins and stack
```json
{
    "lost": "^8.2.0",
    "postcss": "^6.0.9",
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-mixins": "^6.1.0",
    "postcss-normalize": "^4.0.0",
    "postcss-nested": "^2.1.2",
    "postcss-reporter": "^5.0.0",
}
```
Webpack 3.5.5 on Windows 10

**Comment by michael-ciniawsky** [comment]
Does this only happen for `postcss-loader` errors? The loader uses standard webpack error handling, not sure what we can do here

**Comment by cihadturhan** [comment]
@michael-ciniawsky I'm using [postcss/postcss-mixins](/postcss/postcss-mixins) and I was redirected to here. Gotta check some other syntax errors if same problem exists. 
See https://github.com/postcss/postcss-loader/issues/285
