### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'postcss' of null

### ISSUE THREAD

**Issue by jinker** [postcss/postcss-loader#287]
const autoprefixer = require('autoprefixer');
    const autoprefixerCall = autoprefixer({ browsers: ['last 15 versions'] });

    const postCssLoader = {
        loader: 'postcss-loader',
        options: {
            sourceMap: true,
            plugins: [
                autoprefixerCall
            ],
            config: {
                // path: path.resolve(__dirname, './postcss.config.js')
            }
        }
    };

**Comment by michael-ciniawsky** [comment]
**webpack.config.js**
```js
{
  loader: 'postcss-loader',
  options: {
    sourceMap: true,
    ident: 'postcss' // <= this line 
    plugins: [
       require('autoprefixer')(...options)
    ]
  }
}
```

> ⚠️  Either use `options.config` or `options.plugins` but not **both** 


Reopen if still regressions :)

**Comment by jinker** [comment]
Thanks!
But why the option `ident ` is not in the doc.

**Comment by michael-ciniawsky** [comment]
#272 Feel free to send PR I just hadn't the time to do it until now and it worked without it (`ident`) in `webpack v2.2.1 =< v2.6.0` with v2.6.0+ introducing a bug 😞
