### ISSUE TITLE
postcss config validation

### ISSUE THREAD

**Issue by iroy2000** [postcss/postcss-loader#291]
Hi all, 

Is there any issues with my config for the postcss ??

```
{
  test: /\.css$/,
  use: [
    {
      loader: 'style-loader',
    },
    {
      loader: 'css-loader',
      options: { sourceMap: true, importLoaders: 1 }
    },
    {
      loader: 'postcss-loader',
      options: {
        sourceMap: true,
        // https://github.com/postcss/postcss-loader/issues/92
        // https://github.com/postcss/postcss-loader/issues/8
        plugins: () => [
          precss(),
          postcssImport({ addDependencyTo: webpack }),
          postcssNested(),
          postcssCssnext({
            browsers: ['last 2 versions', 'ie >= 9'],
            compress: true,
          }),
        ],
      },
    },
  ],
}
```

The hotloading feature doesn't work, I know I have to put that to the **first line** of the plugin, but if I put before the precss, I got an compilation error

![screen shot 2017-09-21 at 5 41 13 pm](https://user-images.githubusercontent.com/487520/30724638-1e1aeeb6-9ef4-11e7-8188-85f7285d3dec.png)

You can reproduce the issue in this repo

https://github.com/iroy2000/react-redux-boilerplate .

**Comment by michael-ciniawsky** [comment]
```diff
{
      loader: 'postcss-loader',
      options: {
+       ident: 'postcss', // <= This line (fix)
        sourceMap: true,
        // https://github.com/postcss/postcss-loader/issues/92
        // https://github.com/postcss/postcss-loader/issues/8
        plugins: () => [
-          precss(), // deprecated, unmaintained (additionally)
-          postcssImport({ addDependencyTo: webpack }), // @import is handled by `css-loader` (additionally)
          postcssCssnext({
            browsers: ['last 2 versions', 'ie >= 9'],
            compress: true,
          }),
        ],
      }
```

**Comment by iroy2000** [comment]
Actually it doesn't seem fixing my problem, I still see the same thing 

```javascript
{
  test: /\.css$/,
  use: [
    {
      loader: 'style-loader',
    },
    {
      loader: 'css-loader',
      options: { sourceMap: true, importLoaders: 1 }
    },
    {
      loader: 'postcss-loader',
      options: {
        ident: 'postcss',
        sourceMap: true,
        // https://github.com/postcss/postcss-loader/issues/92
        // https://github.com/postcss/postcss-loader/issues/8
        plugins: () => [
          postcssCssnext({
            browsers: ['last 2 versions', 'ie >= 9'],
            compress: true,
          }),
        ],
      },
    },
  ],
}
```

And @michael-ciniawsky , did you get this working with this ---> https://github.com/iroy2000/react-redux-boilerplate ?

**Comment by michael-ciniawsky** [comment]
The warning you get is bc 'postcss-import' is unable to find/resolve `configs/color`, the path seems to be simply incorrect. In your boilerplate you use `precss (Includes a nesting plugin), postcss-nested (dito) && cssnext (Includes a nesting plugin aswell)`, so you definitely should choose **one** nesting solution. PreCSS && CSSNext are just wrappers around PostCSS Plugins. The same goes for `cssnext`, check their `package.json` for plugin duplicates. Also if you really want to use `postcss-import` (it will cause duplicates in your bundle) then use it as the **first** plugin and **not** after `precss` && `postcss-nested`

**Comment by iroy2000** [comment]
Thanks, that helps a lot.

**Comment by michael-ciniawsky** [comment]
`postcss-partial-import` supports `_partial.css` (SASS) import style to my knowledge, but... 
as long as you don't 💯  need to migrate a SASS code base to PostCSS free yourself from SASS conventions whenever possible as you won't really need them anymore 😛
