### ISSUE TITLE
Wired PostCSS loader output

### ISSUE THREAD

**Issue by iroy2000** [postcss/postcss-loader#292]
Hi,

I'm using `"postcss-loader": "^2.0.6" ` with the following postcss plugins, and I'm having weird post css loader output

```
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^11.0.0",
    "postcss-nested": "^2.1.2",
    "precss": "^2.0.0",
```

```
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--6-2!node_modules/postcss-loader/lib/index.js??ref--6-3!src/style/index.css:
       [0] ./node_modules/css-loader?{"sourceMap":true,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"plugins":[null,{"version":"6.0.11","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"precss","postcssVersion":"6.0.11"},null,{"version":"6.0.11","plugins":
[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"6.0.11"}]}!./src/style/index.css 825 bytes {0} [built]
```

Is there compatible issues?  Or it might be my webpack config ?

The following is my webpack config

```
{
  test: /\.css$/,
  use: ExtractTextPlugin.extract({
    fallback: "style-loader",
    use: [
      {
        loader: 'css-loader',
        options: { sourceMap: true, importLoaders: 1 }
      },
      {
        loader: 'postcss-loader',
        options: {
          sourceMap: true,
          plugins: () => [
            postcssImport({ addDependencyTo: webpack }),
            precss(),
            postcssNested(),
            postcssCssnext({
              browsers: ['last 2 versions', 'ie >= 9'],
              compress: true,
            }),
          ],
        },
      }
    ]
  })
}
```

Thanks in advance for any help.

**Comment by michael-ciniawsky** [comment]
What do you exactly mean by 'weird' ?  The `[null,null,null,null,null,null,null,null,null,null,null,null,null...` stuff? Hard to believe at first but this is 'correct' and has to do with webpack internals nothing to worry about here. Check the `bundle.css` file for incorrect CSS, use a small setup (1-2 files) at best

**Comment by iroy2000** [comment]
Yes, I'm talking about the `[null,null,null,null,null,null,null,null,null,null,null,null,null, ....`

I check the css output, it seems correct.  I thought that was a bug, but not sure if anyone has that issues also.

**Comment by michael-ciniawsky** [comment]
It always appears like that, bc webpack uses a query string like syntax (JSON) `postcss-loader?[options]./path/to/file.css` internally an needs to handle `{Function}` options with additional logic to stringify them and keep the reference. The `{Function}` name is lost during this process and it simply displays `null` as the name per `{Function}` ¯\_(ツ)_/¯

**Comment by meyer** [comment]
@michael-ciniawsky sorry to resurrect an old issue, but should this issue be forwarded to the webpack issue tracker? I found this page by googling `postcss-loader "null,null,null,null,null"`.
