### ISSUE TITLE
Error: No PostCSS Config found in node_modules/...

### ISSUE THREAD

**Issue by GiancarlosIO** [postcss/postcss-loader#293]
`"postcss-loader": "^2.0.6"`
`"webpack": "^2.2.0"`

When a file from "node_modules/my_module/src/file.js" has a:
`import 'react-infinite-calendar/styles.css'
`
I get this error:
![captura de pantalla de 2017-09-25 18-08-59](https://user-images.githubusercontent.com/17274950/30835244-fa5ba5c0-a21c-11e7-9627-423f5acd796b.png)

my postcss.config.js:
`module.exports = {
    plugins: [
        require('autoprefixer')({ /* ...options */ })
    ]
}`

and my webpack.config.js
![captura de pantalla de 2017-09-25 18-18-04](https://user-images.githubusercontent.com/17274950/30835357-7ee34f32-a21d-11e7-8c4f-e147a2f90844.png)

however when i add the inline config for postcss-loader it works:
![captura de pantalla de 2017-09-25 18-27-04](https://user-images.githubusercontent.com/17274950/30835634-c4a097b8-a21e-11e7-9f41-d07365172f31.png)

so i think postcss-loader is not working with my postcss.config.js.

Thanks for advanced!

**Comment by michael-ciniawsky** [comment]
Where is your `postcss.config.js` located in the file tree? Could you show `tree $PROJECT` please. Config lookup starts from `dirname(file)` upwards by default and something like e.g 

```
|– node_modules
| |– package
| | |– style.css
|
|– postcss.config.js
|– webpack.config.js
```

should normally work. 

Otherwise either set Plugins/Options directly `webpack.config.js` or provide the `config.path`

**webpack.config.js**
```js
{
  loader: 'postcss-loader',
  options: {
    config: { 
      path: 'path/to/postcss.config.js' 
    } 
  }
}
```

**Comment by GiancarlosIO** [comment]
@michael-ciniawsky yep, i have my postcss.config.js in the root directory
![captura de pantalla de 2017-09-26 09-40-22](https://user-images.githubusercontent.com/17274950/30866269-58569b4a-a29e-11e7-9ac2-ec1fe66d109a.png)

**Comment by michael-ciniawsky** [comment]
Could you show the file where you `import/require` the component style + postcss.config.js + webpack.config.js. Do you run webpack via `gulp` ? Any possibility that `postcss-load-config` would need to to move the file tree downwards during config lookup, starting from `dirname(file)` ?

**Comment by GiancarlosIO** [comment]
@michael-ciniawsky 
we create our a custom node-lib
![captura de pantalla de 2017-09-26 10-24-49](https://user-images.githubusercontent.com/17274950/30868561-a2f1415e-a2a4-11e7-971e-603866c10e69.png)

in this file we have, "react-infinite-calendar" is a node_module:
![captura de pantalla de 2017-09-26 10-25-10](https://user-images.githubusercontent.com/17274950/30868585-b69935c2-a2a4-11e7-81c4-6918d02e8331.png)

webpack.config.js
https://gist.github.com/GiancarlosIO/63044ca1ed3e3fb5d8a5421412125290

and we run the webpack with "yarn watch":
`"watch": "ENV=development webpack --watch --progress",`

**Comment by GiancarlosIO** [comment]
using this solve my problem:
`config: { 
      path: 'path/to/postcss.config.js' 
    } `
so I'll close this i think.
