### ISSUE TITLE
sass @for loop does not work korectly

### ISSUE THREAD

**Issue by SerhiiBilyk** [postcss/postcss-loader#296]
Hello, this is my webpack:
...
use:ExtractTextPlugin.extract({
          fallback:'style-loader',
          use:["css-loader","sass-loader",'postcss-loader']
        })
...
If I write this sass loop:
  @for $i from 1 through 3{
    &.x-#{$i}{
        background-image: url('./img/#{$i}.jpg');
    }
  }
I have an error message: Unknown word($i) -> &.x-#{**$i**}

If I remove 'postcss-loader' from webpack config, it works correctly.
Maybe I'm doing something wrong.

**Comment by evilebottnawi** [comment]
@SerhiiBilyk use `["css-loader", 'postcss-loader', 'sass-loader']`

**Comment by SerhiiBilyk** [comment]
d*mn, it works:)
Thank you very much:)!
