### ISSUE TITLE
Possible to pass postcss options?

### ISSUE THREAD

**Issue by at0g** [postcss/postcss-loader#3]
Is it possible to pass postcss options with postcss-loader, such as `{ map: true }`?

I have a very simple stylus file, which creates two media queries (as a contrived example):

```
  @media only screen and (min-width: 321px)
    color lightcyan

  @media only screen and (min-width: 321px)
    font-size 24px
```

my webpack config file looks like this:

webpack.config.js
```
{
    module: {
        loaders: [
            { test: /\.styl$/,loader: 'style-loader!css-loader?sourceMap!postcss-loader!stylus-loader?paths=src' }
        ]
    },

    postcss: {
        defaults: [require('css-mqpacker')]
    }
}
```

When viewing the source map, the file contents shown are _after_ css-mqpacker has run:

```
@media only screen and (min-width: 321px)
    color lightcyan
    font-size 24px
```

If I remove css-mqpacker from the post css defaults, the source map displays both media queries in the stylus file, as per the original source.

I've tried the same with autoprefixer too - it also shows the source file contents after autoprefixer has run and not the actual source.

Any ideas? I'm very new to webpack so my apologies if I've missed something obvious...

**Comment by ai** [comment]
PostCSS has source map autodetect, so here we has problems not with a options.

**Comment by ai** [comment]
Try to move `css-loader?sourceMap` before `postcss-loader` to take source map from Stylus. I think Stylus loader can set source map in wrong way and webpack didn’t see them to pass to PostCSS loader.

**Comment by at0g** [comment]
I tried swapping the order of `css-loader` and `postcss-loader` so that:

```
style-loader!css-loader?sourceMap!postcss-loader
```

becomes:

```
style-loader!postcss-loader!css-loader?sourceMap
```

This caused an error and the module would not build.

I've also tried using a plain old css file instead of stylus, and the source map refers to the output of postcss and not the source file (it's still wrong).

Any other suggestions?

**Comment by MoOx** [comment]
css-loader returns javascript so you can not execute it before any related css stuff.
Your output in sourcemap is weird since it seems to be a mix of stylus / mqpaker (no `{` or `:`).

**Comment by at0g** [comment]
@MoOx - I know totally weird right - one or the other would make more sense.

I tried a different approach here:
https://github.com/at0g/webpack-css-sourcemaps/tree/gulp

This time gulp is being used to preprocess stylus and generate an external sourcemap.
The compiled css then goes to webpack (postcss-loader & css-loader).

In this configuration, **postcss-loader works exactly as expected**, so I'm going to close this issue.

Sorry about the red herring and thanks for the help.

**Comment by boopathi** [comment]
I still face this issue with source-maps. Using extract-text-webpack-plugin, postcss, and sass. 

The input map to postcss-loader is 

```
{ version: 3,
  file: '/Users/boopathi.rajaa/workspace/phrontend/examples/hello-github/styles.scss',
  sources: [ '../styles.scss' ],
  sourcesContent: [],
  mappings: 'AAAA,IAAI,CAAC;EACJ,UAAU,EAAE,KAAM,GADb',
  names: [] }
```

and the output map of `postcss-loader` is 

```
{ _file: 'styles.scss',
  _sourceRoot: null,
  _skipValidation: false,
  _sources:
   { _array: [ '../styles.scss', 'styles.scss' ],
     _set: { '$../styles.scss': 0, '$styles.scss': 1 } },
  _names: { _array: [], _set: {} },
  _mappings:
   { _array: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     _sorted: true,
     _last:
      { generatedLine: 4,
        generatedColumn: 39,
        originalLine: 4,
        originalColumn: 39,
        source: 'styles.scss',
        name: null } },
  _sourcesContents: null }
```

and the file `styles.scss` is empty in browser.

**Comment by ai** [comment]
@boopathi some of libsass versions had a problems with source map. What `node-sass` is used in your build?

**Comment by boopathi** [comment]
node-sass - `3.1.1`

**Comment by ai** [comment]
I found a problem. Your webpack settings made `sourcesContent` empty.

**Comment by ai** [comment]
In Sass and in PostCSS too. So browsers can’t show you anything in `styles.scss`

**Comment by boopathi** [comment]
https://github.com/boopathi/extract-sass-test 

I tried something, and got `sourcesContent` to work from node-sass using this option (https://github.com/boopathi/extract-sass-test/blob/master/sass-loader.js#L9)

Now sourceMap is generated, and the resultant sourceMap file contents match the original sass file, but the sourcemap itself is located in a different location - `webpack:///styles.scss` instead of `webpack:///./styles.scss`.

**Comment by ai** [comment]
@boopathi show me please source map `sources` before PostCSS and after.

**Comment by boopathi** [comment]
Oh. yeah. 
Before: 

```
sources: [ "stdin" ],
sourcesContent: [ "..." ]
```

After: 

```
_sources: { _array: [ 'styles.scss' ], _set: { '$styles.scss': 0 } },
_sourcesContents: { '$styles.scss': '...' }
```

the full output: http://pastebin.com/MA7W0n0V

**Comment by ai** [comment]
@boopathi why you think path should be `webpack:///styles.scss`?

I take file path by `loaderUtils.getRemainingRequest(this)`. What is a best way?
https://github.com/postcss/postcss-loader/blob/master/index.js#L7

Anyway `extract-sass-test` use strange `stdin`. I think you should create a Issue in Sass loader too.

**Comment by boopathi** [comment]
> why you think path should be webpack:///styles.scss?

It should be `webpack:///./styles.scss` instead of `webpack:///styles.scss`.

![screenshot 2015-05-19 16 39 10](https://cloud.githubusercontent.com/assets/294474/7701564/0d20208c-fe46-11e4-840a-ce6b4af7c0ea.png)

The highlighted one (webpack:///./styles.scss) is mapped. The other `styles.scss` (webpack:///styles.scss) contains the original source.

> I take file path by loaderUtils.getRemainingRequest(this)

The output of getRemainingRequest is like this

```
/Users/boopathi.rajaa/workspace/extract-sass-test/echo-loader.js!/Users/boopathi.rajaa/workspace/extract-sass-test/sass-loader.js!/Users/boopathi.rajaa/workspace/extract-sass-test/styles.scss
```

Shouldn't it be just the filename (this.resourcePath) ? But changing it to resourcePath too didn't do any good. The same issue was there.

> Anyway extract-sass-test use strange stdin. I think you should create a Issue in Sass loader too.

@ai yes. But, I still can't figure out properly what the issue is. That's why I'm using a custom sass-loader (https://github.com/boopathi/extract-sass-test/blob/master/sass-loader.js) in `extract-sass-test` - which passes `sourceMapContents`. 

Maybe what the css-loader receives is not proper ? Will experiment more.

**Comment by ai** [comment]
@boopathi I am open for PR :)

**Comment by at0g** [comment]
@boopathi - I think that sass (and stylus) loaders are not generating sourcemaps correctly. 

https://github.com/jtangelder/sass-loader/issues/92

**Comment by boopathi** [comment]
@ai It works!. I overlooked the fact that original source should be available at `webpack://./styles.scss` cuz that's where the actual file is. But the styles are actually mapped to the other one properly, though it didn't happen when using `!sass-loader?sourceMap`. Looks like there is an [option](https://github.com/jtangelder/sass-loader/issues/92#issuecomment-104699279) in `sass-loader` which does export the sourcemap contents that were not available for the `postcss-loader`.

```
css?sourceMap!postcss!sass?sourceMap&sourceMapContents
```
