### ISSUE TITLE
postcss-loader in combination with sass-loader

### ISSUE THREAD

**Issue by duivvv** [postcss/postcss-loader#30]
I have the following setting in my webpack setup

```
loader: ExtractTextPlugin.extract('css!postcss!sass?outputStyle=expanded')
```
but when I use postcss-media-minmax I get node-sass parsing errors.

```
@media only screen and (width > 500px) and (width < 1000px) {
Unclosed parenthesis in media query expression
```

is there a way to make this work together?

**Comment by ai** [comment]
Nope. It is a syntax conflict.

You can fix it by replacing Sass with PreCSS, which is based on PostCSS.

**Comment by ai** [comment]
You can also report to Sass tracker, because postcss-media-minmax use W3C syntax, so standard CSS will broke Sass in future.

**Comment by davidkpiano** [comment]
@ai It's not official W3C syntax; it's only in editor's draft and it is invalid syntax in all current browsers. This is not a problem with Sass; this is an overzealous plugin.

**Comment by ai** [comment]
@davidkpiano it is official W3C editor’s draft :). I mean that it is highly probable that it became a standard soon.
