### ISSUE TITLE
zindex: true passed to cssnano by default

### ISSUE THREAD

**Issue by OndeVai** [postcss/postcss-loader#306]
It appears that {zindex: true} is being passed by default to the cssnano plugin. This caused us some big headache in the prod build. This option is set to false by default in the plugin itself (http://cssnano.co/optimisations/), so it should the same here.

**Comment by michael-ciniawsky** [comment]
Do you use `css-loader` `minimize` ? Which version of `cssnano` are you using ? `>= v4-rc.1`. `postcss-loader` doesn't alter any options to plugins by default, so the issue must by elsewhere
