### ISSUE TITLE
[postcss.config.js] Symlink or `npm/yarn link` confuse file lookup

### ISSUE THREAD

**Issue by moretti** [postcss/postcss-loader#308]
The following configuration:
```.js
{
  test: /\.css$/,
  use: [
    {
      loader: 'style-loader',
    },
    {
      loader: 'css-loader',
    },
    {
      loader: 'postcss-loader',
    },
  ],
}
```
breaks when using `yarn link`.

I can create a minimal example to reproduce the issue, but essentially the problem is that with a project like:
```
example_project:
  node_modules
    linked-module -> ../../../../linked-module
  webpack.config.js
  postcss.config.js
  index.js
```

`index.js`
```
import 'linked-module/style.css';
```
`postcss.config.js` is resolved from the wrong location, relative to `linked-module`:

```
Module build failed: Error: No PostCSS Config found in (..)/linked-module
```
---
This is probably in line with the docs:
> You can use different `postcss.config.js` files in different directories. Config lookup starts from `path.dirname(file)` and walks the file tree upwards until a config file is found.

A workaround is to explicitly define `config.path`:

```.js
loader: 'postcss-loader',
options: {
  config: {
    path: path.join(__dirname, 'postcss.config.js'),
  },
}
```

| OS                | node | yarn  | postcss | postcss-loader | webpack |
| ------------ | ----- | ---- | --------- | -------------- | ---------  |
|macOS 10.13|6.11.4|1.2.1  |6.0.11       |2.0.6                 |3.8.1          |

**Comment by alsyia** [comment]
Hello,

We are experiencing a really similar issue with postcss-loader 3.0.0. We can update, but looking at the changelog it looks like this the bug has not been fixed. Can you confirm whether it is still present? We are going to try explicitly setting the config path for now.

Thanks! :)
