### ISSUE TITLE
Replace the context of the postcss option function by an argument

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-loader#31]
The way it's currently handled is non intuitive https://github.com/postcss/postcss-loader/blob/a9cb6997eec444b4f90edd67ac7ec4b5d944cbb1/index.js#L28
What about replacing that .call(this) by just calling it with an argument?
Then in the configuration you can instead show a more clear code like 

```js
    postcss: function (webpack) {
        return [
            postcssImport({
                // see postcss-import docs to learn about onImport callback
                // https://github.com/postcss/postcss-import

                onImport: function (files) {
                    files.forEach(webpack.addDependency);
                }.bind(webpack)
            })
        ];
    }
```

Also fyi, I plan to add a `addDependencyTo` option to postcss-import in order to be able to write even more simpler and clean boilerplate like

```js
    postcss: function (webpack) {
        return [
            postcssImport({
                addDependencyTo: webpack
            })
        ];
    }
```

What do you think?

Note: to avoid a breaking change, we might start by changing the doc  + allow context and argument at the same time (via `.call(this, this)`), then in a later major release we replace `.call(this, this)` by `(this)`.

**Comment by MoOx** [comment]
Btw, we can even reduce the current boilerplate to

```js
    postcss: function () {
        // The context of this function is the webpack loader-context
        // see: http://webpack.github.io/docs/loaders.html#loader-context

        return [
            postcssImport({
                // see postcss-import docs to learn about onImport callback
                // https://github.com/postcss/postcss-import

                onImport: (files) => files.forEach(this.addDependency);
            })
        ];
    }
```

**Comment by ai** [comment]
Yeap, `this` is strange API. Do you want to send a PR to store you name in history? :)

**Comment by MoOx** [comment]
Sure. Will do with proper instructions in the readme.
