### ISSUE TITLE
[Question] Plugin fails without `{Error}`

### ISSUE THREAD

**Issue by malydok** [postcss/postcss-loader#313]
I'm trying to minify my CSS with `cssnano` but the plugin fails without ever producing any errors. If `cssnano` is set to execute first, then the following plugins, e.g. `autoprefixer` never get called also.

Please see the problem reproducing project: https://github.com/malydok/postcss-loader-plugin-fail

#### `postcss.config.js`
---

```
plugins: {
  'cssnano': {},
  'autoprefixer': {},
}
```

#### `webpack.config.js`
---

ℹ️  `extractSass` is an instance of `ExtractTextPlugin`

```
{
  test: /\.scss$/,
  use: extractSass.extract({
    fallback: 'style-loader',
    use: [
      'css-loader',
      'sass-loader',
      'postcss-loader'
    ]
  })
}
```

### `Environment`
---

`package.json`
```
"devDependencies": {
  "autoprefixer": "^7.1.6",
  "css-loader": "^0.28.7",
  "cssnano": "^3.10.0",
  "extract-text-webpack-plugin": "^3.0.2",
  "postcss-loader": "^2.0.8",
  "sass-loader": "^6.0.6",
  "style-loader": "^0.19.0",
  "webpack": "^3.8.1"
}
```

|OS|node|npm|postcss-loader|
|:-:|:--:|:-:|:------:|
|Windows 10|6.9.5|3.10.10|2.0.8|

**Comment by michael-ciniawsky** [comment]
Could you try using `postcss-reporter` (added after `cssnano`) and see if you get any warnings ?  `postcss-loader` handles errors, warnings emitted via `result.messages`, but can't do anything if the plugin doesn't have support for this mechanism

**Comment by malydok** [comment]
`postcss-reporter` didn't spit out any warnings so I decided to dig around a bit and finally found that it was `sass-loader` which caused the problem. A moment later I read in `postcss-loader` documentation the following sentence:

> Use it **after** `css-loader` and `style-loader`, but **before** other preprocessor loaders like e.g `sass|less|stylus-loader`, if you use any.

Which solves the case. Thanks a lot and sorry for not reading the docs properly (happens to us all I guess).

**Comment by michael-ciniawsky** [comment]
Oops 😅 I also didn't catch it...
