### ISSUE TITLE
[v2.0.6...2.0.7] `@import` path not found after upgrade

### ISSUE THREAD

**Issue by hualu00** [postcss/postcss-loader#316]
webpack build fails, saying that `Failed to find 'path/name.css'`

In one css file,
`@import 'path/name.css'`
it used to work fine, however, fails after the upgrade.

Here is my webpack config,  
```
rules: [
      {
        test: /\.css$/,
        exclude: /\.modules\.css$/,
        use: [ 'style-loader', 'css-loader', 'postcss-loader' ]
      },
```  
and postcss.config.js  
```
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {},
    'postcss-browser-reporter': {},
    'postcss-reporter': {}
  }
};
```

**Comment by michael-ciniawsky** [comment]
Does `./path/name.css` or `/path/name.css` work? I need more info about your file structure, did you change anything else besides updating `postcss-loader` `v2.0.6...2.0.7`. From the history it's unlikely to be a regression between `v2.0.6...v2.0.7`. Did you try to revert to `v2.0.6` ? Maybe 

**postcss.config.js**
```js
module.exports = ({ file }) => ({
   plugins: {
      'postcss-import': { root: file.dirname } // @import relative to the file currently processed by postcss-loader 
   }
})
```

**Comment by hualu00** [comment]
I didn't do anything else other than postcss-loader upgrade. And I've  tried to revert to v2.0.6, it turns out to be fine.  
I think this path has been resolved by webpack as I also use it in other js files.  
Why it works fine with blank `postcss-import` before with v2.0.6 ?

**Comment by michael-ciniawsky** [comment]
https://github.com/postcss/postcss-loader/compare/v2.0.6...v2.0.7 There doesn't seem to be a code change possibly related to your issue. As mentioned I need more info about your setup :)

**Comment by hualu00** [comment]
Did you update the dependencies?
Following is my webpack config
```
const config = {
  entry: {
    polyfills:  './polyfills.js',
    ie: 'eventsource-polyfill',
    demo: [
      demo_src + '/imports/demo-layout'
    ]
  },

  output: {
    path: demo_src,
    filename: '[name].[chunkhash].js',
    publicPath: '/assets/'
  },

  resolve: {
    modules: [
      src,
      demo_src + '/imports',
      'node_modules'
    ]
  },

  devtool: false,

  plugins: [
    new CaseSensitivePathsPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new Dotenv({ path: ROOT + '/.env' }),
    new AssetsPlugin(),
    new webpack.DefinePlugin({
      'process.env':{
        'NODE_ENV': '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin()
  ],

  module: {
    rules: [
      {
        test: /\.css$/,
        exclude: /\.modules\.css$/,
        use: [ 'style-loader', 'css-loader', 'postcss-loader' ]
      },
      {
        test: /\.modules\.css$/,
        use: [
          'style-loader',
          'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]&camelCase=only',
          'postcss-loader'
        ]
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url-loader?limit=200000&mimetype=application/font-woff'
      },
      {
        test: /\.md$/,
        use: 'raw-loader'
      }
};

as for 'path/name.css', `path` is a sub-folder in `src` which is resolved by webpack

**Comment by michael-ciniawsky** [comment]
`webpack` alias did never work with `postcss-import`, but may work without it and letting the `css-loader` revolve the `@import`'s (better anyways). Could you try without `postcss-import` please?

**Comment by hualu00** [comment]
I've tried it and still no work

**Comment by michael-ciniawsky** [comment]
Did you find a solution  e.g tried without `postcss-import` and changing the `@import` path to the correct URL ?

**Comment by hualu00** [comment]
I don't quite understand what is the right url? relative url? and it's quite complex because we have many levels of folders.  
I tried to config postcss-import in postcss.config.js, however, it doesn't work.  
I'm confused with the mechanism behind postcss resolve.

**Comment by michael-ciniawsky** [comment]
```
$ROOT
|–src
||– styles
|||– a.css
||– file.css
||– file.js
|
|– postcss.config.js
|- package.json
```

**postcss.config.js**
```js
module.exports = ({ file, options, env }) => ({
   plugins: {
     'postcss-import': { root: file.dirname }
   }
})
```

**file.css**
```css
@import './styles/a.css';
```

**file.js**
```js
import css from './file.css'

...
```

**Comment by hualu00** [comment]
I surely did this and print the root, it shows the right path, however still failed to find the css file

**Comment by michael-ciniawsky** [comment]
Please provide a small repo for reproduction for debugging then, it maybe also related to 

**webpack.config.js**
```
resolve: {
    modules: [
      src, // <=
      demo_src + '/imports',
      'node_modules'
    ]
  },
```

but I can't tell 💯

**Comment by hualu00** [comment]
After some time with postcss-import, I find this works: 
```
module.exports = {
  plugins: {
    'postcss-import': { addModulesDirectories: [ src ] },
    'postcss-cssnext': {},
    'postcss-browser-reporter': {},
    'postcss-reporter': {}
  }
};
```

**Comment by michael-ciniawsky** [comment]
hmm... 🙃  If that works for you but I personally would rely on it, both `postcss-import` (`node-resolve`) && webpack (`enhanced-resolve`)  use the same underlying resolve algo (`node_modules` resolving) I'm still wondering why you add the `src` directory to `resolve.modules`
