### ISSUE TITLE
[v2.0.7...2.0.8] inline `options` aren't applied/serialized (`happypack`)

### ISSUE THREAD

**Issue by davidlago** [postcss/postcss-loader#317]
### `Details`
---

After upgrading from 2.0.8 to 2.0.9, webpack fails to build a project, failing on the postcss-loader step.

### `Error`
---

Webpack output (many errors like the following):
```
ERROR in ./src/components/less/FullScreenDialogSlideUpAnimation.less
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in /Users/dlago/src/components/less
```

### `Reproduction`
---

Relevant portion of our webpack.config.js:

```
{
      id: 'less',
      threadPool: happyThreadPool,
      loaders: [
        {
          loader: 'css-loader',
          options: {
            modules: true,
            importLoaders: 1,
            localIdentName: '[name]__[local]___[hash:base64:5]'
          }
        },
        {
          loader: 'postcss-loader',
          options: {
            ident: 'postcss',
            plugins: () => [autoprefixer({ browsers: ['last 2 version', 'ie > 8'] })]
          }
        },
        'less-loader'
      ]
}
```

Files with the error reported above import the following (some of them that is the only import they do):

```
@import "../../variables.less";
``` 

And that file in turn imports:

```
@import (reference) '~cvent-styles/less/bootstrap/variables.less';
```

Not sure if the fact that we are using an ident when importing, and that is the only change from 2.0.8 to 2.0.9 (the way we handle them) could be the culprit here.

### `Environment`
---

|OS|node|npm|PostCSS|
|:-:|:--:|:-:|:------:|
|Mac OS X High Sierra|6.9.1|3.10.8|2.0.9|

**Comment by michael-ciniawsky** [comment]
Is  newer version of `happypack` able to serialize `{Function}` in `loader.options` ?  Your current issue occurs if the options in `webpack.config.js` aren't applied (not found) for some reason so `postcss-loader` tries to load a `postcss.config.js` file instead and finally fails. I don't use happypack myself but it uses workers and therefore needs to serialize the data. Using a `postcss.config.js` file should resolve this. It's unlikely to be a regression between `v2.0.8...2.0.9`

**Comment by davidlago** [comment]
The same version of HappyPack was used when building the project successfully with postcss-loader 2.0.8 though... same configuration with the Function in the loader options.

**Comment by michael-ciniawsky** [comment]
https://github.com/postcss/postcss-loader/compare/v2.0.7...v2.0.8 I can't spot anything suspicious in the diff that may relate to this within the commit range. Please provide a reproduction repo for debugging

**Comment by davidlago** [comment]
So sorry... wrong version. It was 2.0.8 to 2.0.9:
https://github.com/postcss/postcss-loader/compare/v2.0.8...v2.0.9

**Comment by michael-ciniawsky** [comment]
https://github.com/amireh/happypack/wiki/Loader-Compatibility-List  According to this list a `postcss.config.js` file is mandatory to work with `happypack` in general (see my previous comment), if this changed a while ago in `happypack` and the changes to the options `filterFn` in `postcss-loader` `v2.0.8...2.0.9`  are the cause for this I will revisit this asap, albeit I doubt it tbh since tests for this pass and `happypack` is known to not work with complex options (`{Function} || require()`) by design. If reverting to `v2.0.8 ` works, please provide a small reproduction repo and I will try to debug it. Feel free to reopen the issue if a reproduction is provided.
