### ISSUE TITLE
SourceMap not being generated.

### ISSUE THREAD

**Issue by sandiprb** [postcss/postcss-loader#325]
I'm using postcss-loader along with style loader & css loader.  My post css files are directly imported within React components and are used in conjunction  styles-loader/usable. Have parse `sourceMap: true` as options although doesn't seem to work.

### Webpack Config rules as below
```
rules: [
	{test: /\/pcss\/.*\.css$/,
            use: [
                     {loader: 'style-loader/useable',options: { sourceMap: true }},
                     {loader:'css-loader',},
                     {loader: 'postcss-loader',options: { sourceMap: true }},
		],
	},
]
```

Please provide information about your environment.

|OS|node|npm|PostCSS|
|:-:|:--:|:-:|:------:|
|[Mac]|[v6.11.2]|[5.5.1]|[6.0]|

**Comment by evilebottnawi** [comment]
@sandiprb use `sourceMap: true` for `css-loader`, because `sourceMap` is `false` by default. Thank for issue!

**Comment by sandiprb** [comment]
Hey, that worked like a charm. Thanks a lot 👍
