### ISSUE TITLE
Can't npm install because require-from-string version 1.0.1 been removed from npm repo

### ISSUE THREAD

**Issue by anthonymuau** [postcss/postcss-loader#327]
postcss-loader is failing to install because the npm package require-from-string 1.0.1 has been removed from npm.

### `Details`
---

postcss-loader has of dependencie of postcss-load-plugins  that has a dependencie of cosmiconfig what has dependencie of require-from-string 1.0.1. require-from-string 1.0.1 has been removed from npm so npm install fails.

### `Error (Logs|Stacks)`
---
npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

**Comment by michael-ciniawsky** [comment]
https://github.com/npm/registry/issues/255#issuecomment-355771177
