### ISSUE TITLE
Error: ENOENT: no such file or directory ...node_modules/@std/esm/esm.js.gz

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [postcss/postcss-loader#329]
Hello,

I am suddenly getting an issue trying to add the postcss-cssnect plugin. throws the following error:

```
Module build failed: Error: ENOENT: no such file or directory, open '{system path}/node_modules/@std/esm/esm.js.gz'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> 
```

It works fine without this plugin. I have asked postcss-cssnext and was informed it could not be their plugin. Perhaps a recent update has created an issue?

Thanks

**Comment by michael-ciniawsky** [comment]
```
'{system path}/node_modules/@std/esm/esm.js.gz'
```

I can't really tell from the info provided, but did you try to clean your `node_modules` folder and the `@std/esm` cache ? Looks unrelated to `postcss-loader`...Are you using a `postcss.config.js` file ?

As mentioned I need more info about your setup please

**Comment by theboyWhoCriedWoolf** [comment]
I cleared and reinstalled a few times. I am using the following config in webpack:

```
{
                test: /\.css$/,
                use: [
                    require.resolve('style-loader'),
                    {
                        loader: require.resolve('css-loader'),
                        options: {
                            importLoaders: 1,
                            modules: false,
                        },
                    },
                    {
                        loader: require.resolve('postcss-loader'),
                        options: {
                            ident: 'postcss',
                            plugins: () => [
                                require('postcss-flexbugs-fixes'),
                                require('postcss-cssnext')(),
                            ],
                        },
                    },
                ],
            },
```

**Comment by michael-ciniawsky** [comment]
Did you find a solution ?

**Comment by theboyWhoCriedWoolf** [comment]
Hello @michael-ciniawsky, it seemed to be a mismatch in versions and I not only had to clear cache but also clear my directory and move files. So possibly just an issue with my system. 

All good now. Thanks
