### ISSUE TITLE
Config for plugins doesn't seems to work

### ISSUE THREAD

**Issue by amir20** [postcss/postcss-loader#330]
### `Details`

I am trying to disable warnings for `customer-properties` by doing `warnings: false`. 

```
{
        test: /\.(sass|scss|css)$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: [
            {
              loader: "css-loader",
              query: {
                importLoaders: 1
              }
            },
            {
              loader: "postcss-loader",
              options: {
                ident: 'postcss',
                plugins: loader => [
                  require("postcss-custom-properties")({ warnings: false }),
                  require("postcss-import")(),
                  require("postcss-cssnext")(),
                  require("postcss-font-magician")()
                ]
              }
            },
            "sass-loader"
          ]
        })
```

### `Error (Logs|Stacks)`

```
    WARNING in ../node_modules/css-loader?{"importLoaders":1}!../node_modules/postcss-loader/lib?{"ident":"postcss","postcss-custom-properties":{"warnings":false}}!../node_modules/sass-loader/lib/loader.js!./css/styles.css
    (Emitted value instead of an instance of Error) postcss-custom-properties: /Users/amirraminfar/go/src/github.com/amir20/clashstats/assets/css/styles.css:5941:5: Custom property ignored: not scoped to the top-level :root element (.columns.is-variable.is-8 { ... --columnGap: ... })
```

### `Reproduction [Code]`

See above.  You can also clone my project at https://github.com/amir20/clashstats/tree/font-magic and run `webpack --progress` to see it fail. 

### `Environment`

|OS|node|npm|PostCSS|
|:--:|:----:|:---:|:-------:|
|MacOS X|`>= v9.0.0`|` >= v5.0.0`|`>= v6.0.0`|

**Comment by amir20** [comment]
I have tried this for hours and I can't figure out how to configure `ExtractTextPlugin` with postcss. It doesn't seem like it is working with custom config.

**Comment by michael-ciniawsky** [comment]
You're getting this warning from `postcss-cssnext` which already includes `postcss-custom-properties` https://github.com/MoOx/postcss-cssnext/blob/master/package.json#L31 wanings are enabled there

**Comment by amir20** [comment]
Thanks for the quick response. So is there no way to disable it within cssnext?

**Comment by amir20** [comment]
Thanks, @michael-ciniawsky. I realize `css-next` is not even your project. But that worked. This has been annoying me for 2 months now and you finally figured it out.
