### ISSUE TITLE
postcss BrowserslistError: Unknown version 61 of firefox

### ISSUE THREAD

**Issue by mrkhanakia** [postcss/postcss-loader#333]
I am getting error while using postcss loader with webpack **BrowserslistError: Unknown version 61 of firefox**

`
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-1!node_modules/resolve-url-loader/index.js??ref--4-2!node_modules/postcss-loader/lib/index.js??ref--4-3!node_modules/sass-loader/lib/loader.js??ref--4-4!node_modules/antd/lib/grid/style/index.css:
       1 module
    
    ERROR in ./node_modules/css-loader?{"sourceMap":true}!./node_modules/resolve-url-loader?{"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/antd/lib/grid/style/index.css
    Module build failed: BrowserslistError: Unknown version 61 of firefox
        at Function.select (D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\browserslist\index.js:622:17)
        at D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\browserslist\index.js:151:33
        at Array.reduce (<anonymous>)
        at resolve (D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\browserslist\index.js:132:18)
        at browserslist (D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\browserslist\index.js:224:16)
        at D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\postcss-preset-env\index.bundle.js:160:12
        at Array.some (<anonymous>)
        at D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\postcss-preset-env\index.bundle.js:159:29
        at Array.filter (<anonymous>)
        at D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\postcss-preset-env\index.bundle.js:158:42
        at D:\EasyPHP-DevServer-14.1VC11\data\localweb\python\whatsapp_react\client\node_modules\precss\index.bundle.js:31:12
        at <anonymous>
`

Versions
`
 "postcss-loader": "^2.1.0",
    "precss": "^3.1.0",
    "resolve-url-loader": "^2.2.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.20.1",
    "url-loader": "^0.6.2",
`

**Comment by michael-ciniawsky** [comment]
There isn't a Firefox 61 released yet (latest is 58) ? 😛  Did you mean Chrome 61 ?

**Comment by mrkhanakia** [comment]
I know firefox has not 61 version
Please check the error log it is saying **Unknown version 61 of firefox**

**Comment by michael-ciniawsky** [comment]
@egorpavlikhin browserlist is not directly used by `postcss-loader`, please included your current postcss dependencies and I also think this was fixed in a newer version of browserslist (but not 💯 sure). It might be better to open an issue in browserslist instead
