### ISSUE TITLE
Invalid path resolutions in version 2.1.1

### ISSUE THREAD

**Issue by milewski** [postcss/postcss-loader#343]
After upgrading to the latest version `2.1.1` my build no longer works, all relative paths seems to be resolving to an invalid path:

```
 warning  in ./source/components/sections/faq-block.vue

(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  ENOENT: no such file or directory, scandir 'G:\Code\website\source\components\sections\G:\Code\website\source\components\sections'
  at Object.fs.readdirSync (fs.js:924:18)
```

faq-block.vue scss
```
&::before {
   background: url("../../assets/images/icons/faq.svg") no-repeat;
}
```
rolling back to the version `2.1.0` solves the issue

currently i'm using Window 10

**Comment by evilebottnawi** [comment]
@milewski don't related to `postcss-loader`, problem in `resolve-url-loader`, it is very buggy and old loader. You can use absolute url or create new `resolve-url-loader` for solve this problem, sorry, but we have time on this.

**Comment by evilebottnawi** [comment]
Also you can have `resolve-url-loader` above `postcss-loader`, just change their order
