### ISSUE TITLE
context.env not being honoured

### ISSUE THREAD

**Issue by neslinesli93** [postcss/postcss-loader#353]
For some reasong, I am finding that `context.env` is always equal to `development` as it resorts to the default value. I'm setting `process.NODE_ENV` to `production` in my webpack production config file, but it's then ignored inside my `postcss.config.js`.

Thanks

**Comment by minhtranite** [comment]
I tried inject env from webpack config into postcss config but it inject to context.options.env instead of context.env. Is it a bug ?

Inside webpack config:
```js
{
              loader: 'postcss-loader',
              options: {
                sourceMap: true,
                config: {
                  ctx: {
                    env: argv.mode,
                  },
                },
              },
            },
```
Run `webpack --mode=production` and the context in postcss config file:
```
{
  cwd: '...',
  env: 'development',
  file:
    {
      extname: '.scss',
      dirname: '...',
      basename: 'index.scss',
    },
  options: { env: 'production' },
}
```

**Comment by systemist** [comment]
There seems to be a bug in webpack-cli. 

`NODE_ENV=production ./node_modules/.bin/webpack` works as expected.

`./node_modules/.bin/webpack --env.NODE_ENV=production` doesn't work. The value of process.env.NODE_ENV is **development**;

**Comment by evilebottnawi** [comment]
@systemist can you create issue in `webpack-cli`?

**Comment by systemist** [comment]
@evilebottnawi actually I was wrong (kind of). When passing `--env.NODE_ENV=production` argument, the value of process.env.NODE_ENV will be **production** inside `webpack.config.js`, but **development** inside `postcss.config.js`; 

Using the shell to set environment var works in both configs.

**Comment by nikolay-borzov** [comment]
Have the same issue. It seems like webpack sets `process.env.NODE_ENV=production` after postcss-loader processes `postcss.config.js`

webpack.prod.js:
```
module.exports = merge(common, {
  mode: 'production',
  // other parameters
}}
```

npm script:
```
"build:prod": "webpack --config webpack.prod.js"
```

postcss.config.js:
```
module.exports = ({ file, options, env }) => {
  console.log('ENVIRONMENT', env, process.env.NODE_ENV)

  return {
    plugins: {
      autoprefixer: true
    }
  }
}
```

Outputs: ENVIRONMENT development development.

Change script to:
```
build:prod": "cross-env NODE_ENV=production webpack --config webpack.prod.js"
```
And output will be: ENVIRONMENT production production

**Comment by ZSkycat** [comment]
```js
// webpack.production.js

const merge = require('webpack-merge');
const base = require('./webpack.base');

let config = merge(base, {
    mode: 'production',
    ...
});
module.exports = config;
process.env.NODE_ENV = 'production';
```

Add this line of code to fix the bug temporarily:
`process.env.NODE_ENV = 'production';`

**Comment by evilebottnawi** [comment]
Looks like bug, PR welcome, should be easy to fix

**Comment by michael-ciniawsky** [comment]
`env` is set by `process.env.NODE_ENV` or defaults to `development`. Since `webpack` decided to not rely/fallback on `NODE_ENV`  for `mode`, it is unfortunate but you need to add `mode` to the ctx yourself or set `NODE_ENV` separately to webpack's  `mode`

### `1`

**webpack.config.js**
``
`js
module.exports = {
   mode: 'development'
   ...
     {
        loader: 'postcss-loader'
        options: { 
           config: { 
             ctx: { mode: this.mode } 
           } 
      }
   ...
}
```

### `2`

**webpack.config.js**
```js
const env = process.env.NODE_ENV || 'development'
module.exports = {
   mode:  env
   ...
    { loader: 'postcss-loader' }
   ...
}
```

**Comment by zenoven** [comment]
I got env undefined in postcss.config.js

 in the npm scripts there is no env set 

```
"start": "npm run dev",
```

```js
// webpack.config.js
const env = process.env.NODE_ENV || 'development'
const mode = env === 'production' ? 'production' : 'development'
...
console.log('process.env.NODE_ENV:', process.env.NODE_ENV)
console.log('mode:', mode)
const config = {
  mode: mode,
  ...
}
```
 which output is 
```
process.env.NODE_ENV: undefined
mode: development
```

```js
// postcss.config.js
module.exports = ({ file, options, env }) => {
  console.log('env:', env, 'process.env.NODE_ENV:', process.env.NODE_ENV )
  return {
    plugins: {
      'postcss-import': { root: file.dirname },
      // 'postcss-cssnext': options.cssnext ? options.cssnext : false,
      'autoprefixer': env === 'production' ? options.autoprefixer : false,
      'cssnano': env === 'production' ? options.cssnano : false
    }
  }
}
```
 which output is 
```
env: undefined process.env.NODE_ENV: development
``` 


I'm really confused, shoud I set env in the npm scripts first?

**Comment by michael-ciniawsky** [comment]
Yep :)

```
"build": "NODE_ENV=production webpack"
"start": "NODE_ENV=development webpack-dev-server'
```

**webpack.config.js**
```js
const env = process.env.NODE_ENV || 'development'

const config = {
   mode: env,
   ...
}

module.exports = config
```

See my comment above for how to add webpack `mode` to the config context, albeit I don't recommend doing so, since it is needlessly verbose and redundant to use `mode` over `env`. Just ensure to set `mode` via `env` in the config to enable all `webpack` related optimizations

**Comment by PutziSan** [comment]
Does the [documentation for `context (ctx)`](https://github.com/postcss/postcss-loader#context-ctx) correspond to the actual behavior?

`webpack.config.js`
```
{
  loader: "postcss-loader",
  options: {
    config: {
      ctx: { 
        env: "production" 
      }
    }
  }
}
```

`postcss.config.js`
```javascript
module.exports = ({ options, env }) => {
  console.log(env); // undefined
  console.log(options.env); // "production"
  // ...
};
```

I think it should be exactly upside down? (`env === "production"` and `options.env === undefined`)
