### ISSUE TITLE
Not working with webpack 4

### ISSUE THREAD

**Issue by bspies-work** [postcss/postcss-loader#357]
postcss-loader 2.1.4
webpack 4.6.0

```
{
    loader: 'postcss-loader',
    options: {
        sourceMap: true,
        plugins: function () {
            return [autoprefixer(supportedBrowsersList)];
        }
    }
}
```

Error:
 FAILED to compile with webpack: ModuleBuildError: Module build failed: TypeError: loader._compilation.applyPluginsWaterfall is not a function
    at /Users/bspies/GW/Source/portals/portals-frontend/react-portal/node_modules/postcss-loader/index.js:122:43
    at <anonymous>:null:null

**Comment by evilebottnawi** [comment]
@bspies-work You use old version of `postcss-loader` (i.e. 1, here code https://github.com/postcss/postcss-loader/blob/1.3.3/index.js#L122). Also you remove issue template. And don't provide minimum reproducible test repo. We can't help you here, sorry. Feel free to reopen issue when you upgrade postcss-loader and fix issue template. Thanks!
