### ISSUE TITLE
Failure on inline comments

### ISSUE THREAD

**Issue by johnwp** [postcss/postcss-loader#36]
I'm getting errors on inline comments such the one below.  Is there a known workaround for this?

```
//Bootstrap
@import 'bootstrap/bootstrap';
```

**Comment by ai** [comment]
Because CSS has no inline comments. Use SCSS parser in PostCSS

1. `npm install postcss-scss`
2. `postcss-loader?parser=postcss-scss`

**Comment by blachawk** [comment]
@ai for myself and anyone who is new to using parsers, can you elaborate a little more on how 
> postcss-loader?parser=postcss-scss
gets implemented in our webpack.config.js file?  I currently have the following setup...

```js
 {
   loader: 'postcss-loader',
     options: {
       plugins: [],
      }
 },
```

Thanks in advanced!

**Comment by ai** [comment]
@blachawk 

```js
{
  loader: 'postcss-loader',
 options: {
   parser: 'PARSER_NAME'
  }
}
```

Should works. But if you want to compile SCSS to CSS, you need yo use `sass-loader` and not a parser.

**Comment by Juraj-Masiar** [comment]
A more specific example that can handle inline comments if anyone is looking for (using the `sass-loaded`).
```webpack
{
  test: /.s?css$/,
  sideEffects: true,
  use: [
    IS_PROD ? MiniCssExtractPlugin.loader : "style-loader",
    "css-loader",
    "postcss-loader",
    "sass-loader",
  ],
},
```
