### ISSUE TITLE
Output is duplicated when using postcss-loader and mini-css-extract-plugin

### ISSUE THREAD

**Issue by goldfire** [postcss/postcss-loader#362]
When using `postcss-loader` in combination with `css-loader` and `mini-css-extract-plugin` to combine multiple css files into one, the css output gets duplicated in the final file. The below code works; however, all of the CSS is included in the styles.css file twice. If I remove the `postcss-loader` portion from the webpack config, it is no longer duplicated. I also tried removing all plugins from the postcss.config.js file and everything is still duplicated.

### `Reproduction [Code]`
---

The relevant part of the webpack config:

```javascript
module: {
  rules: [
    {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader?-minimize!postcss-loader',
        ],
      },
  ],
},
plugins: [
  new MiniCssExtractPlugin({
    filename: '[name].css',
  }),
],
```

postcss.config.js:

```javascript
module.exports = {
  plugins: {
    autoprefixer: {},
    cssnano: {
      zindex: false,
      reduceIdents: false,
    },
  },
};
```

### `Environment`
---

* node@8.11.1
* webpack@4.8.1
* postcss-loader@2.1.5
* css-loader@0.28.11
* mini-css-extract-plugin@0.4.0

**Comment by evilebottnawi** [comment]
@goldfire please create minimum reproducible test repo, thanks!

**Comment by goldfire** [comment]
While putting the minimal test repo together I discovered that the issue was I had an `index.css` file that was `@import`ing each CSS file. I guess the behavior with this changed from Webpack 3 to 4 (or I didn't notice it was duplicating before)? This caused all of those CSS files to be included in the output twice.
