### ISSUE TITLE
I am unable to install it

### ISSUE THREAD

**Issue by Tanuj69** [postcss/postcss-loader#367]
`Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\DELL>cd desktop\suliteos

C:\Users\DELL\Desktop\suliteos>npm i -D postcss-loader
[            ......] \ finalize:code-point-at: sill finalize C:\Users\DELL\Desktop\suliteos\node_modules\fsevents\node_

`
stuck at this for a long time and I tried numerous times

**Comment by evilebottnawi** [comment]
@Tanuj69 problem in npm, try to reinstall npm
