### ISSUE TITLE
Shouldn't there be a way to notify plugins of files having been changed?

### ISSUE THREAD

**Issue by x-yuri** [postcss/postcss-loader#369]
Let's say I have the following CSS:

```css
body {
    width: image-width(1.png);
    background: url(1.png);
}
```

Here I'm using [`postcss-image-sizes`](https://github.com/s0ber/postcss-image-sizes). The issue is that it caches [the results](https://github.com/s0ber/postcss-image-sizes/blob/3014e1decd972bdc273cc4f319298ba55a6cc45c/src/index.js#L38). As such, when the image changes on disk, corresponding CSS file gets the obsolete value (from the previous version of the image). I can probably deal with it in `webpack.config.js`, but shouldn't there be a way to notify `postcss-image-sizes` of an image having been changed? What do you think is the proper way to handle it?

You can find the details [here](https://github.com/webpack-contrib/css-loader/issues/747). `css-loader` doesn't add dependency on the image yet, so there's no easy way to reproduce it. That is, there are two issues here:

1. CSS file doesn't get rebuilt when the image changes (`css-loader` issue).
2. Even if it does, it doesn't get current value (this issue).

**Comment by michael-ciniawsky** [comment]
`postcss-loader` supports watching additional files via [`result.messages`](https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L148-L150). `postcss-image-sizes` needs to add every image passed by it's `assetPath` option to to `result.messages` in the following way

```js
// Images URL's (options.assetPath + img)
urls.forEach((url) => {
  result.messages.push({ 
     type: 'dependency',
     file: url
  })
})
```

and `postcss-loader` will add them as a `dependency` to `webpack` automatically. This eventually fixes the `css-loader` issue aswell, since the image file is being watch then (no need to add that logic to `css-loader`). I suggest you open a PR in the `postcss-image-sizes` repo or fork the plugin :)

**Comment by x-yuri** [comment]
@michael-ciniawsky Indeed, that would probably solve the first issue (CSS file doesn't get rebuilt). But not the second one. `postcss-image-sizes` [caches][cache] image extents. So even if it were to be asked about image extents on a successive build, it would give the same reply. How can it know when to clear the cache?

[cache]: https://github.com/s0ber/postcss-image-sizes/blob/3014e1decd972bdc273cc4f319298ba55a6cc45c/src/index.js#L38

**Comment by michael-ciniawsky** [comment]
There simply needs to be a more 'advanced' caching mechanism, the extracted helpers from the CSS fle + the image source path need to construct a **cache key** which is invalidates the cache for an image 

```js
const cache = new WeakMap()

function key (img, options) {
  // e.g path/to/image.png?w=300&h=400 (Image Path + Options/Helpers/Metadata)
  const buffer = Buffer.from(`${img}?${options}`)
  // zgg574h1 => Cache Key (Unique Hash)
  return crypto
    .createHash('md4')
    .update(buffer)
    .digest('hex')
    .substr(0, 8)
}

function plugin () {
   let result = ''

   if (cache.has(key(img, options))) {
     result = cache.get(key(img, options))

     return result
   }

   result = // process ...

   cache.set({ 
       [key(img, options)]: result  // { 'zgg574h1': {Result} }
   })
}
```

> ⚠️ This above is just sloppy pseudo code :), but that's the idea

The plugin doesn't currently work well for your use case and I can't possibly do anything on the `postcss-loader` side here to fix it. You need to either write your own plugin or send a PR to fix the cache and add missing dependecy tracking etc to `postcss-image-sizes`

**Comment by x-yuri** [comment]
@michael-ciniawsky I might make PRs to `postcss-image-sizes` repository. But you must be missing the point here. `postcss-image-sizes` replaces `image-width(./1.png)` in css code with say `100px`. Not resizes the image. No options besides [`assetsPath`](https://github.com/s0ber/postcss-image-sizes/tree/3014e1decd972bdc273cc4f319298ba55a6cc45c#configuration-options).

So to check if the cache is invalid, you've got to read the file (which makes the cache meaningless), or subscribe to some sort of file system notifications (which makes no sense when `postcss` is running standalone, and probably overkill). Or clear the cache every time `webpack` builds the bundle. E.g. add `clearCache()` method to `postcss-image-sizes` plugin, and create a `webpack` plugin in `webpack.config.js`, which calls the method every time `webpack` invalidates the build. And maybe make it public? Like, `PostCSSImageSizesClearCachePlugin` :)

What do you think?

**Comment by michael-ciniawsky** [comment]
>I might make PRs to postcss-image-sizes repository. But you must be missing the point here. postcss-image-sizes replaces image-width(./1.png) in css code with say 100px. Not resizes the image. No options besides assetsPath.

By 'options'  I meant the values within the CSS Code, image path + css values === cache key, the cache currently only checks if the image exists or not , there might be a `mtime` (Did the file change ?) check needed aswell here (`mtime` is on the `fs.stat()` `{Object}`). But most importantly if one changes something within the CSS the cache isn't currently invalidated and the change won't have any effect. Only the image path as cach key simply isn't enough

**Comment by michael-ciniawsky** [comment]
> So to check if the cache is invalid, you've got to read the file (which makes the cache meaningless), or subscribe to some sort of file system notifications (which makes no sense when postcss is running standalone, and is probably overkill). Or clear the cache every time webpack builds the bundle. E.g. add clearCache() method to postcss-image-sizes plugin, and create a webpack plugin in webpack.config.js, which calls the method every time webpack invalidates the build. And maybe make it public? Like, PostCSSImageSizesClearCachePlugin :)

That will be magnitudes more complicated as fixing or simply disabling the cache within the plugin to begin with, but yes there are other solution possible in general but that's complicated to explain and won't solve your problem asap. In case you favor or want to try out the webpack plugin approach

```js
class Plugin {
   constructor (options = {}) {
      this.plugin = { name: 'PostCSSImageSizes' }
      this.options = options
   }
   
  apply (compiler) {
    const { plugin, options } = this
    const { compilation } = compiler.hooks
      
    compilation.tap(plugin, (compilation) => {
       // Have fun...
    })
  }
}

module.exports = Plugin
```

For handling CSS assets (images etc), instead of a loader a webpack PostCSS Plugin might be good idea. Processing images and co kg within CSS is not straightforward in webpack atm...

**Comment by x-yuri** [comment]
@michael-ciniawsky Let me explain myself. That's not a big issue for me. I can fix it by adding (PR) `clearCache()` method to `postcss-image-sizes` plugin, and the following code to `webpack.config.js`:

```js
plugins: [
    {apply: function(compiler) {
        compiler.plugin('invalid', () => {
            imageSizesPlugin.clearCache();
        });
    }}
],
```

But it may be a sign of something being off in the Webpack or `postcss-loader`.

Come to think of it, I had a similar issue with [`postcss-custom-properties`](https://github.com/postcss/postcss-custom-properties) plugin. I used this plugin to provide variables to CSS from a file. But when the file changes, I've got to somehow make new values available to the plugin. So I used a similar approach to call `customProperties.setVariables(...)`.

So, it might be an issue with `postcss-loader`, since it's supposedly doesn't reinstantiate plugins when a build starts. Considering I can pass an initialized instance of a plugin to `postcss-loader`, it might not even have a chance to:

```js
{loader: 'postcss-loader',
options: [
    plugins: [
        require('postcss-custom-properties')({
            variables: ...,
        }),
    ],
]}
```

If making `postcss-loader` reinstantiate plugins on every build (**option 1**) is not a good solution, the next thing that comes to mind is to make Webpack notify loaders of starting a build (**option 2**), which in its turn can notify the plugins.

But it's probably best to leave webpack loaders oblivious to the fact that files may be built more than once (to not make them any more complex). So it might make sense to turn `postcss-loader` into a plugin with a loader (**option 3**). Then it can subscribe to `invalid` event.

Now we have two suboptions:

1. Provide a mechanism for `postcss-loader` to notify plugins of starting a build (**option 3.1**). But considering that `postcss`—when used outside of Webpack infrastructure—generally compiles assets just once, this might be not a good option. Not to mention that in more complex cases, you might need to pass some info (new variables in case of `postcss-custom-properties` plugin).

2. Leave the user responsible for taking necessary actions in `webpack.config.js` by calling plugin methods (**option 3.2**), for instance:

```js
plugins: [
    new PostCSSPlugin({
        onInvalid: plugins => {
            plugins['postcss-custom-properties'].setVariables(...);
        },
    }),
],
```

I'd like to contribute to resolving this issue. But I might not know Webpack well enough to come up with a good solution. (Although, I've spent a lot of time inspecting it with a debugger.) So I decided to ask. And was surprised with the direction it took. I feel a bit uneasy about me not being able to fully understand you. Particularly:

> There simply needs to be a more 'advanced' caching mechanism, **the extracted helpers from the CSS fle** + the image source path need to construct a cache key which is invalidates the cache for an image

> By 'options' I meant **the values within the CSS Code,** image path + **css values** === cache key, the cache currently only checks if the image exists or not, there might be a mtime (Did the file change ?) check needed aswell here (mtime is on the fs.stat() {Object}). But most importantly **if one changes something within the CSS the cache isn't currently invalidated and the change won't have any effect.** Only the image path as cache key simply isn't enough...

I understand the idea of adding `mtime` to the cache key. But wouldn't it make the cache less useful? It might result in reading from disk, might it not?

Regarding "extracted helpers from css", "values withing the css code", "css values", I have no clue what they might be. Can you tell what they are specifically for `postcss-image-sizes` case?

As for "if one changes something within the CSS", I see nothing in css that might need the cache to be invalidated. When path to a image in CSS changes, the cache key changes as well, but that doesn't mean that the value under the new key is invalid. The only thing that makes the cache invalid is the fact that a image has been changed. Adding modification time to the cache key is just a way (workaround) to check if image has been changed without reading the it.

> Processing images and co kg within CSS is not straightforward in webpack atm...

Here I suppose you're hinting at Webpack 4 CSS Module Type. If it's going to solve the issue, or change the solution significantly, we can wait until it's there.

P.S. I'd like to know the best (optimal) way to solve the issue. Not the easiest one.

**Comment by michael-ciniawsky** [comment]
I promise to throughly answer your questions within the next few days, I have something for most of this already in mind and I wrote a `postcss-webpack-plugin` (e.g use `postcss-custom-properties on the whole CSS Chunk instead of each CSS Module separately) and a new `css-loader` which transpiles CSS to an ES Module for `@import` && `url()` support (I will explain that approach in detail as promised and link to the repo's when once pushed :))

> Here I suppose you're hinting at Webpack 4 CSS Module Type

I'm the author of the initial CSS Module Type PR in webpack/webpack :stuck_out_tongue:, but the same is solveable with a plugin and a loader while 'native' CSS support is complicated (on the edges) with the way webpack currently works (Multi Compiler, many ways to specify entries and the affects this has on the module graph, communication between different module types e.g exporting CSS Modules to a JS Module, HMR ...). One needs to rebuild most functionality for a new module type since most of the features are implemented as methods of the JS Parser atm
