### ISSUE TITLE
Use PostCSS 7

### ISSUE THREAD

**Issue by ai** [postcss/postcss-loader#374]
There are no real breaking changes, we just dropped Node.js 4

**Comment by patrickabkarian** [comment]
made a pull request

**Comment by michael-ciniawsky** [comment]
I need to make a quick check on the weekend what else might be a good idea to potentionally include in  the next a major release + the additional chores like docs polishing etc. I don't think there are other (needed) breaking changes atm, so I'm heading to cut a release on the weekend/monday for PostCSS v7.0.0 (#375). If there is anything else to triage please open an issue
