### ISSUE TITLE
Using unstable dependency breaking build

### ISSUE THREAD

**Issue by soulman-is-good** [postcss/postcss-loader#387]
This package uses unstable dependency [shema-utils](https://github.com/postcss/postcss-loader/blob/master/package.json#L16), which was updated recently with breaking changes which is failing our build.

### `Details`
---

We are using `postcss-loader@^2.0.6` in our project with `nodejs version 4.2.2` and currently we cannot use newer node.
Today we couldn't build our application as it was failing.
See details and error stack in the corresponding issue reported in that package https://github.com/webpack-contrib/schema-utils/issues/31

### `Environment`
---

|OS|node|npm|PostCSS|
|:-:|:--:|:-:|:------:|
|Linux RHEL6|4.2.2|2.14.7|2.1.6|

**Comment by michael-ciniawsky** [comment]
Already on it, closing in favor of https://github.com/webpack-contrib/schema-utils/issues/31
