### ISSUE TITLE
Extract CSS vs style-loader

### ISSUE THREAD

**Issue by owenstrevor** [postcss/postcss-loader#394]
Would be good to explain the difference between Extract CSS vs style-loader as I see many people include both in their projects. Under the Extract CSS section it does not explain why you have it setup that way.

From the Extract CSS github page:

> [Extract CSS] plugin should be used only on production builds without style-loader in the loaders chain, especially if you want to have HMR in development.
> 
> Here is an example to have both HMR in development and your styles extracted in a file for production builds.

**Comment by evilebottnawi** [comment]
@owenstrevor not here, it is just `postcss` loader, also we already have this https://github.com/webpack-contrib/mini-css-extract-plugin#mini-css-extract-plugin, feel free to send a PR if you have better description
