### ISSUE TITLE
How to exclude a loader, because there are multiple identical loaders in my project, in different directories.   

### ISSUE THREAD

**Issue by lilong7676** [postcss/postcss-loader#395]
### Proposal

How to exclude a loader, because there are multiple identical loaders in my project on different directories.

### Use Case

eg.
loader one:
/project/postcss.config.js

loader two:
/project/src/common/postcss.config.js

how to exclude others from using only one loader.

thank you!

### Implementation

- [x] I'm open to work on this
  - [x] I need help/mentorship
- [ ] I'm unable to work on this

**Comment by evilebottnawi** [comment]
@lilong7676 use difference loader to difference files based on regex (`test` option) with another config

**Comment by lilong7676** [comment]
thanks, this issue has beren resolved, 
just use:
{
  loader: 'postcss-loader',
  options: {
    config: {
      path: 'path/to/.config/' 
    }
  }
}
