### ISSUE TITLE
merge loader options with options from config file(by `postcss-load-config`)

### ISSUE THREAD

**Issue by lovetingyuan** [postcss/postcss-loader#396]
### Proposal

merge loader options with options from config file(by `postcss-load-config`)

but now `postcss-loader` will ignore config file like `postcss.config.js` or `.postcssrc` when it's options has some useful fields like `plugins`.

I hope `postcss-loader` can merge it's own options and other valid options loaded by `postcss-load-config`.
 Thanks.

**Comment by evilebottnawi** [comment]
@lovetingyuan config is aromatic and should not be merge to avoid bad DX, also please use issue template in future
