### ISSUE TITLE
Post-css not running

### ISSUE THREAD

**Issue by nwhite89** [postcss/postcss-loader#4]
I currently have

```js
loaders: [
            {
                test:   /\.css$/,
                loader: 'style-loader!css-loader!postcss-loader'
            }
        ],
postcss: {
        defaults: [
            autoprefixer({
                browsers: ['last 2 version']
            })
        ]
    }
```

The CSS I am passing to the loader is 

```
/** @define DateTime; use strict */

:root {
    --DateTime--understateTime-font-size: 0.75em;
}

.DateTime--understateTime .DateTime-time {
    font-size: var(--DateTime--understateTime-font-size); /* 1 */
}
```

but then what's being passed back is the same as what is passed the loader any ideas?

**Comment by ai** [comment]
You use only Autoprefixer. Autoprefixer adds prefixes. `font-size` doesn’t need any prefix. So you output will be equal input.

PostCSS is totally modular thing. You take only necessary plugin. Take plugins from [Plugins list](https://github.com/postcss/postcss#plugins) and add them to `postcss` option.

**Comment by nwhite89** [comment]
correct me if I'm wrong (apologies very new to post-css) ``val()`` can be used without any plugins no?

**Comment by ai** [comment]
`val()` is supported only in some browsers. So to use universal solution you should add `cssnext` PostCSS plugin

**Comment by nwhite89** [comment]
@ai I see thanks apologies meant ``var()`` have seen that it comes with postcss-custom-properties and thought it actually came built in with post-css. Will close this issue

**Comment by simonsmith** [comment]
Having a similar issue, also trying custom properties funnily enough. Have tried `cssnext` and also `postcss-custom-properties` but my CSS remains the same.

`webpack-config` below:

``` js
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var webpack = require('webpack');
var customProperties = require("postcss-custom-properties")

module.exports = {
  entry: {
    module: "./source/javascripts/app.js",
  },
  output: {
    path: './source/built/',
    filename: 'app.js'
  },
  resolve: {
    modulesDirectories: [
      'node_modules',
      'source/components'
    ],
    extensions: ['', '.js', '.js.erb', '.jsx']
  },
  module: {
    loaders:[
      {
        test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')
      }
    ]
  },
  postcss: [customProperties],
  plugins: [
    new ExtractTextPlugin('app.css')
  ]
};
```

@nwhite89 Did you get it working?

**Comment by ai** [comment]
@simonsmith `postcss-custom-properties` requires brackets:

```js
    postcss: [customProperties()],
```

I will finish PostCSS Plugins Guidelines on this week and all plugins will be forced to use brackets-free API.

/cc @MoOx

**Comment by simonsmith** [comment]
Ah, good spot. That solved it for me. Cheers

**Comment by MoOx** [comment]
@ai since you create a new way to declare plugin (postcss.plugin()), can you handle that automatically ? That would be cool.

**Comment by ai** [comment]
@MoOx `postcss.plugin()` already handled it.

**Comment by MoOx** [comment]
Ok I need to finish custom-properties 4.0 but one issue is still to handle.

**Comment by MoOx** [comment]
So I will be able to remove .postcss export from plugin that have it. That's nice. :)

**Comment by pburtchaell** [comment]
Hey, I am having a similar issue. My config:

```
  postcss: [
    require('postcss-custom-selectors'),
    require('postcss-custom-media'),
    require('postcss-css-variables'),
    require('postcss-nested'),
    require('autoprefixer-core'),
  ],
```

**Comment by ai** [comment]
@pburtchaell show your `module.loader` config

**Comment by pburtchaell** [comment]
@ai 
``` 
{
  test: /\.css$/,
  loader: 'style-loader!css-loader!postcss-loader?safe=1'
},
```

**Comment by ai** [comment]
Can you test your webpack processing on some prefix like:

```css
:fullscreen a {
    display: flex
}
```

**Comment by pburtchaell** [comment]
I tried it with:
```
:root h1 {
  --color: blue;
  display: flex;
  color: var(--color);
}
```

Which appears to be working. Let me try adding some more complex rules and figure out what went wrong.

**Comment by ai** [comment]
I think some of your plugins need the brackets like: `require('postcss-css-variables')()`.

@MoOx what about PostCSS 4.1 API? =^_^=

**Comment by pburtchaell** [comment]
@ai Was able to get it all working. Thanks.

**Comment by jeron-diovis** [comment]
Well, have same issue too. Now it's with postcss-mixins.
Webpack config fragment:
```js
import autoprefixer from "autoprefixer";
import mixins from "postcss-mixins";

...

  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("css?modules=true!postcss"),
      }
    ]
  },

  postcss: [
    mixins(),
    autoprefixer({
      browsers: "last 2 versions"
    })
  ],
```

styles.css
```css

@define-mixin mixThis $url {
  content: url($url);
}

.test {
  @mixin mixThis "./home.png";
}
```

And exactly the same I see in output.
The most interesting thing here is that autoprefixer works. But mixins are not.
Tried both `mixins()` and `mixins` in `postcss` array, no effect.

**Comment by MoOx** [comment]
You are using ExtractTextPlugin the wrong way, check the doc again.

**Comment by jeron-diovis** [comment]
Isn't it better to point out exactly is wrong?

I see this in docs:
> ExtractTextPlugin.extract([notExtractLoader], loader, [options])
> * loader the loader(s) that should be used for converting the resource to a css exporting module.

I see that autoprefixer works for me even with this "wrong" approach. 
And I don't understand what am I doing wrong.
This is exactly why I'm posting question here. This is for what issues are, aren't they?

**Comment by jeron-diovis** [comment]
@MoOx Actually, without ExtractTextPlugin nothing changes.
```
module: {
    loaders: [
      {
        test: /\.css$/,
        loaders: [
          "css?modules=true",
          "postcss"
        ]
      }
    ]
  },
```

And in module inside webpack bundle I still see unprocessed mixins.
What now is incorrect?

**Comment by MoOx** [comment]
I probably missed the optional `notExtractLoader`. So I have no idea.

**Comment by jeron-diovis** [comment]
Well, this becomes crazy.
I created two css files. Both contains exactly same mixin definition as shown above. Both are imported in application as modules.
In one of them mixins in first file are processed. In second one they aren't.
Even more, in second file I can write whatever I want at all, any nonsense, any symbols - and build does not fail. Content of that file is just included as-is. While when I use `composes` statement referencing this file in another modules - they work, so file actually **is** processed. 
I have no idea what the hell is going on.
