### ISSUE TITLE
Confuse with the order of precedence of scss-loader, css-loader

### ISSUE THREAD

**Issue by lim-enhui** [postcss/postcss-loader#402]
I am alittle confused with the statement below from the main page. How would this apply?
Use it after css-loader and style-loader, but before other preprocessor loaders like e.g sass|less|stylus-loader.

            {
                test: /\.scss$/,
                        use: ['css-loader', 'sass-loader', 'postcss-loader']
                })
            }

Would this be the recommended order?

**Comment by michael-ciniawsky** [comment]
Loaders are executed form right to left `dest` <=`loader-2` <= `loader-1` <= `loader-0` <= `src`

```js
{
  test: /\.ext$/,
  use: [ 'loader-2', 'loader1', 'loader-0' ]
}
```

```diff
{
   test: /\.scss$/,
-  use: ['css-loader', 'sass-loader', 'postcss-loader']
+  use: [ 'css-loader', 'postcss-loader', 'sass-loader' ]
}
```
