### ISSUE TITLE
Load postcss.config.js configs from project root by default

### ISSUE THREAD

**Issue by pavinthan** [postcss/postcss-loader#403]
### Proposal

Hi!

First thanks for your grate works,
can you please merge root `postcss.config.js` config with provided options if not specified any config files in options and `postcss.config.js` available in project root directory.

I try to add additional PostCSS plugin into my create-react-app project but It won't allow to add any additional plugins. also I tried to add that in CRA https://github.com/facebook/create-react-app/pull/5893#issuecomment-442228623 but that did not works.

if this wrong may you please check any additional way to resolve this kind of issues, thanks.

Thanks

**Comment by evilebottnawi** [comment]
`CRA` doesn't allow define own configuration https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L97 (I saw projects what allow change this behavior, use search on github). Also i don't think this related to this repo, we use `postcss-load-config` projects to load configuration, so i think you should create issue in their repo

**Comment by michael-ciniawsky** [comment]
https://github.com/michael-ciniawsky/postcss-load-config/issues/182#issuecomment-470604665
