### ISSUE TITLE
vue-cli3.0生成的项目，主题定制问题

### ISSUE THREAD

**Issue by smalldice** [postcss/postcss-loader#404]
Vue-cli 3.0生成的项目 
进行主题自定义
vue.config.js如下
`module.exports = {
  baseUrl: '',
  devServer: {
    proxy: {
      '/api': {
        target: process.env.VUE_APP_URL,
        changeOrigin: true
      }
    }
  },
  css: {
    loaderOptions: {
      sass: {
        data: `@import "./src/styles/_custom.scss"; @import "@nutui/nutui/dist/styles/variable.scss";`
      }
    }
  }
}
`
custom.scss 如下
`$primary-color: #0775F5; // 除了这里 其他都是官网的示例样式
$normal-color: #848484;
$link-color: $primary-color;
$link-hover-color: mix($link-color , #000, 80%);
$title-color: #2D2D2D;
$text-color: #848484;
$light-color: #F6F6F6;
$dark-color: #DADADA;
`

页面上验证 scss 中使用$primary-color 是正常显示我设定的色值， 但是引入ui库后， dialog toast 默认颜色还是红色

引入代码如下 (main.js)
`
import NutUI from '@nutui/nutui'
import '@nutui/nutui/dist/nutui.css'
const { Dialog, Toast } = NutUI
NutUI.install(Vue)
Vue.dialog = Vue.prototype.$dialog = Dialog
Vue.toast = Vue.prototype.$toast = Toast
`

**Comment by michael-ciniawsky** [comment]
I'm not familiar with neither `nutui` nor `vue-cli` and I don't think this is problem related to `postcss-loader`, but I think the order of @imports provided to the `data` options is incorrect. (wrong order)

> ⚠️  Google Translate

我不熟悉`nutri`和`vue-cli`，我不認為這是`postcss-loader`的問題，但我認為提供給`data`選項的@imports的順序是不正確的。 （訂單錯誤）

```diff
module.exports = { 
  baseUrl: '', 
  devServer: { proxy: { '/api': { target: process.env.VUE_APP_URL, changeOrigin: true } } }, 
  css: { 
    loaderOptions: { 
      sass: { 
-        data: @import "./src/styles/_custom.scss"; @import "@nutui/nutui/dist/styles/variable.scss";
+        data: @import "@nutui/nutui/dist/styles/variable.scss"; @import "./src/styles/_custom.scss";
      } 
    } 
  } 
}
```

**Comment by smalldice** [comment]
All right. Thank you for your solution. But the problem is still there.
