### ISSUE TITLE
no emit error when integrate stylelint

### ISSUE THREAD

**Issue by zcs19871221** [postcss/postcss-loader#406]
no emit error when integrate with stylelint

postcss-loader version: 3.0.0
stylelint version:9.10.1

i set stylelint severity as error but only show warning.
i read postcss-loader source index.js,but not found a place to emit error. 
hope to support emit error

**Comment by evilebottnawi** [comment]
It is not good idea using stylelint in postcss-loader, he doesn't validate files inside `@import` (css), anyway you can use `postcss-reporter`

**Comment by zcs19871221** [comment]
i use less loader first, then use postcss-loader, so `@import`  is ok. `postcss-reporter` can not recognize my stylelint error level config..so may be  `stylelint-webpack-plugin` is good

**Comment by zcs19871221** [comment]
or maybe i send a pr to specail handle stylelint

**Comment by evilebottnawi** [comment]
@zcs19871221 no need send a PR, i strongly recommend use CLI `stylelint` instead as part of webpack. Why:
- More abilities
- Using `stylelint` as postcss plugin or as webpack plugin increase compilation time
- All new features are immediately available.
- Easy setup.
- Stylelint plugin is abandoned due it is really bad idea.

**Comment by evilebottnawi** [comment]
Out of scope postcss-loader
