### ISSUE TITLE
Security vulnerability in js-yaml

### ISSUE THREAD

**Issue by UncertainConstraint** [postcss/postcss-loader#407]
`yarn audit` reports a security issue **js-yaml**:

| moderate | Denial of Service |
|--|--|
| Package | js-yaml |
| Patched in | >=3.13.0 |
| Dependency of | postcss-loader |
| Path | postcss-loader > postcss-load-config > cosmiconfig > js-yaml| 
| More info | https://www.npmjs.com/advisories/788 |

**Comment by evilebottnawi** [comment]
Already fixed, update your deps

**Comment by UncertainConstraint** [comment]
We are using the latest version of `postcss-loader` (v3.0.0) but the warning persists.

**Comment by EddyLuten** [comment]
Agreed with the above, we're also still receiving this error. If this was fixed, it was not released.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ postcss-loader                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ postcss-loader > postcss-load-config > cosmiconfig > js-yaml │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/813                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by CoolCyberBrain** [comment]
The problem is fixed, just delete your node_modules and package-lock.json and run npm install again.

**Comment by JohnMica** [comment]
```
postcss-load-config@^2.0.0:
  version "2.0.0"
  dependencies:
    cosmiconfig "^4.0.0"
    import-cwd "^2.0.0"
```
after deleting node_modules and .lock  still have this strange dependency on `cosmiconfig v4.0.0`` which in turn used older version of ```js-yaml``` that causes issues with security advisory

**Comment by evilebottnawi** [comment]
Please open issue in `postcss-load-config`, we can't do something on our side

**Comment by JohnMica** [comment]
Thanks

Will do and defence this one

Regards,

John Mica
