### ISSUE TITLE
BrowserlistError

### ISSUE THREAD

**Issue by shobishani** [postcss/postcss-loader#411]
I'm not sure if I am at the right place to report a bug.

`BrowserslistError: Unknown browser query `android all`

`ERROR in ./client/app/components/Sidebar/Sidebar.scss (./node_modules/css-loader??ref--71!./node_modules/postcss-loader/lib??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./client/app/components/Sidebar/Sidebar.scss)
`

I am using sass-loader and postcss-loader with webpack here is my **postcss.config.js**
`module.exports = {
  plugins: [
    require('postcss-preset-env')(),
    require('postcss-import')({ root: PATHS.root }),
    require('autoprefixer'),
  ],
}`

**Comment by michael-ciniawsky** [comment]
- Please don't use the `postcss-import` plugin with webpack (the `css-loader` handles `@import`)
- [`autoprefixer`](https://github.com/csstools/postcss-preset-env#autoprefixer) should already by part of `postcss-preset-env`, no need to add it standalone 

> `BrowserslistError: Unknown browser query android all`

Well.., your browserlist config seems to be simply invalid ¯\_(ツ)_/¯, please try another query (you can try them [here](https://browserl.ist/))
