### ISSUE TITLE
webpack stats settings ignored

### ISSUE THREAD

**Issue by jonnylink** [postcss/postcss-loader#412]
Using either `stats.warningsFilter` or even`stats: {warnings: false}` seems to have no effect on postcss warnings. I've seen a few past issues where people want to, for example, not have a console filled with warnings about linear-gradients.

While I understand this isn't great, we can't force the 3rd parties to update their css. It isn't helpful, it's noise that potentially obfuscates more serious issues. and users should be trusted to make that distinction.

I'm admittedly a bit new to webpack (and therefore also postcss), so it's possible I've made a mistake. If that's the case, then I humbly apologize. Regardless, thanks for your time and energy to make things that other people find useful (even if I'm griping about this).

### Error (Logs|Stacks)

<details>WARNING  Compiled with 20 warnings                                                                                                               11:26:08 PM

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(322:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib
/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(322:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(322:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(322:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(387:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(387:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(387:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(387:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(439:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(439:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(439:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(439:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(490:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(490:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(490:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(490:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(562:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(562:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(562:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss

 warning  in ./node_modules/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(562:3) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/css/vendor.scss 10:10-191
 @ ./resources/css/vendor.scss</details>

### Environment
npm

**Comment by michael-ciniawsky** [comment]
Please provide your `webpack.config.js`. How are you using `webpack` e.g are you using `webpack-dev-server` etc? (You need to also disable `warnings` in `config.devServer` if so). This is not 'fixable' within/by the loader itself as all it does is propagating the warnings from postcss (plugins) to `webpack` via the Loader API.
