### ISSUE TITLE
Detect and Merge Environment-specific Configurations

### ISSUE THREAD

**Issue by 9ae8sdf76** [postcss/postcss-loader#413]
### Proposal

Similar to [webpack-merge](https://www.npmjs.com/package/webpack-merge), it would be good DX to allow [merging multiple](https://www.npmjs.com/package/webpack-merge#multiple-merging) postcss configurations. This will minimize any configuration-based logic and allow developers to focus on configuring features for their target environments.

### Use Case

Split out `postcss.config.js` into three files (including `postcss.config.js`):

- postcss.config.js - the "base" configuration that other configurations will merge into
- postcss.config.development.js - development-specific configuration (e.g., no compress, inline source maps, etc)
- postcss.config.production.js - production-specific configuration (e.g., compress, no source maps, etc)

### Implementation

- [ ] I'm open to work on this
  - [ ] I need help/mentorship
- [x] I'm unable to work on this

When looking for the `postcss.config.js`, also look for an environment-specific configuration. If found, import both and do a deep copy of the environment-specific configuration into the base configuration (similar to `Object.assign({}, baseConfig, prodConfig)`).

1. If the base configuration defines a non-array/-object setting that exists in the environment configuration, then the environment configuration should overwrite the base configuration. 
1. For arrays, any duplicate items should be ignored, while new items appended to the array. 
1. For objects, any existing keys will get overwritten by the environment-specific config, and new items added. 
    - If the key is an array or object, then it follows the previous rule about appending.
1. Environment configurations that provide `null`, `undefined`, `[]`, or `{}` for items provided in the base configuration will effectively reset the values as appropriate.

**Comment by evilebottnawi** [comment]
why don't use?
```
const isDevEnv = process.env.NODE_ENV === 'develoment';

const plugins = [];

if (isDevEnv) {
  plugins.push(plugin)
}
```

>  I'm unable to work on this

So it is not required and nobody will be implement this, sorry

**Comment by 9ae8sdf76** [comment]
> why don't use?
>
> ```
> const isDevEnv = process.env.NODE_ENV === 'develoment';
>
> const plugins = [];
>
> if (isDevEnv) {
>  plugins.push(plugin)
> }
> ```

* The idea is to remove this kind of logic from the configuration.
* Improves readability of the configuration files
* Reduces environment-checking logic
* Reduces potential adverse effects to other environments
* Keeps the configuration(s) concise and easy to maintain
* New environment? No problem. Add new file `postcss.config.wednesday-morning.js`.
* No need for boilerplate logic across multiple projects when it's a part of the loader itself

>> I'm unable to work on this
>
> So it is not required and nobody will be implement this, sorry

I'll be honest that I'm taken aback by such a curt response, simply because I don't have the time and ability to implement this myself.

**Comment by evilebottnawi** [comment]
> I'll be honest that I'm taken aback by such a curt response, simply because I don't have the time and ability to implement this myself.

Unfortunately it open source project and all people don't have time, also better create issue in `postcss-load-config`, because we use this module for loading configurations

**Comment by evilebottnawi** [comment]
Please open issue in `postcss-load-config`
