### ISSUE TITLE
Use webpacks resolve.modules

### ISSUE THREAD

**Issue by felixoi** [postcss/postcss-loader#414]
### Proposal

Make use of the `resolve.modules` option of webpack to find plugins

### Use Case

When the modules are installed into a different directory it's harder to add plugins-

### Implementation

- [ ] I'm open to work on this
- [ ] I need help/mentorship
- [x] I'm unable to work on this

**Comment by evilebottnawi** [comment]
Why? What is use case? How postcss plugins related to modules?

**Comment by felixoi** [comment]
I am having a setup where the nodejs modules are installed in a different directory.
This ends up in using a relative path like 
```
require(Path.resolve(__dirname, "target/scala-2.12/scalajs-bundler/main/node_modules/autoprefixer"))
```
which is totally stupid since I have to staticly bind a dynamically changing folder. The problem with this is that the `postcss.config.js` is sometimes called from different base directories, so `__dirname` changes which ends up in modules are not found. This would be fixes when using the `resolve.modules` property from webpack since it always has the same base. In my case it's configured like
```
resolve.modules: [
            Path.resolve(__dirname, 'node_modules')
]
```.
With this I could just do `require('autoprefixer')` and it would automatically use the configured directory to find the node modules.

**Comment by evilebottnawi** [comment]
Please open issue `postcss-load-config`, we can pass loader context to `postcss-load-config`
