### ISSUE TITLE
Add @import-ed files as module dependencies

### ISSUE THREAD

**Issue by Vittly** [postcss/postcss-loader#420]
### Proposal

Add @import-ed files (style imports) as module dependencies to let SplitChunks work with them efficiently.

### Use Case

Let's see the https://gist.github.com/Vittly/4244ff8b65b864674ed1739144e23386.

The example contains two components Foo and Bar. And Bar is used inside Foo.
Also there are two entry points. The first entry imports only styles - Foo.scss with Bar.scss inside. The second entry imports Foo.tsx with all other stuff (styles and tsx) in it.

- Foo.tsx imports Bar.tsx
- Foo.scss does `@import` Bar.scss
- Bar.tsx and Bar.scss do nothing special
- cssOnlyEntry.ts impors Foo.scss
- hydratedEntry.tsx imports Foo.tsx
- webpack.config.js build two entries + splitChunks
- postcss.config.js uses [postcss-imports](https://www.npmjs.com/package/postcss-import) to handle `@import` clauses

It's expected from webpack.[splitChunksPlugin](https://webpack.js.org/plugins/split-chunks-plugin/#root) to build a single css-file shared between the output bundles. But it doesn't happen. Instead I got two css-files.

After hours of digging I've found the reason.

`postcss-import` produces special [type of messages for imported dependencies](https://github.com/postcss/postcss-import#dependency-message-support). These messages [are converted to file dependencies under the hood of postcss-loader](https://github.com/postcss/postcss-loader/blob/v3.0.0/src/index.js#L150-L152). It's done for file watching only. But SplitChunks works with [modules only](https://github.com/webpack/webpack/blob/v4.41.2/lib/optimize/SplitChunksPlugin.js#L371-L376). So `@import` of style within another style is not the same as `import` in script file.

Style imports are not processed by SplitChunks. And that's a pity.

Whereas [css-loader do the job](https://github.com/webpack-contrib/css-loader/blob/v1.0.0/lib/loader.js#L52-L68).

### Implementation

I've fixed it by additional loader:

```js
'use strict';

module.exports = function(content) {
    var requiredJs = [];

    // get file dependencies produced by postcss-loader
    this.getDependencies().reverse().forEach(dep => {
        if (dep.endsWith('.scss') && !this.currentRequest.endsWith(dep)) {
            // and convert them to cjs-imports
            requiredJs.push(
                'require("' + dep + '");'
            );
        }
    });

    const result = [...requiredJs, content].join('\n');

    return result;
};
```

But it is a tricky way to solve the problem. May be maintainers will offer something else.

- [ ] I'm open to work on this
- [x] I need help/mentorship
- [ ] I'm unable to work on this

**Comment by evilebottnawi** [comment]
Sorry, it is out of scope postcss-loader, you can do it using https://github.com/webpack-contrib/mini-css-extract-plugin, please use stackoverflow or gitter for questions

**Comment by Vittly** [comment]
Have you read my message? Can you explain how did you come to that conclusion?

**Comment by Vittly** [comment]
Let's do it in a friendly way )

**Comment by Vittly** [comment]
mini-css-extract [keeps fileDeps as files](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/v0.8.0/src/loader.js#L147-L149). It doesn't convert it to modules. Was it your point?

**Comment by evilebottnawi** [comment]
Better create own loader/plugin for this cases, it is really out of scope this loader, here only transformation - something like css -> css

**Comment by Vittly** [comment]
Moved it to https://stackoverflow.com/questions/59137254/postcss-import-ed-modules-arent-actually-split-by-splitchunksplugin
