### ISSUE TITLE
Expose Webpack aliases for files processed by PostCSS

### ISSUE THREAD

**Issue by qntndev** [postcss/postcss-loader#424]
### Proposal

A way to use aliases defined in `webpack.config.js` so we can use it in commonJS files processed by PostCSS

### Use Case

For example using **tailwindcss**, we will be able to define an alias and referenced it in `tailwind.config.js` (which is processed by PostCSS via `postcss-loader`) to manage paths in a more simplier way.

```js
//webpack.config.js
module.exports = {
  resolve: {
    alias: {
      TailwindPlugins: path.resolve(__dirname, 'src/assets/styles/plugins')
    }
  }
};
```

**Implementations expected to work**

```js
//tailwind.config.js
module.exports = {
  //...
  plugins: [
    require('./src/assets/styles/plugins/reset'),  //✅
    require('@/assets/styles/plugins/reset'),      //doesn't work actually
    require('TailwindPlugins/reset')               //doesn't work actually
  ]
}
```

### Implementation

- [ ] I'm open to work on this
- [ ] I need help/mentorship
- [x] I'm unable to work on this

If expose aliases defined in `webpack.config.js` is not possible maybe an option available in `postcss.config.js` can be way to solve it.

**Comment by evilebottnawi** [comment]
`require` is part of node.js we can't change how they works, sorry
