### ISSUE TITLE
Add a way to suppress URL path check error

### ISSUE THREAD

**Issue by luiscla27** [postcss/postcss-loader#431]
### Proposal

Please include a way to tell `postcss-loader` that it should not try to resolve an URL path

### Use Case

In my case I have an image which his URL path doesn't exists until the application is running, I'm doing this:
```
.user-custom-bg {
  background-image: url(../style/s-welcome-bg.style);
}
```
The thing is that` ../style/s-welcome-bg.style` doesn't exist at compilation time so the `CssSyntaxError` is thrown:

```
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: C:\path\to\project\some\some.component.scss:64:25: Can't resolve '../style/s-welcome-bg.style' in 'C:\path\to\project\some\'
```
### Implementation

- [ ] I'm open to work on this
- [ ] I need help/mentorship
- [X] I'm unable to work on this

Something like this:
```
.user-custom-bg {
  /** postcss-loader: skip-next-line **/
  background-image: url(../style/s-welcome-bg.style);
}
```
Anything that is written after `/** postcss-loader: skip-next-line **/` should be ignored at `postcss-loader`

If there's already a workaround for my use case you can close this fr. I tried to get feedback for this [here](https://github.com/stylelint/stylelint/issues/2215#issuecomment-631814191) at the `stylelint` project

**Comment by evilebottnawi** [comment]
postcss-loader does't work with urls, it does css-loader and we already have `url` option for this

**Comment by luiscla27** [comment]
What do you mean that you already have `url` option for this?? You mean [the url option form css-loader](https://github.com/webpack-contrib/css-loader#boolean)??

I tried that, however it seems that Angular [is not intended that developers modify the webpack configuration](https://stackoverflow.com/a/40762015/1657465) .. that's way to much work for just to skip a simple validation.

**Comment by evilebottnawi** [comment]
Please open an issue in angular repo, it is out of scope postcss-loader
