### ISSUE TITLE
Work with webpack and postcss-loader.

### ISSUE THREAD

**Issue by TheLarkInn** [postcss/postcss-loader#45]
Is it possible to make this work with webpack and the postcss-loader?

**Comment by MoOx** [comment]
This does not have sense since you are posting an issue on postcss-loader tracker (which is obviously made for webpack, as it's a loader).
Did you read the readme?

**Comment by ai** [comment]
Yes, postcss-loader is a special module (“loader” in webpack terms) to run PostCSS inside webpack.
