### ISSUE TITLE
Does this loader prefix styles within a React component?

### ISSUE THREAD

**Issue by Ehesp** [postcss/postcss-loader#47]
Hello,

I'm working on a React project, and I'm using [Radium](https://github.com/FormidableLabs/radium).

I'm not sure whether from the docs this loader will work the way styles are inlined... For example

```
export default class Test extends Component {
    render() {
        return <div style={styles.test}>Hello!</div>;
    }
}

const styles = {
    test: {
        width: 100,
        height: 100
    }
};
```

Obviously here's there is nothing to prefix, but how would this loader handle styles like this?

**Comment by ai** [comment]
Nope. You can use postcss-js to handle CSS-in-JS styles.
