### ISSUE TITLE
Source maps not generated for resolve-url-loader

### ISSUE THREAD

**Issue by doxavore** [postcss/postcss-loader#50]
I think this may only be a question/user error and not so much a bug. I have some CSS files that I would like to run through postcss (including a customized cssnano config), then pass those results through `resolve-url-loader` *or an equivalent loader*. However, `resolve-url-loader` requires sourcemaps, and I don't see how to generate them with just this loader. I am attempting to use this configuration:
```js
  {
    test: /\.css$/,
    loader: ExtractTextPlugin.extract('style', 'css?-minimize!resolve-url!postcss')
  }
```
Is there a `map` option I can pass to postcss-loader? Looking over the source, it appears it may honor source maps if they already exist, but when I append `sass?sourceMap` to the loaders (so that it runs before postcss) then `resolve-url-loader` doesn't receive a mapping.

Should a different loader be used with postcss instead of the resolve-url loader?

**Comment by ai** [comment]
This loader generates source map by default https://github.com/postcss/postcss-loader/blob/master/index.js#L13-L16

**Comment by doxavore** [comment]
Just to follow up, it appears that `resolve-url-loader` only likes inline sourcemaps. For anyone who is not using PostCSS's file resolution methods, it seems to work by moving `resolve-url-loader` before `postcss-loader`, eg:
```js
  {
    test: /\.css$/,
    loader: ExtractTextPlugin.extract('style', 'css?-minimize!postcss!resolve-url')
  }
```

**Comment by craigcosmo** [comment]
@doxavore before or after? in your code you pust resolve-url after postss
