### ISSUE TITLE
Add NPM install steps to `README.md`

### ISSUE THREAD

**Issue by wesleyb-io** [postcss/postcss-loader#60]
These are obvious steps for some developers, but a `README.md` that explicitly lists **all** steps for a "Usage" section is more complete, and may be helpful for newcomers to the web build process.

```bash
npm install postcss-loader --save-dev
npm install autoprefixer --save-dev
npm install precss --save-dev
```

**Comment by ai** [comment]
Sure. Do you want to send PR?
