### ISSUE TITLE
Need an example for cssmodules and replacing css-loader by postcss-modules plugin.

### ISSUE THREAD

**Issue by Strate** [postcss/postcss-loader#62]
Hi all!

I have tried to replace `css-loader?modules` with `postcss-loader` with `postcss-modules`, but got an errors in compile time.
Could you provide simple example how to do that?

**Comment by ai** [comment]
What error did you have a what config do you use?

/cc @outpunk

**Comment by Strate** [comment]
Config (cut):
```
const autoprefixer = require("autoprefixer")
const postcssModules = require("postcss-modules")
module.exports = {
  // ....
  module: {
    // ....
    loaders: [
      test: /\.css$/
      loaders: [
        "style",
        "postcss"
      ]
    ]
  },
  postcss: function() {
    return [autoprefixer, postcssModules]
  }
}
```
Got an error like:
```
Line 1: Unexpected token .
You may need an appropriate loader to handle this file type.
| ._headerCard_12w42_1 {
|   margin-bottom: 7px;
|   display: table;
```

Seems that it happens because `postcss-loader` with `postcss-modules` emits a json, not a commonjs module. How can it be fixed?

**Comment by ai** [comment]
@Strate how did you use CSS file in JS?

**Comment by Strate** [comment]
```jsx
const style = require("./style.css")
return <div className={style.myClassName} />
```
This is standard way to do with `css-loader?modules` loader

**Comment by ai** [comment]
@Strate nope, you miss whole idea of postcss-modules. It doesn’t return a JSON. It saves JSON to separated file. So you should load it by `require("json!./style.css.json")` (or you can move `json!` to webpack config)

**Comment by Strate** [comment]
Could you please remove this line in readme?
> or replace css-loader with postcss-modules plugin.
Because I can't just replace css-loader without complete rewriting all my code.

**Comment by ai** [comment]
Done https://github.com/postcss/postcss-loader/commit/6c15025b3cf006b1e17fa0ed8a0d1c0a5a1ccf4e
