### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'postcss' of undefined

### ISSUE THREAD

**Issue by tmaximini** [postcss/postcss-loader#65]
Seeing this error when I try to incorporate postcss with webpack:

```
Module build failed: TypeError: Cannot read property 'postcss' of undefined
        at Processor.normalize (/Users/tmaximini/data/frontend-node/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:53:18)
        at new Processor (/Users/tmaximini/data/frontend-node/node_modules/postcss-loader/node_modules/postcss/lib/processor.js:23:29)
        at postcss (/Users/tmaximini/data/frontend-node/node_modules/postcss-loader/node_modules/postcss/lib/postcss.js:55:12)
        at Object.module.exports (/Users/tmaximini/data/frontend-node/node_modules/postcss-loader/index.js:46:5)
```

Webpack Config
```
const path = require('path');
const webpack = require('webpack');
const cssnano = require('cssnano');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const stylesPath = path.resolve(__dirname, 'client/styles');

module.exports = {
    devtool: false,
    entry: {
        app: __dirname + '/client/Entry.js'
    },
    output: {
        path: __dirname + '/public/dist/',
        filename: 'bundle.js',
        chunkFilename: '[name].js',
        publicPath: '/dist/'
    },
    plugins: [
        new webpack.DefinePlugin({
            '__DEV__': false // set global variable __DEV__ to true
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                unused: true,
                dead_code: true,
                warnings: false
            }
        }),
        new ExtractTextPlugin('css/[name].[contenthash:5].css', {
            disable: false,
            allChunks: true
        }),
        new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js')
    ],
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract(
                    'style',
                    'css!postcss!sass'
                )
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015', 'react', 'react-hmre', 'stage-0']
                }
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            }
        ]
    },
    postcss: cssnano({
        autoprefixer: {
          add: true,
          remove: true,
          browsers: ['last 2 versions']
        },
        discardComments: {
          removeAll: true
        },
        discardUnused: false,
        mergeIdents: false,
        reduceIdents: false,
        safe: true,
        sourcemap: true
    })
};
```

If I remove `!postcss` from the Loaders it builds fine.

```
"postcss-loader": "^0.8.0",
"css-loader": "^0.23.1",
"cssnano": "^3.5.2",
"sass-loader": "^3.2.0",
"style-loader": "^0.13.0",
```

thanks in advance.

**Comment by MoOx** [comment]
postcss entry expect a function that returns postcss plugins, not directly a postcss plugins.
Change `postcss: cssnano( ` to `postcss: function () { return [ cssnano(` or something like that. Please read the documentation and example in the README.

**Comment by tmaximini** [comment]
Thanks, that worked!

**Comment by siemiatj** [comment]
Just for the recard, I got the same error when using old postcss version with webpack 4 config.

**Comment by Ghanshyam-K-Dobariya** [comment]
Now I am also facing same issue & I fixed ... I followed this post

https://dev.to/daveirvine/postcss-with-css-modules-andreact-51ln

I upgraded version of  below 

![image](https://user-images.githubusercontent.com/5426993/59352358-10272380-8d3e-11e9-8a5d-6a58a6432989.png)

to

![image](https://user-images.githubusercontent.com/5426993/59352383-203f0300-8d3e-11e9-8f85-62409f0434af.png)

How I came to know what to do ??

1. open your package-lock.json
2. search which libraries are using "postcss"
3. They must be using same version (major) of "postcss"

I am using "postcss": "^7.0.17"

Let me know if you still face the same issue.

**Comment by princesodhi** [comment]
> Now I am also facing same issue & I fixed ... I followed this post
> 
> https://dev.to/daveirvine/postcss-with-css-modules-andreact-51ln
> 
> I upgraded version of below
> 
> ![image](https://user-images.githubusercontent.com/5426993/59352358-10272380-8d3e-11e9-8a5d-6a58a6432989.png)
> 
> to
> 
> ![image](https://user-images.githubusercontent.com/5426993/59352383-203f0300-8d3e-11e9-8f85-62409f0434af.png)
> 
> How I came to know what to do ??
> 
> 1. open your package-lock.json
> 2. search which libraries are using "postcss"
> 3. They must be using same version (major) of "postcss"
> 
> I am using "postcss": "^7.0.17"
> 
> Let me know if you still face the same issue.

worked for me
