### ISSUE TITLE
Hot reloading variables

### ISSUE THREAD

**Issue by dacz** [postcss/postcss-loader#66]
Hi, I'm using css variables from js file that is loaded from webpack. Works great but not watch for changes and when I change variables.js, I need to restart webpack dev server.

Is there any way how to hot reload variables?

in webpack loaders

```
test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader')
```

in webpack (too)

```
postcss: function () {
    return [
      require('postcss-custom-properties')({
        variables: require('./srcClient/cssUtils/variables.js')
      }),
      require('autoprefixer'),
      require('precss')
    ];
  },
```

variables:

``` javascript
module.exports = {
  textFontFamily:   'Helvetica, Arial',
  headerFontFamily: 'Helvetica, Arial',
  fontSize:         '15px',
  lineHeight:       '1.45',

  gutter: '32px',
  pad:    '16px',

  mainColor:      '#ef007f', // pink
  secondaryColor: '#f4d428', // yellow
  addColor:       '#00a2ff', // blue
  textColor:      '#333',
  bgrColor:       'white',

};
```

Thanks!

**Comment by ai** [comment]
cc @MoOx

**Comment by MoOx** [comment]
hot loading can be done for compiled code and config is not compiled.

2 workarounds for you:
- [use a imported files (so hot loading ok)](https://github.com/postcss/postcss-loader#integration-with-postcss-import)
- [auto restart webpack when webpack config changes](https://github.com/webpack/webpack-dev-server/issues/440)

**Comment by dacz** [comment]
@MoOx Thanks. I was trying to avoid imports for the reason that I need to explicitly import variables to all css modules that needs them (and most do, because I use variables as default padding, main color, etc.). Restart webpack is burden for me (bigger project, long time to restart), so I hoped that css loader may be instructed to reload when variables.js changes. No luck with this so I reverted to (more clear but more typing) import to every module that needs variables.

Would be nice that postcss loader used with variables (when this func exists) has hot reloading made built in. I'd help but I'm new to webpack.

Thanks anyway!

**Comment by chibicode** [comment]
In case someone finds this helpful, [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars#variables) allows hot reloading of variables.

**Comment by MoOx** [comment]
I just found a simple trick to hot load entire postcss config that even rebuild everything when you save your config from an external file.

https://twitter.com/MoOx/status/797906437259169793

You might add that in the readme.

**Comment by ai** [comment]
Big snippets is not good UX. Could we integrate it to `postcss-loader` on development environment?

**Comment by MoOx** [comment]
Here is the raw config:

```js
const postcssPluginFile = require.resolve("./postcss.config.js")

// ...
postcss: (webpackInstance) => {
    // hot loading on postcss config
    webpackInstance.addDependency(postcssPluginFile)
    delete require.cache[postcssPluginFile]
    return require(postcssPluginFile)(config)
  }
```

I guess you can handle that directly in the core: if postcss option is a string (we assume a path), you play the snippet. In my case, "config" is the [webpack env option](https://webpack.js.org/how-to/upgrade-from-webpack-1/#using-custom-arguments-in-cli-and-configuration) which is mandatory to tweak the postcss config

eg:

```js
module.exports = (config) => [
    require("stylelint")(),
    require("postcss-cssnext")({
      browsers: "last 2 versions",
      features: {
        customProperties: {
          variables: {
            maxWidth: "60rem",
            colorPrimaryDark: "#107491",
            colorPrimary: "#007acc",
            colorSecondaryDark: "#22846C",
            colorSecondary: "#46BE77",
            colorNeutralDark: "#111",
            colorNeutral: "#8C8D91",
            colorNeutralLight: "#FBFCFC",
            colorText: "#555",
          },
        },
      },
    }),
    require("postcss-reporter")(),
    ...!config.production ? [
      require("postcss-browser-reporter")(),
    ] : [],
  ]

```

**Comment by ai** [comment]
Hm, in most of cases users will use `require()` in config as the most common way for every cases. So we will not have a path.

@michael-ciniawsky do you have any ideas, maybe?

**Comment by ai** [comment]
Maybe we could provide some syntax sugar like:

```js
export default ctx => {
  hotReload: [
    './my-plugin'
  ],
  plugins: [
    require('./my-plugin')
    require('stanble-3rd-party-plugin')
  ]
}
```

**Comment by ai** [comment]
But will we calculate `./my-plugin` path correctly?

**Comment by MoOx** [comment]
The only way to get this working is by letting postcss-loader doing the require on each compilation (with a fresh node cache) with an absolute path (so we can clean the node cache, which is stored with absolute path). That's why I used path.resolve().

Using a require() before runtime just make this impossible...

You current "syntax sugar" is at the end more long than this

```js
  postcss: path.resolve("./postcss.config.js")
```

(then the config in the file export a function like I just shown in a previous comment)

**Comment by michael-ciniawsky** [comment]
@MoOx  Cool 😛 


@ai `postcss-load-config` simply must expose the config (postcss.config.js) filepath e.g 

### Current

```js
postcssrc(ctx).then((config) => {
   console.log(config.plugins)
   console.log(config.options)
})
```

### Needed

```js
postcssrc(ctx).then((config) => {
   console.log(config.file) // => e.g `${process.cwd()}/path/to/postcss.config.js` (absolute)
   console.log(config.plugins)
   console.log(config.options)
})
```

### CLI

```
if (argv.watch) {
   // Watch postcss.config.js
   postcssrc(ctx).then((config) => {
      chokidar
       .watch(config.file)
       .on('change', () => postcss()...) // Restart the CSS Input processing
  })
  // Watch CSS Input
  chokidar
    .watch(input)
    .on('change', (file) => postcss()...) // Restart the CSS Input processing
  })
}
```

### Gulp

I have some ideas with gulp.watch/chokidar && child_process.spawn but not really noteworthy atm :). Although possible...


### Webpack

@MoOx's  concept but inside of `postcss-loader`, needs more investigation from my side nevertheless ;)

##### Current

```js
if ( typeof options !== 'undefined' ) {
            return parseOptions.call(loader, options, pack);
        } else {
            if ( pack ) {
                throw new Error('PostCSS plugin pack is supported ' +
                                'only when use plugins in webpack config');
            }
            return loadConfig({ webpack: loader }, path.dirname(file));
        }
```

#### Maybe 😛 

```js
if ( typeof options !== 'undefined' ) {
            return parseOptions.call(loader, options, pack);
        } else {
            if ( pack ) {
                throw new Error('PostCSS plugin pack is supported ' +
                                'only when use plugins in webpack config');
            }

             var config =  loadConfig({ webpack: loader }, path.dirname(file))
               .then((config) => {
                   loader.addDependencyTo(config.file)
                   // TODO => Invalidate caches (webpack, cosmiconfig) correctly 
                   return loadConfig({ webpack: loader }, path.dirname(file))
               })

            return config
        }
```

@davidtheclark What is the best way to clear the cosmiconfig cache, do you have any ideas in general on this subject? :)

**Comment by michael-ciniawsky** [comment]
I discussed HMR with folks in the webpack slack and it's seems not to be possible to add it to the  loader itself, `postcss.config.js` is watched and rebuilds on changes, closing for now as won't fix.

**Comment by franciscolourenco** [comment]
@michael-ciniawsky to clarify, is `postcss.config.js` watched and rebuild by default? Or does it need the setup proposed by @MoOx?

**Comment by franciscolourenco** [comment]
@michael-ciniawsky is it possible to watch variable files imported in postcss.config.js or do they need to be added as dependencies like @MoOx suggested and the cache invalidated?
