### ISSUE TITLE
Add documentation why precss is required

### ISSUE THREAD

**Issue by MartinMuzatko** [postcss/postcss-loader#68]

**Comment by ai** [comment]
PreCSS is not required :)

**Comment by MartinMuzatko** [comment]
Yes,  I just noticed that. I was looking for a guide how to use autoprefixer, as the old package is outdated for webpack (see https://github.com/passy/autoprefixer-loader)

Quickly after taking a second look, I saw that this was just an example in this guide.. Thanks for clearing that up anyway :)
