### ISSUE TITLE
How to compose `postcss` definitions?

### ISSUE THREAD

**Issue by bebraw** [postcss/postcss-loader#69]
I have a little problem at **webpack-merge** (https://github.com/survivejs/webpack-merge/issues/18). As **postcss-loader** relies on `postcss: function() {...}` kind of definition, it's hard to compose in a generic way. The question is how/where to solve this.

Do you think it would be possible to expand `postcss` definition to support an array? After that you would end up with `postcss: [function() {...}, function() {...}, ...]`. This array would be then composed at `postcss` (evaluated left to right).

If this sort of interface is acceptable, I could craft a PR for you.

**Comment by ai** [comment]
Are you asking about using different plugins for different loaders? https://github.com/postcss/postcss-loader#plugins-packs

**Comment by bebraw** [comment]
The problem is that

```javascript
postcss: function () {
    return {
        defaults: [precss, autoprefixer],
        cleaner:  [autoprefixer({ browsers: [] })]
    };
}
```

isn't composable either.

I cannot tell from outside a function what it's going to return. What I would like to achieve is just that.

**Comment by ai** [comment]
Sorry, I am not native. What do you mean for compose in this issue?

**Comment by bebraw** [comment]
To give you a better idea, here's what a **webpack-merge** part could look like if we had something composable:

```javascript
exports.enableStylelint = function(paths) {
  return {
    module: {
      preLoaders: [
        {
          test: /\.css$/,
          loaders: ['postcss'],
          include: paths
        }
      ]
    },
    postcss: [
      function () {
        return [
          stylelint({
            rules: {
              'color-hex-case': 'lower'
            }
          })
        ];
      }
    ]
  };
}
```

**Comment by bebraw** [comment]
The tool can deal with objects and arrays. We would have to do array -> fn to adapt. Redux [compose](http://redux.js.org/docs/api/compose.html) does this essentially.

**Comment by ai** [comment]
Ouh, you mean that there are some webpack tools, that could merge few configs into a one config, but they will generate a arrays inside arrays in PostCSS plugin, so PostCSS plugin will not work?

**Comment by bebraw** [comment]
Basically **webpack-merge** `concats` arrays and merges objects. The problem is that I cannot do this type of work with pure functions. Those will get replaced.

**Comment by ai** [comment]
Ouh, OK.

You need to send PR (I don't use this webpack tool and could not test the solution). I will accept it and release a version (I could do it for 1 day after May 12, right now I am preparing for talk).

**Comment by bebraw** [comment]
Ok, I'll get it done. Good luck with the talk. 👍

**Comment by bebraw** [comment]
I actually realized postcss-loader supports arrays already (good to mention at the README).

This commit (https://github.com/postcss/postcss-loader/commit/1ab50df0ca88baab8f918326ac360afcec8f71f6) illustrates the support.

Sorry for the delay. I've been a bit busy with work. 😈
