### ISSUE TITLE
why 'style!css!postcss!sass' is not work?

### ISSUE THREAD

**Issue by pengxueshan** [postcss/postcss-loader#71]

**Comment by ai** [comment]
Show me your config, your input and output.

**Comment by ai** [comment]
Of course, you should write a issue description and show why you thing it doesn’t work. Do it throw a error? Or return empty string? Or do not apply PostCSS plugins (what plugins exactly).

**Comment by binjospookie** [comment]
Try to use this:
`{
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(
          'css-loader?modules' +
          '&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]' +
          '!postcss-loader' +
          '!sass'
        ),
      },'`

**Comment by kevinSuttle** [comment]
@binjospookie Do you need to use `ExtractTextPlugin` to be able to specify a `localIdentName`?
