### ISSUE TITLE
Example setup for usage with postcss-devtools

### ISSUE THREAD

**Issue by export-mike** [postcss/postcss-loader#73]
I've been trying to get devtools to work with a webpack config.

I'm sure others would appreciate some documentation on how to do this.

**Comment by ai** [comment]
Sorry, I can't have a section for every plugin 😞. Documentation will be too long and unreadable.

Maybe you should ask in postcss-devtools repo for help?

**Comment by export-mike** [comment]
sure! see: https://github.com/postcss/postcss-devtools/issues/17
