### ISSUE TITLE
PostCss not applied

### ISSUE THREAD

**Issue by arddor** [postcss/postcss-loader#75]
Hello
I have the problem that apparently no transformation is done on the css. I tried for several hours but I don't find the reason. The css module changes are applied (you can see the hash) however postcss modules are not applied. I tried with several things which should go with precss (e.g. variables) but it does not work, even worse the rest of the css is not processed, because it is faulty. 

Webpack configs:
```
loaders: [
  {
    test: /\.css?$/,
    loaders: [ 'style', 'css?modules&importLoaders=1&localIdentName=[local]---[hash:base64:5]', 'postcss' ],
    include: path.resolve(__dirname, '../src')
  }
],
postcss: function () {
  return [
    require('precss')(),
    require('autoprefixer')(),
    require('cssnano')()
  ]
}

**Comment by MoOx** [comment]
Do you use import statements?

**Comment by arddor** [comment]
Yes, the css modules work and the elements are styled, however there are just no PostCss transformations done. When I then try to use syntax from precss (e.g. mixins, variables, ...) nothing is in the resulting css. If I put the precss stuff before existing "normal" css then some if it also no longer works.

**Comment by ai** [comment]
Can you should some example of your CSS?

Also you don’t need cssnano in postcss, css-loader already use it.

**Comment by arddor** [comment]
Short trivia to the css: I'm trying to make some styled buttons with React and PostCss. I figured I could use precss mixins to minimize the repetition. The css how it is now works, but if you add for example a variable (e.g. $blue: #056ef0;) before .default the result will be that all the styling from .default is no longer applied while the color from .primary is still there. The reason that this works is because of the browser support for the variables (--primary-color).

```
@import url('../../styles/variables.css');

/* $blue: #056ef0; */

.default{
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.primary{
    composes: default;
    background-color: var(--primary-color);
}

.success{
    composes: default;
    background-color: var(--success-color);
}

.info{
    composes: default;
    background-color: var(--info-color);
}

.warning{
    composes: default;
    background-color: var(--warning-color);
}

.danger{
    composes: default;
    background-color: var(--danger-color);
}

**Comment by MoOx** [comment]
You need to use postcss-import. (use v7 as v8 is buggy and will be replaced soon)
