### ISSUE TITLE
Loader does not resolve non-relative modules

### ISSUE THREAD

**Issue by pke** [postcss/postcss-loader#76]
I have this webpack config

```
resolve: {
    extensions: ["", ".js", ".jsx"],
    root: [
      path.join(process.cwd(), "src"),
    ],
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loaders: ["babel"],
        exclude: /node_modules/,
        include: src,
      },
      {
        test: /\.json$/,
        loader: "json",
      },
    ],
  },
```

Which works. When I mix in the `postcss-loader` as described in the readme, the modules relative to `src` are no longer found

```
app
app/src
app/src/index.js
app/src/api
app/src/api/api.js
```

and in `index.js` it says:
`import api from "api/api` 

This resolves fine with my original config but throws `api/api` not found when using this loader.

**Comment by ai** [comment]
Could you show config with PostCSS?

**Comment by pke** [comment]
@ai Sure, just copied what I found in the readme, as written above.

```
resolve: {
    extensions: ["", ".js", ".jsx"],
    root: [
      path.join(process.cwd(), "src"),
    ],
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: "style-loader!css-loader!postcss-loader?parser=postcss-js!babel",
        exclude: /node_modules/,
        include: src,
      },
      {
        test: /\.json$/,
        loader: "json",
      },
    ],
  },
```

**Comment by ai** [comment]
Do you load JS module and then you have a issue? Very strange. I have no idea where I should look. Maybe you should ask in webpack chat and they will have some ideas?

**Comment by pke** [comment]
well it works when I remove all the css loader stuff and just leave:
`loader: babel`

So, the webpack setup seems correct.

**Comment by pke** [comment]
So the actual console output is:

```
ERROR in ./src/index.js
Module build failed: Error: Cannot find module 'api/api'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> \app\src\index.js:15:12)
    at Module._compile (module.js:541:32)
    at Object.loaderContext.exec (\app\node_modules\webpack-core\lib\NormalModuleMixin.js:88:7)
    at Object.module.exports (\app\node_modules\postcss-loader\index.js:59:23)
```

**Comment by ai** [comment]
Ouh, I see. I mess that you use `postcss-js`. Could you show me your style file?

**Comment by pke** [comment]
There are no style files. All styles are inline, in the `.js*` files. There is no style in `index.js`, the entry file that contains the import to `api/api`. As written, when I leave out postcss-loader as a loader, the config works just fine.

**Comment by ai** [comment]
Ouh, I understand the issue :). You are using postcss-loader in wrong way ;).

If you have style object in JSX files:

```js
const style = {
  display: 'flex'
}

export class Logo extends React.Component {
}
```

you don’t need `postcss-loader` at all. `postcss-loader` is used *only* when you store styles in separated files like:

```js
export default {
  display: 'flex'
}
```

Use [postcss-js](https://github.com/postcss/postcss-js) or [babel-plugin-csjs-postcss](https://github.com/rtsao/babel-plugin-csjs-postcss) if you want to process styles in JSX files.

**Comment by pke** [comment]
So there is no solution out there to use webpack to transform all occurrences of inline styles like those?

```es6
const STYLE = {
  display: "flex"
}

const Component = () => (
  <div style={STYLE}/>
)

const OtherComponent = () => (
  <Component><div style={{ display: "inline" }}/></Component>
)
```

**Comment by ai** [comment]
I give you a 2 links for solutions — look to last paragraph ;).

**Comment by pke** [comment]
I checked your 2 solutions. Both are not doing what I hoped they would. Both require code changes, that would be massive in our code base.

Maybe I need to read up on how babel transform plugins work and do this `wherever a style prop is used replace it with a call to `prefixer(style)`.

**Comment by ai** [comment]
Yeap, there is no solution withour code changes right now. But you could write a Babel plugin to do it.
