### ISSUE TITLE
Plugins config as object instead of array

### ISSUE THREAD

**Issue by texastoland** [postcss/postcss-loader#78]
I'm using your plugin this way:

```js
{
  postcss: (context) => ({
    import: { // must run first
      addDependencyTo: context,
      path: "src",
    },
    cssnext: true,
    reporter: { // must run last
      clearMessages: true,
      noIcon: true,
    },
  }),
}
```

…and later with a library function:

```js
config.postcss = Object.entries(config.postcss)
  .filter(([key, options]) => options !== false)
  .map(([key, options]) => [require("postcss-" + kebabCase(key)), options])
  .map(([plugin, options]) => options === true ? plugin : plugin(options))
```

I could generalize it if you're interested in accepting either an array of plugins (current behavior), array of plugin names, config of plugin names, or function returning one of the above?

**Comment by ai** [comment]
Some plugins will be loaded from relative paths. But we are thinking about global PostCSS config and it will work with this syntax in simple cases

https://github.com/postcss/postcss/issues/813
