### ISSUE TITLE
How to run postcss on ExtractTextPlugin's output?

### ISSUE THREAD

**Issue by lochstar** [postcss/postcss-loader#84]
I'm creating a postcss plugin that outputs a JSON object after reading CSS input. It does not mutate the CSS.

I'm trying to execute postcss during my build, AFTER my CSS has been merged and optimised. It's the final step in my build process, it cannot run before css-loader.

Does anyone know if this can be accomplished with ExtractTextPlugin? I've tried many configurations and have had no luck. A similar question is asked [here](https://stackoverflow.com/questions/36122012/how-to-run-postcss-after-sass-loader-and-extracttextplugin-have-finished) but is unanswered.

Forgive me if this question would be better asked at ExtractTextPlugin.

**Comment by ai** [comment]
Sorry, I have no idea too 😞
