### ISSUE TITLE
Workaround for this.exec?

### ISSUE THREAD

**Issue by 7rulnik** [postcss/postcss-loader#86]
Hi! Thanks for postcss and loader for it. It's really awesome. But…

I want to use SugarSS parser with https://github.com/amireh/happypack but it cannot work with `this.exec`.
Does it really necessary? Or maybe exist any workarounds?

**Comment by ai** [comment]
Hi. Thanks for good issue start text 😆

What you mean about `this.exec`? How it could be fixed? (I didn't use HappyPack).

**Comment by 7rulnik** [comment]
[Here](https://github.com/postcss/postcss-loader/blob/master/index.js#L59) you use `this.exec` but happypack [can't support](https://github.com/amireh/happypack/wiki/Webpack-Loader-API-Support) it.

UPD: oh, I was wrong. You use exec only for `postcss-js` parser.
Sorry T____T

**Comment by ai** [comment]
So, how I could fix it?
