### ISSUE TITLE
Global config support

### ISSUE THREAD

**Issue by ai** [postcss/postcss-loader#88]

**Comment by ertrzyiks** [comment]
any progress on that? 

If I understand correctly by reading [this thread](https://github.com/postcss/postcss-loader/issues/78) it will enable object based config instead of an array, right?

**Comment by ai** [comment]
@ertrzyiks this issue is best for first PR. Do you want help me with it? (right now I am developing other project)

We already have library to load config — you need just to add it to loader: [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config).

Here is discussion about config: https://github.com/postcss/postcss/issues/813

**Comment by ertrzyiks** [comment]
@ai yeah, I would like to help. I need that change to use `postcss-loader` with `happypack` (see [corresponding thread](https://github.com/amireh/happypack/issues/84))
