### ISSUE TITLE
CSS Modules and postcss-loader

### ISSUE THREAD

**Issue by soluml** [postcss/postcss-loader#89]
In the [readme](https://github.com/postcss/postcss-loader#with-css-modules) you mention getting CSS Modules and the postcss-loader working with css-loader by using `importLoaders`.  I've been trying to get this to work, because I want access to the CSS Modules function `generateScopedName` for more customization of classnames.  

However, css-loader can't access the classnames prior to postcss-loader and so it doesn't work. For example, this is what I'm seeing with the following webpack loader string:

`css-loader?-minimize&-import&modules&importLoaders=1!postcss-loader?pack=modules!postcss-loader?pack=default`

**Original Class**
`.Font-SourceSansPro`

**postcss-loader -> creates this in the app.css.json**
`{"Font-SourceSansPro":"abcFont-SourceSansPro"}`

**css-loader -> when importing into a JS file**
`{"abcFont-SourceSansPro": "_2d42_tumF6upsotQymi9wn"}`

Ideally, we'd have this as our import into our JS file:
`{"Font-SourceSansPro":"abcFont-SourceSansPro"}`

Any ideas on what I could do to make this work? Pre-pending "abc" was just an example, I'm actually wanting to pass the class name off to another npm module for processing.  Any help would be appreciated.

Thanks!

**Comment by ai** [comment]
Sorry, you should ask CSS Modules team :(

**Comment by soluml** [comment]
Thanks for your prompt reply!

The CSS Modules bit is working fine, it's the postcss-loader passing the values to css-loader that I'm having issues with.  It's possible that what I'm trying to do won't work, but the aforementioned readme gives me hope.. it just doesn't look like importLoaders does anything with postcss-loader.

**Comment by ai** [comment]
I'm. Do you use CSS Modules from css-loader or from postcss-modules?

**Comment by ai** [comment]
I see that you use `modules` param in `css-loader`, but you told about JSON files, which could be created only by `postcss-modules`. Maybe you enable CSS Modules in `css-loader` *and* by `postcss-modules` PostCSS plugin?

**Comment by soluml** [comment]
Yea, that's what I've done.  I'm trying to use both postcss-modules and css-loader modules and I'm trying to pass in my postcss-modules stuff into css-loader.  css-loader treats the postcss-modules class as the original, which makes it impossible to use together.

**Comment by ai** [comment]
Of course, it is impossible. You need to use only one way.

**Comment by soluml** [comment]
That's too bad, I kinda figured as much.  css-loader injects the modules into the JS how I want but has limited class name customizations.  CSS Modules has a function that let's you do whatever you want with the class names, but has no way to pass that into the JS like css-loader does.

Thanks!

**Comment by ai** [comment]
You could load JSON from `postcss-loader` from React too ;).

```
const styles = require('./style.css.json')
```
