### ISSUE TITLE
why would a postcss plugin break webpack simply by including it as a variable?

### ISSUE THREAD

**Issue by alisonailea** [postcss/postcss-loader#98]
I want to use postcss-less-engine in a project but simply requiring it in my webpack.config breaks webpack.

Here's the code that breaks. But you can see I'm only requiring `postcss-less-engine` not using it in my postcss loader

```js
/* PostCSS Style Handling */
var map = require('postcss-map');
var autoprefixer = require('autoprefixer');
var nestedAncestors = require('postcss-nested-ancestors');
var nested = require('postcss-nested');
var lessEngine = require('postcss-less-engine');

...

module: {
    loaders: [
        {
            test: /\.less$/,
	    loader: ExtractLESS.extract('style-loader', ['css-loader', 'less-loader']),
        }
    ]
},
postcss: function () {
    return [
	    map(),
            nestedAncestors,
	    nested,
	    autoprefixer,
    ]
},
```

ERROR `Unable to load webpack configuration file "webpack.config.dev.js": Cannot find module 'postcss'`

BUT this code works...

```js
/* PostCSS Style Handling */
var map = require('postcss-map');
var autoprefixer = require('autoprefixer');
var nestedAncestors = require('postcss-nested-ancestors');
var nested = require('postcss-nested');
// var lessEngine = require('postcss-less-engine');

...
```

The plugin author doesn't know much about webpack and I'm still trying to learn about the postcss-loader for webpack. Any ideas?

**Comment by ai** [comment]
You should ask `postcss-less-engine`, seems like they try to require `postcss` and you didn’t install it

**Comment by ai** [comment]
Yeap, it is `postcss-less-engine` issue. They load `postcss` in `index.js`, but didn’t add `postcss` to `dependencies` in their `package.json`.

Could you create a issue there? Just put a link to my comments and mention me to subscribe me on this issue :).

**Comment by alisonailea** [comment]
thanks!!!
